using System.Linq;
using Content.Client.UserInterface.Screens;
using Content.Shared._Mono.CCVar;
using Content.Shared.CCVar;
using Content.Shared.GameTicking.Prototypes;
using Content.Shared.HUD;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class MiscTab : Control
{
    [Dependency] private IPlayerManager _playerManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IConfigurationManager _cfg = default!;
    private int _pendingLobbyBackgroundLayoutRefreshFrames = 2;

    private const string LobbyBackgroundModeServer = "server";
    private const string LobbyBackgroundModeStatic = "static";
    private const string LobbyBackgroundModeAnimated = "animated";
    private const string LobbyBackgroundUnknownTitleLoc = "lobby-state-background-unknown-title";

    public MiscTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var themes = _prototypeManager.EnumeratePrototypes<HudThemePrototype>().ToList();
        themes.Sort();
        var themeEntries = new List<OptionDropDownCVar<string>.ValueOption>();
        foreach (var gear in themes)
        {
            themeEntries.Add(new OptionDropDownCVar<string>.ValueOption(gear.ID, Loc.GetString(gear.Name)));
        }

        var layoutEntries = new List<OptionDropDownCVar<string>.ValueOption>();
        foreach (var layout in Enum.GetValues(typeof(ScreenType)))
        {
            layoutEntries.Add(new OptionDropDownCVar<string>.ValueOption(layout.ToString()!, Loc.GetString($"ui-options-hud-layout-{layout.ToString()!.ToLower()}")));
        }

        // Channel can be null in replays so.
        // ReSharper disable once ConditionalAccessQualifierIsNonNullableAccordingToAPIContract
        ShowOocPatronColor.Visible = _playerManager.LocalSession?.Channel?.UserData.PatronTier is { };

        Control.AddOptionDropDown(CVars.InterfaceTheme, DropDownHudTheme, themeEntries);
        Control.AddOptionDropDown(CCVars.UILayout, DropDownHudLayout, layoutEntries);
        var lobbyBackgroundMode = Control.AddOptionDropDown(CCVars.LobbyBackgroundType, DropDownLobbyBackgroundType, BuildLobbyBackgroundModeOptions());
        Control.AddOptionDropDown(CCVars.LobbyStaticBackground, DropDownLobbyStaticBackground, BuildLobbyBackgroundOptions(animated: false));
        Control.AddOptionDropDown(CCVars.LobbyAnimatedBackground, DropDownLobbyAnimatedBackground, BuildLobbyBackgroundOptions(animated: true));
        Control.AddOptionPercentSlider(CCVars.LobbyPanelOpacity, LobbyPanelOpacitySlider);
        Control.AddOptionPercentSlider(CCVars.UiWindowOpacity, UiWindowOpacitySlider, min: 0.75f, max: 1f);

        Control.AddOptionCheckBox(CVars.DiscordEnabled, DiscordRich);
        Control.AddOptionCheckBox(CCVars.ShowOocPatronColor, ShowOocPatronColor);
        Control.AddOptionCheckBox(CCVars.LoocAboveHeadShow, ShowLoocAboveHeadCheckBox);
        Control.AddOptionCheckBox(CCVars.HudHeldItemShow, ShowHeldItemCheckBox);
        Control.AddOptionCheckBox(CCVars.CombatModeIndicatorsPointShow, ShowCombatModeIndicatorsCheckBox);
        Control.AddOptionCheckBox(CCVars.OpaqueStorageWindow, OpaqueStorageWindowCheckBox);
        Control.AddOptionCheckBox(CCVars.ChatEnableFancyBubbles, FancySpeechBubblesCheckBox);
        Control.AddOptionCheckBox(CCVars.ChatFancyNameBackground, FancyNameBackgroundsCheckBox);
        Control.AddOptionCheckBox(CCVars.LogInChat, LogInChatCheckBox);
        Control.AddOptionCheckBox(CCVars.CoalesceIdenticalMessages, CoalesceIdenticalMessagesCheckBox);
        Control.AddOptionCheckBox(CCVars.StaticStorageUI, StaticStorageUI);
        Control.AddOptionCheckBox(CCVars.DetailedExamine, DetailedExamineCheckBox); // Goobstation Change
        Control.AddOptionCheckBox(MonoCVars.RadioNoiseEnabled, RadioNoiseCheckBox); // Mono
        Control.AddOptionCheckBox(MonoCVars.AreaEchoEnabled, AreaEchoCheckBox); // Mono
        Control.AddOptionCheckBox(MonoCVars.AreaEchoHighResolution, AreaEchoHighResolutionCheckBox); // Mono

        lobbyBackgroundMode.ImmediateValueChanged += UpdateLobbyBackgroundSelectorVisibility;
        Control.Initialize();
        UpdateLobbyBackgroundSelectorVisibilityFromDropDown();
        RequestLobbyBackgroundLayoutRefresh();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateLobbyBackgroundSelectorVisibilityFromDropDown();

        if (_pendingLobbyBackgroundLayoutRefreshFrames <= 0)
            return;

        RefreshLobbyBackgroundLayout();
        _pendingLobbyBackgroundLayoutRefreshFrames--;
    }

    private IReadOnlyCollection<OptionDropDownCVar<string>.ValueOption> BuildLobbyBackgroundModeOptions()
    {
        return
        [
            new OptionDropDownCVar<string>.ValueOption(LobbyBackgroundModeServer, Loc.GetString("ui-options-lobby-background-type-server")),
            new OptionDropDownCVar<string>.ValueOption(LobbyBackgroundModeStatic, Loc.GetString("ui-options-lobby-background-type-static")),
            new OptionDropDownCVar<string>.ValueOption(LobbyBackgroundModeAnimated, Loc.GetString("ui-options-lobby-background-type-animated")),
        ];
    }

    private IReadOnlyCollection<OptionDropDownCVar<string>.ValueOption> BuildLobbyBackgroundOptions(bool animated)
    {
        var options = new List<OptionDropDownCVar<string>.ValueOption>
        {
            new(string.Empty, Loc.GetString("ui-options-lobby-background-auto")),
        };

        var backgrounds = _prototypeManager.EnumeratePrototypes<LobbyBackgroundPrototype>().ToList();
        backgrounds.Sort((a, b) => CompareBackgroundDisplayNames(GetBackgroundDisplayName(a), GetBackgroundDisplayName(b)));

        foreach (var proto in backgrounds)
        {
            if (animated && proto.BackgroundGif == null)
                continue;

            if (!animated && proto.Background == null)
                continue;

            options.Add(new OptionDropDownCVar<string>.ValueOption(proto.ID, GetBackgroundDisplayName(proto)));
        }

        return options;
    }

    private static int CompareBackgroundDisplayNames(string left, string right)
    {
        var leftHasNumber = TrySplitTrailingNumber(left, out var leftPrefix, out var leftNumber);
        var rightHasNumber = TrySplitTrailingNumber(right, out var rightPrefix, out var rightNumber);

        if (leftHasNumber &&
            rightHasNumber &&
            string.Equals(leftPrefix, rightPrefix, StringComparison.CurrentCultureIgnoreCase))
        {
            var prefixCompare = string.Compare(leftPrefix, rightPrefix, StringComparison.CurrentCultureIgnoreCase);
            if (prefixCompare != 0)
                return prefixCompare;

            return leftNumber.CompareTo(rightNumber);
        }

        return string.Compare(left, right, StringComparison.CurrentCultureIgnoreCase);
    }

    private static bool TrySplitTrailingNumber(string value, out string prefix, out int number)
    {
        var splitIndex = value.Length;

        while (splitIndex > 0 && char.IsDigit(value[splitIndex - 1]))
        {
            splitIndex--;
        }

        if (splitIndex == value.Length || !int.TryParse(value[splitIndex..], out number))
        {
            prefix = value;
            number = 0;
            return false;
        }

        prefix = value[..splitIndex];
        return true;
    }

    private string GetBackgroundDisplayName(LobbyBackgroundPrototype proto)
    {
        if (proto.Title == LobbyBackgroundUnknownTitleLoc)
            return proto.ID;

        var localizedTitle = Loc.GetString(proto.Title);
        var plainTitle = FormattedMessage.RemoveMarkupPermissive(localizedTitle).Trim();
        return string.IsNullOrWhiteSpace(plainTitle) ? proto.ID : plainTitle;
    }

    private void UpdateLobbyBackgroundSelectorVisibility(string mode)
    {
        var normalized = string.IsNullOrWhiteSpace(mode) ? LobbyBackgroundModeServer : mode.ToLowerInvariant();
        var showStatic = normalized == LobbyBackgroundModeStatic;
        var showAnimated = normalized == LobbyBackgroundModeAnimated;

        if (DropDownLobbyStaticBackground.Visible == showStatic &&
            DropDownLobbyAnimatedBackground.Visible == showAnimated)
        {
            return;
        }

        DropDownLobbyStaticBackground.Visible = showStatic;
        DropDownLobbyAnimatedBackground.Visible = showAnimated;
        RequestLobbyBackgroundLayoutRefresh();
    }

    private void UpdateLobbyBackgroundSelectorVisibilityFromDropDown()
    {
        var selectedMode = DropDownLobbyBackgroundType.Button.SelectedMetadata as string
                           ?? _cfg.GetCVar(CCVars.LobbyBackgroundType);
        UpdateLobbyBackgroundSelectorVisibility(selectedMode);
    }

    private void RequestLobbyBackgroundLayoutRefresh()
    {
        _pendingLobbyBackgroundLayoutRefreshFrames = 2;
    }

    private void RefreshLobbyBackgroundLayout()
    {
        InvalidateMeasure();
        Control.InvalidateMeasure();

        RefreshLobbyDropDown(DropDownLobbyBackgroundType);
        RefreshLobbyDropDown(DropDownLobbyStaticBackground);
        RefreshLobbyDropDown(DropDownLobbyAnimatedBackground);
    }

    private static void RefreshLobbyDropDown(OptionDropDown dropDown)
    {
        dropDown.InvalidateMeasure();
        dropDown.InvalidateArrange();
        dropDown.Button.InvalidateMeasure();
        dropDown.Button.InvalidateArrange();
    }
}
