using System.Numerics;
using System.Linq;
using Content.Client.Shuttles.Systems;
using Content.Client.UserInterface;
using Content.Client.UserInterface.Controls;
using Content.Shared._Mono.Company;
using Content.Shared._Mono.Detection;
using Content.Shared._WH40K.SectorMap.BUI;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Components;
using Content.Shared.Shuttles.Systems;
using Content.Shared.Shuttles.UI.MapObjects;
using Content.Shared.Timing;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio;
using Robust.Shared.Audio.Systems;
using Robust.Shared.GameObjects;
using Robust.Shared.Map;
using Robust.Shared.Map.Components;
using Robust.Shared.Physics.Components;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class NavScreen : BoxContainer
{
    private const int PlanetaryTitleCharacterLimit = 18;
    private const int PlanetaryInfoCharacterLimit = 22;
    private const int PlanetaryLandingSiteCharacterLimit = 21;
    private const float PlanetaryPopupWidth = 224f;
    private const float PlanetaryPopupFallbackHeight = 226f;
    private const float PlanetaryPopupGap = 8f;
    private const float PlanetaryPopupEdgePadding = 6f;

    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private IMapManager _mapManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    private DetectionSystem _detection;
    private SharedAudioSystem _audio;
    private ShuttleSystem _shuttles;
    private SharedTransformSystem _xformSystem;

    private EntityUid? _consoleEntity; // Entity of controlling console
    private EntityUid? _shuttleEntity;
    private KoronusPlanetaryInterfaceState _planetaryState = KoronusPlanetaryInterfaceState.Unavailable();
    private string? _selectedPlanetaryBody;
    private string? _selectedLandingSite;
    private Vector2? _planetaryPanelPosition;
    private FTLState _ftlState;
    private StartEndTime _ftlTime;
    private List<ShuttleBeaconObject> _bssBeacons = new();
    private List<ShuttleExclusionObject> _bssExclusions = new();
    private readonly StyleBoxFlat _ftlStyle = new(Color.LimeGreen);
    private bool _bssMode;
    private bool _navigationSuppressed;
    private bool _bssObjectsDirty = true;
    private MapId _bssObjectMap = MapId.Nullspace;
    private TimeSpan _nextBssScan;
    private static readonly TimeSpan BssScanCooldown = TimeSpan.FromSeconds(3);

    public event Action? AutoDockRequest;
    public event Action<MapCoordinates, Angle>? RequestFTL;
    public event Action<NetEntity, Angle>? RequestBeaconFTL;
    public event Action<MapCoordinates, Angle>? RequestAutopilot;
    public event Action<NetEntity>? RequestAutopilotGrid;
    public event Action<string, string>? PlanetaryLandingRequest;
    public event Action? PlanetaryLaunchRequest;

    public NavScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _detection = _entManager.System<DetectionSystem>();
        _audio = _entManager.System<SharedAudioSystem>();
        _shuttles = _entManager.System<ShuttleSystem>();
        _xformSystem = _entManager.System<SharedTransformSystem>();
        NavRadar.ForcePannable = true;

        var navigationModeGroup = new ButtonGroup();
        NavSubModeButton.Group = navigationModeGroup;
        BssSubModeButton.Group = navigationModeGroup;
        NavSubModeButton.Pressed = true;
        NavSubModeButton.OnPressed += _ => SetNavigationMode(false);
        BssSubModeButton.OnPressed += _ => SetNavigationMode(true);

        IFFToggle.OnToggled += OnIFFTogglePressed;
        IFFToggle.Pressed = NavRadar.ShowIFF;

        IFFShuttleToggle.OnToggled += OnIFFShuttleTogglePressed;
        IFFShuttleToggle.Pressed = NavRadar.ShowIFFShuttles;

        DockToggle.OnToggled += OnDockTogglePressed;
        DockToggle.Pressed = NavRadar.ShowDocks;

        AutoDockButton.OnPressed += _ => AutoDockRequest?.Invoke();
        NavAutopilotButton.OnToggled += args => SetTargeting(args.Pressed, ShuttleNavTargetingMode.Autopilot);
        BssFTLButton.OnToggled += args => SetTargeting(args.Pressed, ShuttleNavTargetingMode.Bss);
        BssRebuildButton.OnPressed += _ => ScanBssObjects();
        PlanetaryLandingButton.OnPressed += _ => TryRequestPlanetaryLanding();
        PlanetaryLaunchButton.OnPressed += _ => PlanetaryLaunchRequest?.Invoke();
        NavRadar.PlanetSelected += OnPlanetSelected;
        NavRadar.PlanetSelectionCleared += ClosePlanetaryDetails;
        NavRadar.OnRadarClick += OnNavigationTargetSelected;

        BssFTLBar.ForegroundStyleBoxOverride = _ftlStyle;

        NfInitialize(); // Frontier Initialization for the NavScreen
    }

    private void SetNavigationMode(bool bssMode)
    {
        _bssMode = bssMode;
        NavSubModeButton.Pressed = !bssMode;
        BssSubModeButton.Pressed = bssMode;
        NavModeControls.Visible = !bssMode;
        BssModeControls.Visible = bssMode;
        CancelTargeting();

        if (bssMode && _shuttleEntity != null &&
            _entManager.TryGetComponent(_shuttleEntity.Value, out TransformComponent? shuttleXform) &&
            shuttleXform.MapID != _bssObjectMap)
        {
            _bssObjectsDirty = true;
        }

        if (bssMode && _bssObjectsDirty)
            RebuildBssObjects();
    }

    private void SetTargeting(bool pressed, ShuttleNavTargetingMode mode)
    {
        if (_navigationSuppressed || pressed && mode == ShuttleNavTargetingMode.Bss && _ftlState != FTLState.Available)
        {
            CancelTargeting();
            return;
        }

        if (!pressed)
        {
            CancelTargeting();
            return;
        }

        NavAutopilotButton.Pressed = mode == ShuttleNavTargetingMode.Autopilot;
        BssFTLButton.Pressed = mode == ShuttleNavTargetingMode.Bss;
        NavRadar.SetTargetingMode(mode);
        ClosePlanetaryDetails();
    }

    private void CancelTargeting()
    {
        NavAutopilotButton.Pressed = false;
        BssFTLButton.Pressed = false;
        NavRadar.SetTargetingMode(ShuttleNavTargetingMode.None);
    }

    private void OnNavigationTargetSelected(EntityCoordinates coordinates)
    {
        if (_navigationSuppressed || NavRadar.TargetingMode == ShuttleNavTargetingMode.None)
            return;

        var targetAngle = NavRadar.TargetAngle;
        if (NavRadar.TargetingMode == ShuttleNavTargetingMode.Autopilot)
        {
            if (NavRadar.TryGetTargetGrid(coordinates, out var targetGrid))
                RequestAutopilotGrid?.Invoke(_entManager.GetNetEntity(targetGrid));
            else
                RequestAutopilot?.Invoke(_xformSystem.ToMapCoordinates(coordinates), targetAngle);
        }
        else if (NavRadar.TryGetTargetBeacon(coordinates, out var targetBeacon))
        {
            RequestBeaconFTL?.Invoke(targetBeacon.Entity, targetAngle);
        }
        else
        {
            RequestFTL?.Invoke(_xformSystem.ToMapCoordinates(coordinates), targetAngle);
        }

        CancelTargeting();
    }

    private void ScanBssObjects()
    {
        if (_navigationSuppressed)
            return;

        if (_consoleEntity != null)
        {
            _audio.PlayEntity(
                new SoundPathSpecifier("/Audio/Effects/Shuttle/radar_ping.ogg"),
                Filter.Local(),
                _consoleEntity.Value,
                true);
        }

        _bssObjectsDirty = true;
        RebuildBssObjects();
        _nextBssScan = _timing.CurTime + BssScanCooldown;
        BssRebuildButton.Disabled = true;
    }

    private void RebuildBssObjects()
    {
        BssDestinations.DisposeAllChildren();
        _bssObjectsDirty = false;
        if (_navigationSuppressed || _shuttleEntity == null ||
            !_entManager.TryGetComponent(_shuttleEntity.Value, out TransformComponent? shuttleXform) ||
            shuttleXform.MapID == MapId.Nullspace)
        {
            return;
        }

        var mapId = shuttleXform.MapID;
        _bssObjectMap = mapId;
        var mapUid = _mapManager.GetMapEntityId(mapId);
        var mapName = _entManager.TryGetComponent(mapUid, out MetaDataComponent? metadata) &&
                      !string.IsNullOrWhiteSpace(metadata.EntityName)
            ? metadata.EntityName
            : Loc.GetString("shuttle-console-unknown");

        var heading = new CollapsibleHeading(mapName)
        {
            MinHeight = 32f,
            HorizontalAlignment = HAlignment.Stretch,
            HorizontalExpand = true,
        };
        heading.AddStyleClass(ContainerButton.StyleClassButton);
        heading.Label.HorizontalAlignment = HAlignment.Center;
        heading.Label.HorizontalExpand = true;

        var objectContainer = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };
        var entries = new List<IMapObject>();
        foreach (var grid in _mapManager.GetAllGrids(mapId))
        {
            _entManager.TryGetComponent(grid.Owner, out IFFComponent? iff);
            var hideLabel = iff != null &&
                            (iff.Flags & IFFFlags.HideLabel) != 0 &&
                            grid.Owner != _shuttleEntity;
            var detection = _consoleEntity == null
                ? DetectionLevel.Detected
                : _detection.IsGridDetected(grid.Owner, _consoleEntity.Value);
            if (detection == DetectionLevel.Undetected && hideLabel || iff != null && (iff.Flags & IFFFlags.Hide) != 0)
                continue;

            var name = hideLabel
                ? detection == DetectionLevel.PartialDetected
                    ? Loc.GetString("shuttle-console-signature-infrared")
                    : _detection.HandleUnknownMassLabel(grid.Owner)
                : _entManager.GetComponent<MetaDataComponent>(grid.Owner).EntityName;
            if (iff != null && (iff.Flags & IFFFlags.HideLabelAlways) != 0)
                continue;

            entries.Add(new GridMapObject
            {
                Name = name,
                Entity = grid.Owner,
            });
        }

        foreach (var (exclusion, _) in _shuttles.GetExclusions(mapId, _bssExclusions))
        {
            if (!exclusion.HideButton)
                entries.Add(exclusion);
        }

        foreach (var (beacon, _) in _shuttles.GetBeacons(mapId, _bssBeacons))
        {
            if (!beacon.HideButton)
                entries.Add(beacon);
        }

        entries.Sort((left, right) => string.Compare(left.Name, right.Name, StringComparison.CurrentCultureIgnoreCase));
        foreach (var entry in entries)
        {
            var button = new Button
            {
                Text = entry.Name,
                HorizontalExpand = true,
                StyleClasses = { "ButtonSquare" },
            };
            button.Label.ClipText = true;
            button.ToolTip = entry.Name;
            button.OnPressed += _ => NavRadar.CenterOn(_shuttles.GetMapCoordinates(entry));
            objectContainer.AddChild(button);
        }

        var body = new CollapsibleBody
        {
            HorizontalAlignment = HAlignment.Stretch,
            HorizontalExpand = true,
            Children = { objectContainer },
        };
        var collapsible = new Collapsible(heading, body)
        {
            BodyVisible = true,
        };
        BssDestinations.AddChild(collapsible);
    }

    // Frontier - IFF search
    private void OnIffSearchChanged(string text)
    {
        text = text.Trim();

        NavRadar.IFFFilter = text.Length == 0
            ? null // If empty, do not filter
            : (entity, grid, iff, hideLabel, name) => // Otherwise use simple search criteria
            {
                // Check entity name
                if (name.Contains(text, StringComparison.OrdinalIgnoreCase))
                {
                    return true;
                }
                if (hideLabel)
                    return false;

                // Check company name
                if (_entManager.TryGetComponent<CompanyComponent>(entity, out var companyComp) &&
                    !string.IsNullOrEmpty(companyComp.CompanyName))
                {
                    // Try to match the company ID directly
                    if (companyComp.CompanyName.Id.Contains(text, StringComparison.OrdinalIgnoreCase))
                    {
                        return true;
                    }

                    // Try to match company name from prototype
                    if (_prototypeManager.TryIndex(
                        companyComp.CompanyName, out var prototype) &&
                        prototype.Name.Contains(text, StringComparison.OrdinalIgnoreCase))
                    {
                        return true;
                    }
                }

                return false;
            };
    }

    public void SetShuttle(EntityUid? shuttle)
    {
        if (_shuttleEntity != shuttle)
            _bssObjectsDirty = true;

        _shuttleEntity = shuttle;
        NavRadar.SetShuttle(shuttle);

        NfAddShuttleDesignation(shuttle); // Frontier - PR #1284 Add Shuttle Designation
    }

    public void SetConsole(EntityUid? console)
    {
        _consoleEntity = console;
        NavRadar.SetConsole(console);
    }

    private void OnIFFTogglePressed(BaseButton.ButtonEventArgs args)
    {
        NavRadar.ShowIFF ^= true;
        args.Button.Pressed = NavRadar.ShowIFF;
    }

    private void OnIFFShuttleTogglePressed(BaseButton.ButtonEventArgs args)
    {
        NavRadar.ShowIFFShuttles ^= true;
        args.Button.Pressed = NavRadar.ShowIFFShuttles;
    }

    private void OnDockTogglePressed(BaseButton.ButtonEventArgs args)
    {
        NavRadar.ShowDocks ^= true;
        args.Button.Pressed = NavRadar.ShowDocks;
    }

    public void UpdateState(NavInterfaceState scc)
    {
        NavRadar.UpdateState(scc);

        // Update port names if custom names are available
        UpdateNetworkPortButtonNames(scc.NetworkPortNames);

        NfUpdateState(); // Frontier Update State
    }

    public void UpdateMapState(ShuttleMapInterfaceState state)
    {
        var objectsChanged = !_bssBeacons.SequenceEqual(state.Destinations) ||
                             !_bssExclusions.SequenceEqual(state.Exclusions);
        var previousState = _ftlState;
        _ftlState = state.FTLState;
        _ftlTime = state.FTLTime;
        _bssBeacons = state.Destinations;
        _bssExclusions = state.Exclusions;
        _bssObjectsDirty |= objectsChanged;
        if (previousState != _ftlState && _ftlState is FTLState.Available or FTLState.Cooldown)
            _bssObjectsDirty = true;
        NavRadar.SetBssObjects(_bssBeacons, _bssExclusions);
        BssFTLState.Text = Loc.GetString($"shuttle-console-ftl-state-{_ftlState}");

        switch (_ftlState)
        {
            case FTLState.Available:
                _ftlStyle.BackgroundColor = Color.FromHex("#80C71F");
                break;
            case FTLState.Starting:
                _ftlStyle.BackgroundColor = Color.FromHex("#169C9C");
                break;
            case FTLState.Travelling:
                _ftlStyle.BackgroundColor = Color.FromHex("#8932B8");
                break;
            case FTLState.Arriving:
                _ftlStyle.BackgroundColor = Color.FromHex("#F9801D");
                break;
            default:
                _ftlStyle.BackgroundColor = Color.FromHex("#B02E26");
                break;
        }

        BssFTLButton.Disabled = _navigationSuppressed || _ftlState != FTLState.Available;
        BssRebuildButton.Disabled = _navigationSuppressed || _ftlState is FTLState.Starting or FTLState.Travelling or FTLState.Arriving;
        NavAutopilotButton.Disabled = _navigationSuppressed;
        if (BssFTLButton.Disabled && NavRadar.TargetingMode == ShuttleNavTargetingMode.Bss)
            CancelTargeting();

        if (_bssMode && _bssObjectsDirty)
            RebuildBssObjects();
    }

    public void UpdatePlanetaryState(KoronusPlanetaryInterfaceState state)
    {
        _planetaryState = state;
        _navigationSuppressed = state.NavigationSuppressed;
        NavRadar.UpdatePlanetaryState(state);

        NavAutopilotButton.Disabled = _navigationSuppressed;
        BssFTLButton.Disabled = _navigationSuppressed || _ftlState != FTLState.Available;
        BssRebuildButton.Disabled = _navigationSuppressed || _ftlState is FTLState.Starting or FTLState.Travelling or FTLState.Arriving;
        if (_navigationSuppressed)
            CancelTargeting();

        if (!state.Available)
        {
            _selectedPlanetaryBody = null;
            _selectedLandingSite = null;
            PlanetaryDetailsPanel.Visible = false;
            NavRadar.Visible = true;
            PlanetaryNoSignal.Visible = false;
            return;
        }

        NavRadar.Visible = !state.NavigationSuppressed;
        PlanetaryNoSignal.Visible = state.NavigationSuppressed;

        if (_selectedPlanetaryBody != null && state.Bodies.All(body => body.Id != _selectedPlanetaryBody))
        {
            _selectedPlanetaryBody = null;
            _selectedLandingSite = null;
            PlanetaryDetailsPanel.Visible = false;
        }

        if (state.LandedBody != null)
        {
            _selectedPlanetaryBody = state.LandedBody;
            var landedBody = state.Bodies.FirstOrDefault(body => body.Id == state.LandedBody);
            _selectedLandingSite = landedBody?.LandingSites
                .FirstOrDefault(site => site.ReservedByCurrentShuttle)?.Id;
            PlanetaryDetailsPanel.Visible = true;
        }

        if (PlanetaryDetailsPanel.Visible)
            UpdatePlanetaryPanel();
    }

    private void OnPlanetSelected(KoronusCelestialBodyState body)
    {
        if (_selectedPlanetaryBody == body.Id && PlanetaryDetailsPanel.Visible)
        {
            ClosePlanetaryDetails();
            return;
        }

        if (_selectedPlanetaryBody != body.Id)
            _selectedLandingSite = null;

        _selectedPlanetaryBody = body.Id;
        _planetaryPanelPosition = null;
        PlanetaryDetailsPanel.Visible = true;
        UpdatePlanetaryPanel();
    }

    private void UpdatePlanetaryPanel()
    {
        PlanetaryLandingSites.RemoveAllChildren();
        var body = _planetaryState.Bodies.FirstOrDefault(candidate => candidate.Id == _selectedPlanetaryBody);
        if (body == null)
        {
            PlanetaryDetailsPanel.Visible = false;
            _selectedLandingSite = null;
            return;
        }

        PlanetaryBodyName.Text = Ellipsize(body.Name, PlanetaryTitleCharacterLimit);
        PlanetaryBodyName.ToolTip = body.Name;
        var climate = Loc.GetString(string.IsNullOrEmpty(body.Climate)
            ? "koronus-planetary-climate-unknown"
            : body.Climate);
        var size = Loc.GetString(body.NavVisualRadius switch
        {
            < 180f => "koronus-planetary-size-small",
            < 320f => "koronus-planetary-size-medium",
            _ => "koronus-planetary-size-large",
        });
        var climateText = Loc.GetString("koronus-planetary-popup-climate", ("climate", climate));
        PlanetaryBodyClimate.Text = Ellipsize(climateText, PlanetaryInfoCharacterLimit);
        PlanetaryBodyClimate.ToolTip = climateText;
        PlanetaryBodySize.Text = Loc.GetString("koronus-planetary-popup-size", ("size", size));

        var isLandedHere = _planetaryState.LandedBody == body.Id;
        var selectedSite = body.LandingSites.FirstOrDefault(site => site.Id == _selectedLandingSite);
        if (_selectedLandingSite != null && selectedSite == null)
            _selectedLandingSite = null;

        var siteGroup = new ButtonGroup();

        foreach (var site in body.LandingSites)
        {
            var portAvailable = site.Enabled && !site.Occupied;
            var status = site.ReservedByCurrentShuttle
                ? Loc.GetString("koronus-planetary-nav-site-current")
                : !site.Enabled
                    ? Loc.GetString("koronus-planetary-nav-site-closed")
                    : site.Occupied
                        ? Loc.GetString("koronus-planetary-nav-site-occupied")
                        : Loc.GetString("koronus-planetary-nav-site-available");
            var button = new Button
            {
                Text = Ellipsize(site.Name, PlanetaryLandingSiteCharacterLimit),
                ToolTip = Loc.GetString(
                    "koronus-planetary-details-port-entry",
                    ("name", site.Name),
                    ("width", site.Size.X.ToString("0")),
                    ("height", site.Size.Y.ToString("0")),
                    ("status", status)),
                TextAlign = Label.AlignMode.Left,
                HorizontalExpand = true,
                MinHeight = 28f,
                ToggleMode = true,
                Group = siteGroup,
                StyleClasses = { "ButtonSquare" },
                Disabled = !portAvailable,
            };
            var selected = site.Id == _selectedLandingSite && (portAvailable || site.ReservedByCurrentShuttle);
            button.Pressed = selected;
            button.Label.ClipText = true;
            button.Label.FontColorOverride = selected
                ? Color.FromHex("#A6EF7C")
                : site.ReservedByCurrentShuttle
                ? Color.FromHex("#80CFFF")
                : portAvailable
                    ? Color.FromHex("#E0E0E0")
                    : Color.FromHex("#6F7774");
            button.OnPressed += _ => SelectLandingSite(body.Id, site.Id);
            PlanetaryLandingSites.AddChild(button);
        }

        PlanetaryLandingSiteScroll.Visible = true;
        PlanetaryLandingButton.Visible = !isLandedHere;
        PlanetaryLaunchButton.Visible = isLandedHere;
        PlanetaryLaunchButton.Disabled = !_planetaryState.CanLaunch || _planetaryState.Transit != null;
        PlanetaryLaunchButton.Label.FontColorOverride = PlanetaryLaunchButton.Disabled
            ? Color.FromHex("#686868")
            : Color.FromHex("#9BEF73");

        selectedSite = body.LandingSites.FirstOrDefault(site => site.Id == _selectedLandingSite);
        var canLandAtSelectedSite = selectedSite != null && CanLandAtSite(body, selectedSite);
        PlanetaryLandingButton.Disabled = !canLandAtSelectedSite;
        PlanetaryLandingButton.Label.FontColorOverride = canLandAtSelectedSite
            ? Color.FromHex("#9BEF73")
            : Color.FromHex("#686868");
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        var progress = _ftlTime.ProgressAt(_timing.CurTime);
        BssFTLBar.Value = float.IsFinite(progress) ? progress : 1f;
        if (!_navigationSuppressed &&
            _timing.CurTime >= _nextBssScan &&
            _ftlState is not (FTLState.Starting or FTLState.Travelling or FTLState.Arriving))
        {
            BssRebuildButton.Disabled = false;
        }

        PositionPlanetaryPanel();
    }

    private void PositionPlanetaryPanel()
    {
        if (!PlanetaryDetailsPanel.Visible)
            return;

        // A landed shuttle deliberately hides NavRadar. Its arranged size then becomes zero, so
        // using it as the anchor leaves the manually positioned panel at the layout origin. The
        // surrounding navigation area remains arranged in both modes and is the stable anchor.
        var navigationSize = PlanetaryNavigationArea.Size;
        if (navigationSize.X <= 0f || navigationSize.Y <= 0f)
            return;

        var panelSize = PlanetaryDetailsPanel.Size;
        var panelWidth = panelSize.X > 0f ? panelSize.X : PlanetaryPopupWidth;
        var panelHeight = panelSize.Y > 0f ? panelSize.Y : PlanetaryPopupFallbackHeight;
        // PlanetaryDetailsPanel is a direct child of PlanetaryNavigationArea, therefore manual
        // positions are local to that container rather than to the outer shuttle window.
        var navigationOrigin = Vector2.Zero;
        var radarSize = NavRadar.Size;
        var radarOrigin = NavRadar.Position;
        Vector2 position;

        if (NavRadar.Visible &&
            _selectedPlanetaryBody != null &&
            NavRadar.TryGetPlanetVisual(_selectedPlanetaryBody, out var planetPosition, out var planetRadius))
        {
            var planetCentre = radarOrigin + planetPosition;
            var left = planetCentre.X - planetRadius - PlanetaryPopupGap - panelWidth;
            var right = planetCentre.X + planetRadius + PlanetaryPopupGap;
            var minimumX = radarOrigin.X + PlanetaryPopupEdgePadding;
            var maximumX = MathF.Max(minimumX, radarOrigin.X + radarSize.X - panelWidth - PlanetaryPopupEdgePadding);
            var fitsLeft = left >= minimumX;
            var fitsRight = right <= maximumX;
            var x = fitsLeft || !fitsRight ? left : right;
            var minimumY = radarOrigin.Y + PlanetaryPopupEdgePadding;
            var maximumY = MathF.Max(minimumY, radarOrigin.Y + radarSize.Y - panelHeight - PlanetaryPopupEdgePadding);
            position = new Vector2(
                Math.Clamp(x, minimumX, maximumX),
                Math.Clamp(planetCentre.Y - panelHeight * 0.5f, minimumY, maximumY));
        }
        else
        {
            position = navigationOrigin + new Vector2(
                MathF.Max((navigationSize.X - panelWidth) * 0.5f, PlanetaryPopupEdgePadding),
                MathF.Max((navigationSize.Y - panelHeight) * 0.5f, PlanetaryPopupEdgePadding));
        }

        position = new Vector2(
            MathF.Round(position.X * 2f) * 0.5f,
            MathF.Round(position.Y * 2f) * 0.5f);
        if (_planetaryPanelPosition != null &&
            Vector2.DistanceSquared(_planetaryPanelPosition.Value, position) < 0.01f)
        {
            return;
        }

        _planetaryPanelPosition = position;
        LayoutContainer.SetPosition(PlanetaryDetailsPanel, position);
    }

    private bool CanLandAtSite(KoronusCelestialBodyState body, KoronusLandingSiteState site)
    {
        return _planetaryState.CanLand &&
               body.InLandingApproachRange &&
               _planetaryState.Transit == null &&
               site.Enabled &&
               !site.Occupied;
    }

    private void SelectLandingSite(string bodyId, string siteId)
    {
        var body = _planetaryState.Bodies.FirstOrDefault(candidate => candidate.Id == bodyId);
        var site = body?.LandingSites.FirstOrDefault(candidate => candidate.Id == siteId);
        if (body == null || site == null || !site.Enabled || site.Occupied)
            return;

        _selectedLandingSite = siteId;
        UpdatePlanetaryPanel();
    }

    private void TryRequestPlanetaryLanding()
    {
        var body = _planetaryState.Bodies.FirstOrDefault(candidate => candidate.Id == _selectedPlanetaryBody);
        var site = body?.LandingSites.FirstOrDefault(candidate => candidate.Id == _selectedLandingSite);
        if (body == null || site == null || !CanLandAtSite(body, site))
            return;

        PlanetaryLandingRequest?.Invoke(body.Id, site.Id);
    }

    private void ClosePlanetaryDetails()
    {
        if (_planetaryState.LandedBody != null || _planetaryState.Transit != null)
            return;

        _selectedPlanetaryBody = null;
        _selectedLandingSite = null;
        _planetaryPanelPosition = null;
        PlanetaryDetailsPanel.Visible = false;
    }

    private static string Ellipsize(string text, int maximumCharacters)
    {
        if (text.Length <= maximumCharacters)
            return text;

        return text[..(maximumCharacters - 3)].TrimEnd() + "...";
    }

    /// <summary>
    /// Updates the text on the network port buttons based on the custom port names.
    /// </summary>
    /// <param name="portNames">Dictionary of port IDs to display names</param>
    private void UpdateNetworkPortButtonNames(Dictionary<string, string> portNames)
    {
        // Map of button names to their corresponding port IDs in the component
        var buttonToPortIdMap = new Dictionary<Button, string>
        {
            { DeviceButton1, "device-button-1" },
            { DeviceButton2, "device-button-2" },
            { DeviceButton3, "device-button-3" },
            { DeviceButton4, "device-button-4" },
            { DeviceButton5, "device-button-5" },
            { DeviceButton6, "device-button-6" },
            { DeviceButton7, "device-button-7" },
            { DeviceButton8, "device-button-8" }
        };

        // For each button, check if there's a custom name and update accordingly
        foreach (var (button, portId) in buttonToPortIdMap)
        {
            if (portNames.TryGetValue(portId, out var customName))
            {
                // Use the custom name if available
                button.Text = customName;
            }
            else
            {
                // Otherwise use the default localized name
                var locKey = $"shuttle-console-{portId}";
                button.Text = Loc.GetString(locKey);
            }
        }
    }

    public void SetMatrix(EntityCoordinates? coordinates, Angle? angle)
    {
        _shuttleEntity = coordinates?.EntityId;
        NavRadar.SetMatrix(coordinates, angle);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (!_entManager.TryGetComponent(_shuttleEntity, out TransformComponent? gridXform) ||
            !_entManager.TryGetComponent(_shuttleEntity, out PhysicsComponent? gridBody))
        {
            return;
        }

        var (_, worldRot, worldMatrix) = _xformSystem.GetWorldPositionRotationMatrix(gridXform);
        var worldPos = Vector2.Transform(gridBody.LocalCenter, worldMatrix);

        // Mono - remap to [0, 360)
        var displayRot = (-worldRot).Reduced();
        var displayRotDegrees = displayRot.FlipPositive().Degrees;

        GridPosition.Text = Loc.GetString("shuttle-console-position-value",
            ("X", $"{worldPos.X:0.0}"),
            ("Y", $"{worldPos.Y:0.0}"));
        GridOrientation.Text = Loc.GetString("shuttle-console-orientation-value",
            ("angle", $"{displayRotDegrees:0.0}"));

        var gridVelocity = gridBody.LinearVelocity;
        gridVelocity = displayRot.RotateVec(gridVelocity);
        // Get linear velocity relative to the console entity
        GridLinearVelocity.Text = Loc.GetString("shuttle-console-linear-velocity-value",
            ("X", $"{gridVelocity.X + 10f * float.Epsilon:0.0}"),
            ("Y", $"{gridVelocity.Y + 10f * float.Epsilon:0.0}"));
        GridAngularVelocity.Text = Loc.GetString("shuttle-console-angular-velocity-value",
            ("angularVelocity", $"{-MathHelper.RadiansToDegrees(gridBody.AngularVelocity) + 10f * float.Epsilon:0.0}"));
    }
}
