using System.Linq;
using System.Numerics;
using Content.Client._Mono.Radar;
using Content.Client._WH40K.SectorMap;
using Content.Client.Shuttles.Systems;
using Content.Client.Station; // Frontier
using Content.Shared._Crescent.ShipShields;
using Content.Shared._Mono.Company;
using Content.Shared._Mono.Detection;
using Content.Shared._Mono.Radar;
using Content.Shared._WH40K.SectorMap.Components;
using Content.Shared._WH40K.SectorMap.BUI;
using Content.Shared._WH40K.SectorMap.Prototypes;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Components;
using Content.Shared.Shuttles.Systems;
using Content.Shared.Shuttles.UI.MapObjects;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Map;
using Robust.Shared.Map.Components;
using Robust.Shared.Physics;
using Robust.Shared.Physics.Collision.Shapes;
using Robust.Shared.Physics.Components;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.Shuttles.UI;

public enum ShuttleNavTargetingMode : byte
{
    None,
    Autopilot,
    Bss,
}

[GenerateTypedNameReferences]
[Virtual]
public partial class ShuttleNavControl : BaseShuttleControl // Mono
{
    private const int KoronusBoundaryBandSegments = 128;

    [Dependency] private IMapManager _mapManager = default!;
    [Dependency] private IUserInterfaceManager _uiManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    private readonly DetectionSystem _detection; // Mono
    private readonly StationSystem _station; // Frontier
    private readonly SharedShuttleSystem _shuttles;
    private readonly ShuttleSystem _clientShuttles;
    private readonly SharedTransformSystem _transform;
    private readonly RadarBlipsSystem _blips;
    private readonly IGameTiming _timing;
    private readonly KoronusPlanetVisualRenderer _planetRenderer;
    private readonly KoronusSunVisualRenderer _sunRenderer;

    /// <summary>
    /// Used to transform all of the radar objects. Typically is a shuttle console parented to a grid.
    /// </summary>
    protected EntityCoordinates? _coordinates; // Mono

    /// <summary>
    /// Entity of controlling console
    /// </summary>
    protected EntityUid? _consoleEntity; // Mono
    private EntityUid? _shuttleEntity;

    // Mono - is world rotation of the view.
    protected Angle? _rotation = Angle.Zero;

    private Dictionary<NetEntity, List<DockingPortState>> _docks = new();
    private KoronusPlanetaryInterfaceState _planetaryState = KoronusPlanetaryInterfaceState.Unavailable();
    private readonly List<PlanetHitTarget> _planetHitTargets = new();
    private bool _planetClickPressed;
    private bool _rightMousePanning;
    private List<ShuttleBeaconObject> _bssBeacons = new();
    private List<ShuttleExclusionObject> _bssExclusions = new();

    // temporary buffers to avoid per-frame heap churn
    private readonly List<BlipData> _tempBlipDataList = new();
    private readonly HashSet<EntityUid> _visibleGridsSet = new();
    private readonly Vector2[] _koronusBoundaryBandVertices = new Vector2[(KoronusBoundaryBandSegments + 1) * 2];
    private readonly Vector2[] _radarPositionVertices = new Vector2[RadarPosVertsCache.Length];
    private static readonly Color KoronusOrbitShadowColor = Color.FromHex("#14211E").WithAlpha(0.92f);
    private static readonly Color KoronusOrbitColor = Color.FromHex("#83B7A5").WithAlpha(0.82f);
    private static readonly Vector2[] KoronusBoundaryBandDirections = CreateKoronusBoundaryBandDirections();
    private static readonly Vector2[] RadarPosVertsCache =
    [
        new Vector2(0f, -2f),
        new Vector2(1f, 0f),
        new Vector2(0f, 2f),
        new Vector2(-1f, 0f),
    ];

    public bool ShowIFF { get; set; } = true;
    public bool ShowIFFShuttles { get; set; } = true;
    public bool ShowDocks { get; set; } = true;
    public bool ForcePannable { get; set; }
    public ShuttleNavTargetingMode TargetingMode { get; private set; }
    public Angle TargetAngle { get; private set; }

    public float MaximumIFFDistance { get; set; } = 3000f; // Frontier // Mono - 3000 by default to not gigaclutter
    public bool HideCoords { get; set; } = false; // Frontier

    private static Color _dockLabelColor = Color.White; // Frontier

    /// <summary>
    ///   If present, called for every IFF. Must determine if it should or should not be shown.
    /// </summary>
    public Func<EntityUid, MapGridComponent, IFFComponent?, bool, string, bool>? IFFFilter { get; set; } = null;

    /// <summary>
    /// Raised if the user left-clicks on the radar control with the relevant entitycoordinates.
    /// </summary>
    public Action<EntityCoordinates>? OnRadarClick;

    /// <summary>
    /// Raised when the user selects a planetary body drawn over the ordinary NAV radar.
    /// </summary>
    public event Action<KoronusCelestialBodyState>? PlanetSelected;
    public event Action? PlanetSelectionCleared;

    private List<Entity<MapGridComponent>> _grids = new();

    // Mono - set if we want this to detect not from itself
    public List<EntityUid>? Detectors = null;

    #region Mono
    // These 2 handle timing updates
    protected const float RadarUpdateInterval = 0f;
    protected float _updateAccumulator = 0f;

    // doesn't support absolute panning and angle follow, but why would you need that?
    protected bool _relativePanning = false;
    protected bool _angleFollow = true;
    private bool _radarModeDefaultsApplied;

    private bool _wasPanned = false;
    #endregion

    protected bool _isMouseDown;
    protected bool _isMouseInside;
    protected Vector2 _lastMousePos;
    protected float _lastFireTime;
    protected const float FireRateLimit = 0.1f; // 100ms between shots

    private enum RadarAzimuthMode : byte
    {
        Edge,
        Ring,
        Off,
    }

    private BoxContainer? _radarModeButtons;
    private RadarModeButton? _radarAzimuthButton;
    private RadarModeButton? _radarRotationButton;
    private RadarModeButton? _radarAnchorButton;
    private RadarModeButton? _radarResetButton;
    private RadarAzimuthMode _azimuthMode;

    public ShuttleNavControl() : this(64f, 256f, 256f) { } // Mono

    public ShuttleNavControl(float minRange, float maxRange, float range) : base(minRange, maxRange, range) // Mono
    {
        RobustXamlLoader.Load(this);
        // MapGridControl defaults to a fixed 648 x 648 square. NAV must follow the available
        // rectangular viewport in every console that embeds it.
        SetSize = new Vector2(float.NaN, float.NaN);
        MinSize = new Vector2(240f, 180f);
        HorizontalExpand = true;
        VerticalExpand = true;
        HorizontalAlignment = HAlignment.Stretch;
        VerticalAlignment = VAlignment.Stretch;
        _detection = EntManager.System<DetectionSystem>(); // Mono
        _shuttles = EntManager.System<SharedShuttleSystem>();
        _clientShuttles = EntManager.System<ShuttleSystem>();
        _transform = EntManager.System<SharedTransformSystem>();
        _station = EntManager.System<StationSystem>(); // Frontier
        _blips = EntManager.System<RadarBlipsSystem>();
        _timing = IoCManager.Resolve<IGameTiming>();
        _planetRenderer = new KoronusPlanetVisualRenderer(
            _prototypeManager,
            IoCManager.Resolve<IResourceCache>());
        _sunRenderer = new KoronusSunVisualRenderer(
            _prototypeManager,
            IoCManager.Resolve<IResourceCache>());

        OnMouseEntered += HandleMouseEntered;
        OnMouseExited += HandleMouseExited;
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        // LayoutContainer does not use BoxContainer's expand flags. Anchor NAV explicitly so
        // radar, gunnery and drone consoles all resize it with their viewport.
        if (Parent is LayoutContainer)
            LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);
    }

    private void HandleMouseEntered(GUIMouseHoverEventArgs args)
    {
        _isMouseInside = true;
    }

    private void HandleMouseExited(GUIMouseHoverEventArgs args)
    {
        _isMouseInside = false;
    }

    public void SetMatrix(EntityCoordinates? coordinates, Angle? angle)
    {
        if (_wasPanned) // Mono hack
            return;

        _coordinates = coordinates;
        // Mono - TODO: either remove this or make this do anything
        // _rotation = angle;
    }

    public void SetConsole(EntityUid? consoleEntity)
    {
        if (_consoleEntity == consoleEntity)
            return;

        _consoleEntity = consoleEntity;
        _radarModeDefaultsApplied = false;
        ApplyRadarModeDefaults();
    }

    public void SetShuttle(EntityUid? shuttleEntity)
    {
        _shuttleEntity = shuttleEntity;
    }

    public void SetBssObjects(List<ShuttleBeaconObject> beacons, List<ShuttleExclusionObject> exclusions)
    {
        _bssBeacons = beacons;
        _bssExclusions = exclusions;
    }

    public void SetTargetingMode(ShuttleNavTargetingMode mode)
    {
        if (TargetingMode == mode)
            return;

        TargetingMode = mode;
        _isMouseDown = false;
        if (mode != ShuttleNavTargetingMode.None)
        {
            var angleEntity = _shuttleEntity ?? _coordinates?.EntityId;
            if (angleEntity != null)
                TargetAngle = _transform.GetWorldRotation(angleEntity.Value).Reduced();
        }
    }

    public void CenterOn(MapCoordinates coordinates)
    {
        if (coordinates.MapId == MapId.Nullspace)
            return;

        PanToWorld();
        _coordinates = _transform.ToCoordinates(coordinates);
        Offset = Vector2.Zero;
        _relativePanning = false;
        _angleFollow = false;
        _wasPanned = true;
    }

    // converts Offset to world-relative offset so we can modify radar parameters without conversion headaches
    // call this before potentially rotation-modifying operations and PanToEnt() after
    private void PanToWorld()
    {
        if (!_angleFollow || _coordinates is not { } cord)
            return;
        var coordEntRot = _transform.GetWorldRotation(cord.EntityId);
        Offset = coordEntRot.RotateVec(Offset);
    }

    // converts world-relative Offset to relative to current view
    // call this after potentially rotation-modifying operations and PanToWorld() before
    private void PanToEnt()
    {
        if (!_angleFollow || _coordinates is not { } cord)
            return;
        var coordEntRot = _transform.GetWorldRotation(cord.EntityId);
        Offset = (-coordEntRot).RotateVec(Offset);
    }

    // reanchor our view to console or grid
    private void ReanchorView()
    {
        if (_consoleEntity is not { } cons
        || _coordinates is not { } cord
        || !EntManager.TryGetComponent<TransformComponent>(cons, out var xform))
            return;

        PanToWorld();
        var anchTo = cons;
        if (xform.GridUid != null)
            anchTo = xform.GridUid.Value;
        _coordinates = _transform.WithEntityId(cord, anchTo);
        _relativePanning = true;
        PanToEnt();
    }

    private void EnsureRadarModeButtons()
    {
        if (_radarModeButtons != null)
            return;

        if (Parent is not LayoutContainer parent)
            return;

        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);

        _radarModeButtons = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 2,
            HorizontalExpand = false,
            VerticalExpand = false,
            MouseFilter = MouseFilterMode.Stop,
        };

        _radarAzimuthButton = CreateRadarModeButton(RadarModeButtonIcon.Azimuth);
        _radarAzimuthButton.ToolTip = Loc.GetString("shuttle-console-button-azimuth");
        _radarAzimuthButton.OnPressed += _ =>
        {
            _azimuthMode = _azimuthMode switch
            {
                RadarAzimuthMode.Edge => RadarAzimuthMode.Ring,
                RadarAzimuthMode.Ring => RadarAzimuthMode.Off,
                _ => RadarAzimuthMode.Edge,
            };
        };

        _radarRotationButton = CreateRadarModeButton(RadarModeButtonIcon.Rotation);
        _radarRotationButton.ToolTip = Loc.GetString("shuttle-console-button-rotation");
        _radarRotationButton.OnPressed += _ =>
        {
            PanToWorld();
            _angleFollow ^= true;
            PanToEnt();
        };

        _radarAnchorButton = CreateRadarModeButton(RadarModeButtonIcon.Anchor);
        _radarAnchorButton.ToolTip = Loc.GetString("shuttle-console-button-anchor");
        _radarAnchorButton.OnPressed += _ =>
        {
            if (_coordinates is not { } cord)
                return;

            // if we're anchored or not yet bound to map, just deanchor
            if (_relativePanning || !EntManager.HasComponent<MapComponent>(cord.EntityId))
            {
                PanToWorld();
                // we're deanchoring, so simply detach our view to the map
                _coordinates = _transform.ToCoordinates(_transform.ToMapCoordinates(cord));
                _relativePanning = false;
                _wasPanned = true;
                PanToEnt();
            }
            else
            {
                ReanchorView();
            }
        };

        _radarResetButton = CreateRadarModeButton(RadarModeButtonIcon.Reset);
        _radarResetButton.ToolTip = Loc.GetString("shuttle-console-button-reset");
        _radarResetButton.OnPressed += _ =>
        {
            _radarModeDefaultsApplied = false;
            ApplyRadarModeDefaults();
            if (EntManager.TryGetComponent<TransformComponent>(_consoleEntity, out var xform))
            {
                Offset = Vector2.Zero;
                _coordinates = xform.Coordinates;
                ReanchorView();
            }
        };

        _radarModeButtons.AddChild(_radarAzimuthButton);
        _radarModeButtons.AddChild(_radarRotationButton);
        _radarModeButtons.AddChild(_radarAnchorButton);
        _radarModeButtons.AddChild(_radarResetButton);

        parent.AddChild(_radarModeButtons);
        LayoutContainer.SetAnchorAndMarginPreset(_radarModeButtons, LayoutContainer.LayoutPreset.BottomLeft, margin: 10);
    }

    private void ApplyRadarModeDefaults()
    {
        if (_radarModeDefaultsApplied)
            return;

        if (!EntManager.TryGetComponent<RadarConsoleComponent>(_consoleEntity, out var radar))
            return;

        _radarModeDefaultsApplied = true;
        Draggable = ForcePannable || radar.Pannable;
        _angleFollow = !radar.NoRotate;
        _relativePanning = radar.RelativePanning;
    }

    private static RadarModeButton CreateRadarModeButton(RadarModeButtonIcon icon = RadarModeButtonIcon.None)
    {
        return new RadarModeButton(icon)
        {
            MinWidth = 16f,
            MaxWidth = 16f,
            MinHeight = 16f,
            MaxHeight = 16f,
            HorizontalExpand = false,
            VerticalExpand = false,
            ModulateSelfOverride = Color.White.WithAlpha(0.55f),
        };
    }

    internal enum RadarModeButtonIcon : byte
    {
        None,
        Azimuth,
        Rotation,
        Anchor,
        Reset
    }

    public sealed class RadarModeButton : BaseButton
    {
        private readonly RadarModeButtonIcon _icon;

        internal RadarModeButton(RadarModeButtonIcon icon)
        {
            _icon = icon;
        }

        protected override Vector2 MeasureOverride(Vector2 availableSize)
        {
            return new Vector2(16f, 16f);
        }

        protected override void Draw(DrawingHandleScreen handle)
        {
            var alpha = DrawMode switch
            {
                DrawModeEnum.Pressed => 0.62f,
                DrawModeEnum.Hover => 0.48f,
                _ => 0.32f,
            };

            var center = new Vector2(PixelSize.X * 0.5f, PixelSize.Y * 0.5f);
            var radius = MathF.Min(PixelSize.X, PixelSize.Y) * 0.42f;
            handle.DrawCircle(center, radius, Color.White.WithAlpha(alpha));

            var up = new Vector2(0f, -radius);
            var down = new Vector2(0f, radius);
            var leftOffs = new Vector2(-radius, 0f);
            var rightOffs = new Vector2(radius, 0f);
            var top = center + up;
            var bottom = center + down;
            var left = center + leftOffs;
            var right = center + rightOffs;

            switch (_icon) {
                case RadarModeButtonIcon.Azimuth:
                {
                    var iconColor = Color.Black.WithAlpha(0.95f);
                    var topLeft = center + (up + leftOffs) / MathF.Sqrt(2f);
                    var topRight = center + (up + rightOffs) / MathF.Sqrt(2f);
                    var bottomLeft = center + (down + leftOffs) / MathF.Sqrt(2f);
                    var bottomRight = center + (down + rightOffs) / MathF.Sqrt(2f);

                    handle.DrawLine(topLeft, bottomRight, iconColor);
                    handle.DrawLine(bottomLeft, topRight, iconColor);
                    handle.DrawLine(left, right, iconColor);
                    handle.DrawLine(bottom, top, iconColor);
                    break;
                }
                case RadarModeButtonIcon.Rotation:
                {
                    var iconColor = Color.Yellow.WithAlpha(0.95f);
                    var innerRatio = 0.8f;
                    var segCount = 3;
                    var prevOffs = up * innerRatio;
                    for (var i = 0; i < segCount; i++)
                    {
                        var angle = Angle.FromDegrees(120f * i / (float)segCount - 15f);
                        var thisOffs = angle.RotateVec(up * innerRatio);
                        var thisPointUp = center + thisOffs;
                        var thisPointDown = center - thisOffs;
                        var oldPointUp = center + prevOffs;
                        var oldPointDown = center - prevOffs;
                        handle.DrawLine(oldPointUp, thisPointUp, iconColor);
                        handle.DrawLine(oldPointDown, thisPointDown, iconColor);
                        prevOffs = thisOffs;
                    }
                    break;
                }
                case RadarModeButtonIcon.Anchor:
                {
                    var iconColor = Color.Blue.WithAlpha(0.95f);
                    var stemTop = center + up * 0.5f;
                    var crossLeft = center + leftOffs * 0.3f + up * 0.7f;
                    var crossRight = center + rightOffs * 0.3f + up * 0.7f;;
                    var leftFluke = center + leftOffs * 0.6f + down * 0.6f;
                    var rightFluke = center + rightOffs * 0.6f + down * 0.6f;
                    var innerRadius = radius * 0.4f;
                    var innerTop = center + up * 0.6f;

                    handle.DrawCircle(innerTop, innerRadius, iconColor, false);
                    handle.DrawLine(stemTop, bottom, iconColor);
                    handle.DrawLine(crossLeft, crossRight, iconColor);
                    handle.DrawLine(bottom, leftFluke, iconColor);
                    handle.DrawLine(bottom, rightFluke, iconColor);
                    break;
                }
                case RadarModeButtonIcon.Reset:
                {
                    var iconColor = Color.Red.WithAlpha(0.95f);
                    handle.DrawLine(left, right, iconColor);
                    break;
                }
                default:
                    break;
            }
        }
    }

    // Mono - evil hack
    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        // Both right-mouse bindings can be raised for MouseRight, depending on active input
        // contexts. Keep the drag latched until the matching key-up instead of relying on the
        // base control seeing the lower-priority UseSecondary event.
        if (_rightMousePanning)
            _draggin = true;

        base.MouseMove(args);
        if (_isMouseInside)
            _lastMousePos = args.RelativePosition;

        if (!_draggin || _coordinates == null)
            return;

        if (!_relativePanning
            && _coordinates?.EntityId is { } coordEnt
            && EntManager.TryGetComponent<TransformComponent>(coordEnt, out var coordXform)
            && coordXform.MapUid != coordEnt
        )
            _coordinates = _transform.ToCoordinates(_transform.ToMapCoordinates(_coordinates.Value));


        _wasPanned = true;
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        if (IsRightMouseFunction(args.Function))
        {
            PlanetSelectionCleared?.Invoke();
            // UIRightClick has a higher input priority than UseSecondary in keybinds.yml, while
            // some input contexts still deliver only UseSecondary. Handle both here directly.
            StartDragPosition = args.PointerLocation.Position;
            Recentering = false;
            _rightMousePanning = true;
            _draggin = true;

            args.Handle();
            return;
        }

        if (args.Function == EngineKeyFunctions.UIClick && TargetingMode != ShuttleNavTargetingMode.None)
        {
            PlanetSelectionCleared?.Invoke();
            args.Handle();
            return;
        }

        if (args.Function == EngineKeyFunctions.UIClick && TrySelectPlanet(args.RelativePosition * UIScale))
        {
            _planetClickPressed = true;
            args.Handle();
            return;
        }

        if (args.Function == EngineKeyFunctions.UIClick)
            PlanetSelectionCleared?.Invoke();

        base.KeyBindDown(args);

        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        _isMouseDown = true;
        _lastMousePos = args.RelativePosition;
        TryFireAtPosition(args.RelativePosition);
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        if (IsRightMouseFunction(args.Function))
        {
            _rightMousePanning = false;
            _draggin = false;
            args.Handle();
            return;
        }

        if (args.Function == EngineKeyFunctions.UIClick && _planetClickPressed)
        {
            _planetClickPressed = false;
            args.Handle();
            return;
        }

        if (args.Function == EngineKeyFunctions.UIClick && TargetingMode != ShuttleNavTargetingMode.None)
        {
            _isMouseDown = false;
            OnRadarClick?.Invoke(GetMouseEntityCoordinates(args.RelativePosition));
            args.Handle();
            return;
        }

        base.KeyBindUp(args);

        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        _isMouseDown = false;

        var coords = GetMouseEntityCoordinates(args.RelativePosition);
        OnRadarClick?.Invoke(coords);
    }

    private static bool IsRightMouseFunction(BoundKeyFunction function)
    {
        return function == EngineKeyFunctions.UIRightClick ||
               function == EngineKeyFunctions.UseSecondary;
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        if (TargetingMode != ShuttleNavTargetingMode.None)
        {
            TargetAngle -= Angle.FromDegrees(15f) * args.Delta.Y;
            TargetAngle = TargetAngle.Reduced();
            return;
        }

        base.MouseWheel(args);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _updateAccumulator += args.DeltaSeconds;

        if (_updateAccumulator >= RadarUpdateInterval)
        {
            _updateAccumulator = 0; // I'm not subtracting because frame updates can majorly lag in a way normal ones cannot.

            if (_consoleEntity != null)
                _blips.RequestBlips((EntityUid)_consoleEntity);
        }

        if (_isMouseDown && _isMouseInside)
        {
            var currentTime = IoCManager.Resolve<IGameTiming>().CurTime.TotalSeconds;
            if (currentTime - _lastFireTime >= FireRateLimit)
            {
                var mousePos = UserInterfaceManager.MousePositionScaled;
                var relativePos = mousePos.Position - GlobalPosition;
                if (relativePos != _lastMousePos)
                {
                    _lastMousePos = relativePos;
                }
                TryFireAtPosition(relativePos);
                _lastFireTime = (float)currentTime;
            }
        }
    }

    private void TryFireAtPosition(Vector2 relativePosition)
    {
        var coords = GetMouseEntityCoordinates(relativePosition);
        OnRadarClick?.Invoke(coords);
    }

    /// <summary>
    /// Gets the entity coordinates of where the mouse position is, relative to the control.
    /// </summary>
    [PublicAPI]
    public EntityCoordinates GetMouseCoordinatesFromCenter()
    {
        if (_coordinates == null || _rotation == null)
        {
            return EntityCoordinates.Invalid;
        }

        var pos = _uiManager.MousePositionScaled.Position - GlobalPosition;
        return GetMouseEntityCoordinates(pos);
    }

    public void UpdateState(NavInterfaceState state)
    {
        EnsureRadarModeButtons();
        ApplyRadarModeDefaults();
        SetMatrix(EntManager.GetCoordinates(state.Coordinates), state.Angle);

        WorldMaxRange = state.MaxRange;

        if (WorldMaxRange < WorldRange)
        {
            ActualRadarRange = WorldMaxRange;
        }

        if (WorldMaxRange < WorldMinRange)
            WorldMinRange = WorldMaxRange;

        ActualRadarRange = Math.Clamp(ActualRadarRange, WorldMinRange, WorldMaxRange);

        // Frontier
        if (state.MaxIffRange != null)
            MaximumIFFDistance = state.MaxIffRange.Value;
        HideCoords = state.HideCoords;
        // End Frontier

        _docks = state.Docks;

        NfUpdateState(state); // Frontier Update State
    }

    public void UpdatePlanetaryState(KoronusPlanetaryInterfaceState state)
    {
        _planetaryState = state;
        if (!state.Available)
            _planetHitTargets.Clear();
    }

    /// <summary>
    /// Returns the current UI-space centre and visible radius of a planet drawn by the NAV radar.
    /// The containing screen uses this to keep its compact information card attached to the body
    /// while the radar is panned, zoomed or the body advances along its orbit.
    /// </summary>
    public bool TryGetPlanetVisual(string bodyId, out Vector2 position, out float radius)
    {
        foreach (var target in _planetHitTargets)
        {
            if (target.Body.Id != bodyId)
                continue;

            position = target.Position / UIScale;
            radius = target.VisualRadius / UIScale;
            return true;
        }

        position = default;
        radius = 0f;
        return false;
    }

    public bool TryGetTargetGrid(EntityCoordinates coordinates, out EntityUid targetGrid)
    {
        targetGrid = default;
        var mapCoordinates = _transform.ToMapCoordinates(coordinates);
        if (mapCoordinates.MapId == MapId.Nullspace)
            return false;

        var bodyQuery = EntManager.GetEntityQuery<PhysicsComponent>();
        var captureRange = MathF.Max(1f, 18f * UIScale / MinimapScale);
        var closestDistance = captureRange * captureRange;

        foreach (var grid in _visibleGridsSet)
        {
            if (!bodyQuery.TryGetComponent(grid, out var body))
                continue;

            var gridCoordinates = _transform.ToMapCoordinates(new EntityCoordinates(grid, body.LocalCenter));
            if (gridCoordinates.MapId != mapCoordinates.MapId)
                continue;

            var distance = Vector2.DistanceSquared(gridCoordinates.Position, mapCoordinates.Position);
            if (distance > closestDistance)
                continue;

            closestDistance = distance;
            targetGrid = grid;
        }

        return targetGrid.IsValid();
    }

    public bool TryGetTargetBeacon(EntityCoordinates coordinates, out ShuttleBeaconObject targetBeacon)
    {
        targetBeacon = default;
        var mapCoordinates = _transform.ToMapCoordinates(coordinates);
        if (mapCoordinates.MapId == MapId.Nullspace)
            return false;

        var captureRange = MathF.Max(1f, 22f * UIScale / MinimapScale);
        var closestDistance = captureRange * captureRange;
        var found = false;
        foreach (var beacon in _bssBeacons)
        {
            var beaconCoordinates = _clientShuttles.GetMapCoordinates(beacon);
            if (beaconCoordinates.MapId != mapCoordinates.MapId)
                continue;

            var distance = Vector2.DistanceSquared(beaconCoordinates.Position, mapCoordinates.Position);
            if (distance > closestDistance)
                continue;

            closestDistance = distance;
            targetBeacon = beacon;
            found = true;
        }

        return found;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        DrawBacking(handle);
        DrawCircles(handle);

        // No data
        if (_coordinates == null || _rotation == null)
        {
            return;
        }

        var xformQuery = EntManager.GetEntityQuery<TransformComponent>();
        var fixturesQuery = EntManager.GetEntityQuery<FixturesComponent>();
        var bodyQuery = EntManager.GetEntityQuery<PhysicsComponent>();

        if (!xformQuery.TryGetComponent(_coordinates.Value.EntityId, out var xform)
            || xform.MapID == MapId.Nullspace)
        {
            return;
        }

        // Mono
        Draggable = ForcePannable;
        if (EntManager.TryGetComponent<RadarConsoleComponent>(_consoleEntity, out var radar))
            Draggable |= radar.Pannable;
        // Mono - TODO: remove _rotation and make it a method instead
        var coordEnt = _coordinates.Value.EntityId;
        var coordEntRot = _transform.GetWorldRotation(coordEnt);
        if (_angleFollow && EntManager.TryGetComponent<TransformComponent>(coordEnt, out var coordXform))
            _rotation = coordEntRot;
        else
            _rotation = Angle.Zero;

        var worldRot = _rotation.Value;
        var observerPosition = _transform.ToMapCoordinates(_coordinates.Value).Position;
        var mapPos = _transform.ToMapCoordinates(_coordinates.Value).Offset(_rotation.Value.RotateVec(Offset));
        var mapCoord = _transform.ToCoordinates(mapPos);
        var worldToShuttle = Matrix3Helpers.CreateTranslation(-mapCoord.Position) * Matrix3Helpers.CreateRotation(-worldRot);
        Matrix3x2.Invert(worldToShuttle, out var shuttleToWorld);
        var shuttleToView = Matrix3x2.CreateScale(new Vector2(MinimapScale, -MinimapScale)) * Matrix3x2.CreateTranslation(MidPointVector);
        var worldToView = worldToShuttle * shuttleToView;

        // Draw shields
        DrawShields(handle, xform, worldToShuttle);

        // Frontier Corvax: north line drawing
        DrawNorthLine(handle, worldRot);

        // Mono
        switch (_azimuthMode)
        {
            case RadarAzimuthMode.Edge:
                DrawAzimuthScale(handle, worldRot);
                break;
            case RadarAzimuthMode.Ring:
                DrawAzimuthRing(handle, worldRot);
                break;
        }

        if (worldRot != Angle.Zero)
        {
            DrawCompassOverlay(handle, coordEntRot);
        }

        // This is deliberately part of the ordinary radar pass: planet positions use the same
        // world-to-view matrix as grids, IFF contacts and docking ports.
        DrawCelestialNavigation(handle, worldToView);

        // Draw our grid in detail
        var ourGridId = xform.GridUid ?? _shuttleEntity;
        if (EntManager.TryGetComponent<MapGridComponent>(ourGridId, out var ourGrid) &&
            fixturesQuery.HasComponent(ourGridId.Value))
        {
            var ourGridToWorld = _transform.GetWorldMatrix(ourGridId.Value);
            var ourGridToShuttle = Matrix3x2.Multiply(ourGridToWorld, worldToShuttle);
            var ourGridToView = ourGridToShuttle * shuttleToView;
            var color = _shuttles.GetIFFColor(ourGridId.Value, self: true);

            DrawGrid(handle, ourGridToView, (ourGridId.Value, ourGrid), color);
            DrawDocks(handle, ourGridId.Value, ourGridToView);
        }

        // Draw radar position on the station without a per-frame vertex allocation.
        for (var i = 0; i < _radarPositionVertices.Length; i++)
        {
            _radarPositionVertices[i] = ScalePosition(RadarPosVertsCache[i]);
        }

        handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, _radarPositionVertices, Color.Lime);

        var viewBounds = new Box2Rotated(new Box2(-WorldRange, -WorldRange, WorldRange, WorldRange).Translated(mapPos.Position), worldRot, mapPos.Position);
        var viewAABB = viewBounds.CalcBoundingBox();

        _grids.Clear();
        _mapManager.FindGridsIntersecting(xform.MapID, new Box2(mapPos.Position - MaxRadarRangeVector, mapPos.Position + MaxRadarRangeVector), ref _grids, approx: true, includeMap: false);

        // Mono edited: Frontier - collect blip location data outside foreach - more changes ahead
        _tempBlipDataList.Clear();

        _visibleGridsSet.Clear();

        // Draw other grids... differently
        foreach (var grid in _grids)
        {
            var gUid = grid.Owner;
            if (gUid == ourGridId || !fixturesQuery.HasComponent(gUid))
                continue;

            var gridBody = bodyQuery.GetComponent(gUid);
            EntManager.TryGetComponent<IFFComponent>(gUid, out var iff);

            if (!_shuttles.CanDraw(gUid, gridBody, iff))
                continue;

            var hideLabel = iff != null && (iff.Flags & IFFFlags.HideLabel) != 0x0;
            var noLabel = iff != null && (iff.Flags & IFFFlags.HideLabelAlways) != 0x0;
            var detectionLevel = _consoleEntity == null ? DetectionLevel.Detected : GetGridDetected(grid.Owner);
            var detected = detectionLevel != DetectionLevel.Undetected || !hideLabel;
            var blipOnly = detectionLevel != DetectionLevel.Detected; // don't show outline outside of detection radius even if IFF on
            if (!detected)
                continue;

            if (!blipOnly)
                _visibleGridsSet.Add(grid);
            var curGridToWorld = _transform.GetWorldMatrix(gUid);
            var curGridToView = curGridToWorld * worldToView;

            var hideColor = hideLabel && iff != null && (iff.Flags & IFFFlags.AlwaysShowColor) == 0x0;
            var labelColor = hideColor ? blipOnly ? Color.Orange : Color.White : _shuttles.GetIFFColor(grid, self: false, iff);
            var coordColor = new Color(labelColor.R * 0.8f, labelColor.G * 0.8f, labelColor.B * 0.8f, 0.5f);

            var isPlayerShuttle = iff != null && (iff.Flags & IFFFlags.IsPlayerShuttle) != 0x0;
            // Others default:
            // Color.FromHex("#FFC000FF")
            // Hostile default: Color.Firebrick
            // Mono
            var labelName = noLabel ? null : hideLabel ?
                detectionLevel == DetectionLevel.PartialDetected ?
                    Loc.GetString($"shuttle-console-signature-infrared")
                    : _detection.HandleUnknownMassLabel(grid.Owner)
                : _shuttles.GetIFFLabel(grid, self: false, component: iff);

            var shouldDrawIFF = ShowIFF && labelName != null;
            if (shouldDrawIFF)
            {
                if (IFFFilter != null)
                    shouldDrawIFF &= IFFFilter(gUid, grid.Comp, iff, hideLabel, labelName!);
                if (isPlayerShuttle)
                    shouldDrawIFF &= ShowIFFShuttles;
            }

            //var mapCenter = curGridToWorld. * gridBody.LocalCenter;
            //shouldDrawIFF = NfCheckShouldDrawIffRangeCondition(shouldDrawIFF, mapCenter, curGridToWorld); // Frontier code
            // Frontier: range checks // Mono
            var gridMapPos = _transform.ToMapCoordinates(new EntityCoordinates(gUid, gridBody.LocalCenter)).Position;
            if (!hideLabel) // Mono - show thermal signatures even at long range
                shouldDrawIFF = NfCheckShouldDrawIffRangeCondition(shouldDrawIFF, mapPos.Position - gridMapPos);
            // End Frontier

            // Mono
            var gridUiPosition = Vector2.Transform(gridBody.LocalCenter, curGridToView) / UIScale;

            if (shouldDrawIFF)
            {
                //var gridCentre = Vector2.Transform(gridBody.LocalCenter, curGridToView);
                //gridCentre.Y = -gridCentre.Y;

                // Frontier: IFF drawing functions
                // The actual position in the UI. We offset the matrix position to render it off by half its width
                // plus by the offset.
                //var uiPosition = ScalePosition(gridCentre) / UIScale;
                var uiPosition = gridUiPosition; // Mono

                // Confines the UI position within the viewport.
                var uiXCentre = (int)Width / 2;
                var uiYCentre = (int)Height / 2;
                var uiXOffset = uiPosition.X - uiXCentre;
                var uiYOffset = uiPosition.Y - uiYCentre;
                var uiDistance = MathF.Sqrt(uiXOffset * uiXOffset + uiYOffset * uiYOffset);
                if (uiDistance <= float.Epsilon)
                    uiDistance = 1f;

                var uiX = uiXCentre * uiXOffset / uiDistance;
                var uiY = uiYCentre * uiYOffset / uiDistance;

                var isOutsideRadarCircle = uiDistance > Math.Abs(uiX) && uiDistance > Math.Abs(uiY);
                if (isOutsideRadarCircle)
                {
                    // 0.95f for offsetting the icons slightly away from edge of radar so it doesnt clip.
                    uiX = uiXCentre * uiXOffset / uiDistance * 0.95f;
                    uiY = uiYCentre * uiYOffset / uiDistance * 0.95f;
                    uiPosition = new Vector2(
                        x: uiX + uiXCentre,
                        y: uiY + uiYCentre
                    );
                }

                var scaledMousePosition = GetMouseCoordinatesFromCenter().Position * UIScale;
                var isMouseOver = Vector2.Distance(scaledMousePosition, uiPosition * UIScale) < 30f;

                // Distant stations that are not player controlled ships
                var isDistantPOI = iff != null || (iff == null || (iff.Flags & IFFFlags.IsPlayerShuttle) == 0x0);

                var distance = Vector2.Distance(gridMapPos, mapPos.Position);

                if (!isOutsideRadarCircle || isDistantPOI || isMouseOver)
                {
                    // Shows decimal when distance is < 50m, otherwise pointless to show it.
                    var displayedDistance = distance < 50f ? $"{distance:0.0}" : distance < 1000 ? $"{distance:0}" : $"{distance / 1000:0.0}k";
                    var labelText = Loc.GetString("shuttle-console-iff-label", ("name", labelName)!, ("distance", displayedDistance));

                    var coordsText = $"({gridMapPos.X:0.0}, {gridMapPos.Y:0.0})";

                    #region Mono

                    // Why are the magic numbers 0.9 and 0.7 used? I have no fucking clue.
                    var labelDimensions = handle.GetDimensions(Font, labelText, 0.9f);
                    var blipSize = RadarBlipSize * 0.7f;

                    // The center of the radar in UI space.
                    var uiCenter = new Vector2(Width * 0.5f, Height * 0.5f);

                    // Whether the blip is on the left side of the center of the radar.
                    var isOnLeftSide = (uiPosition - uiCenter).X < 0;

                    // The UI position of the bottom-left corner of the label, relative to the UI center of the radar, when the label is right-aligned.
                    var labelPosition = uiPosition + new Vector2(-labelDimensions.X - blipSize, -labelDimensions.Y * 0.5f) - uiCenter;

                    // The radius and squared radius of the radar, in virtual pixels.
                    var radius = Width * 0.5f;
                    var squaredRadius = radius * radius;

                    // If true, flip the entire label to the right side of the blip and left-align it.
                    // We default to the label being on the left side of the blip because it looked better to me in testing. (arbitrary)
                    var labelRight = labelPosition + new Vector2(labelDimensions.X, 0f);
                    var labelBottom = labelPosition + new Vector2(0f, labelDimensions.Y);
                    var labelBottomRight = labelPosition + labelDimensions;
                    var flipLabel = isOnLeftSide &&
                                    (labelPosition.LengthSquared() > squaredRadius ||
                                     labelRight.LengthSquared() > squaredRadius ||
                                     labelBottom.LengthSquared() > squaredRadius ||
                                     labelBottomRight.LengthSquared() > squaredRadius);

                    // Calculate unscaled offsets.
                    var labelOffset = new Vector2()
                    {
                        X = flipLabel
                            ? blipSize // Label on the right side of the blip, left-aligned text.
                            : -labelDimensions.X - blipSize, // Label on the left side of the blip, right-aligned text.
                        Y = -labelDimensions.Y * 0.5f
                    };

                    #endregion Mono

                    // Get company color if entity has CompanyComponent
                    var displayColor = labelColor;
                    if (!hideLabel && EntManager.TryGetComponent(gUid, out Shared._Mono.Company.CompanyComponent? companyComp) &&
                        !string.IsNullOrEmpty(companyComp.CompanyName))
                    {
                        CompanyPrototype? prototype = null;
                        if (_prototypeManager.TryIndex(companyComp.CompanyName, out prototype) && prototype != null)
                        {
                            displayColor = prototype.Color;
                        }
                    }

                    var lineBreak = labelText.IndexOf('\n');
                    var mainLabel = lineBreak < 0 ? labelText : labelText[..lineBreak];
                    var companyLabel = !hideLabel && lineBreak >= 0
                        ? labelText[(lineBreak + 1)..]
                        : null;

                    // Draw main ship label with company color if available
                    handle.DrawString(Font, (uiPosition + labelOffset) * UIScale, mainLabel, UIScale * 0.9f, displayColor);

                    // Draw company label if present
                    if (companyLabel != null)
                    {
                        var companyLabelOffset = new Vector2(
                            labelOffset.X,
                            labelOffset.Y + handle.GetDimensions(Font, mainLabel, 0.9f).Y
                        );

                        handle.DrawString(Font, (uiPosition + companyLabelOffset) * UIScale, companyLabel, UIScale * 0.9f, displayColor);
                    }

                    if (isMouseOver && !HideCoords)
                    {
                        var coordDimensions = handle.GetDimensions(Font, coordsText, 0.7f);
                        var coordOffset = new Vector2()
                        {
                            X = uiPosition.X > Width / 2f
                                ? -coordDimensions.X - blipSize / 0.7f // right align the text to left of the blip (0.7 needed for scale)
                                : blipSize, // left align the text to the right of the blip
                            Y = labelOffset.Y + handle.GetDimensions(Font, mainLabel, 1f).Y + (companyLabel != null ? handle.GetDimensions(Font, companyLabel, 1f).Y : 0) + 5
                        };
                        handle.DrawString(Font, (uiPosition + coordOffset) * UIScale, coordsText, 0.7f * UIScale, displayColor);
                    }
                }

                NfAddBlipToList(_tempBlipDataList, isOutsideRadarCircle, uiPosition, uiXCentre, uiYCentre, labelColor, hideLabel ? default : gUid); // Frontier code
                // End Frontier: IFF drawing functions
            }

            // Detailed view
            var gridAABB = curGridToWorld.TransformBox(grid.Comp.LocalAABB);

            // Skip drawing if it's out of range.
            if (!gridAABB.Intersects(viewAABB))
                continue;

            // Mono
            if (!blipOnly)
            {
                DrawGrid(handle, curGridToView, grid, labelColor);
                DrawDocks(handle, gUid, curGridToView);
            }
        }

        // Draw the accumulated blips once. Drawing this inside the grid loop made the same growing
        // list render repeatedly, which was quadratic in the number of visible grids.
        NfDrawBlips(handle, _tempBlipDataList);

        // If we've set the controlling console, and it's on a different grid
        // to the shuttle itself, then draw an additional marker to help the
        // player determine where they are relative to the shuttle.
        if (_consoleEntity != null && xformQuery.TryGetComponent(_consoleEntity, out var consoleXform))
        {
            if (consoleXform.ParentUid != _coordinates.Value.EntityId)
            {
                var consolePositionWorld = _transform.GetWorldPosition((EntityUid)_consoleEntity);
                var p = Vector2.Transform(consolePositionWorld, worldToView);
                handle.DrawCircle(p, 5, Color.ToSrgb(Color.Cyan), true);
            }
        }

        #region Mono
        // Draw radar line
        // First, figure out which angle to draw.
        var updateRatio = _updateAccumulator / RadarUpdateInterval;

        Angle angle = updateRatio * Math.Tau;
        var origin = ScalePosition(-new Vector2(Offset.X, -Offset.Y));
        handle.DrawLine(origin, origin + angle.ToVec() * ScaledMinimapRadius * 1.42f, Color.Red.WithAlpha(0.1f));

        // Get blips
        var rawBlips = _blips.GetCurrentBlips();

        // Prepare view bounds for culling
        var monoViewBounds = new Box2(-3f, -3f, PixelSize.X + 3f, PixelSize.Y + 3f);

        // Draw blips using the same grid-relative transformation approach as docks
        foreach (var blip in rawBlips)
        {
            var position = Vector2.Transform(_transform.ToMapCoordinates(blip.Position).Position, worldToView);
            var color = blip.Config.Color.WithAlpha(0.8f);
            var box = new Box2Rotated(blip.Config.Bounds, 0);
            if (blip.Config.RespectZoom)
                box.Box = new Box2(box.Box.BottomLeft * MinimapScale, box.Box.TopRight * MinimapScale);
            if (blip.Config.Rotate)
                box.Rotation = worldRot - blip.Rotation;

            if (blip.GridUid is { } grid)
            {
                // check detection if we're on a grid and that grid isn't our grid
                if (!_visibleGridsSet.Contains(grid) && grid != ourGridId)
                    continue;
            }

            // Check if this blip is within view bounds before drawing
            if (monoViewBounds.Contains(position))
            {
                DrawBlipShape(handle, position, box, color, blip.Config.Shape);
            }
        }

        // Draw missile lines from the radar blips system
        var missileLines = _blips.GetMissileLines();
        foreach (var line in missileLines)
        {
            var startPos = new Vector2(line.PositionStart.X, line.PositionStart.Y);
            var startEnd = new Vector2(line.PositionEnd.X, line.PositionEnd.Y);
            var startPosInView = Vector2.Transform(startPos, worldToView);
            var endPosInView = Vector2.Transform(startEnd, worldToView);

            // Only draw lines if at least one endpoint is within view
            if (monoViewBounds.Contains(startPosInView) || monoViewBounds.Contains(endPosInView))
            {
                // Draw the line with the specified thickness and color
                handle.DrawLine(startPosInView, endPosInView, line.Color);
            }
        }

        // Draw hitscan lines from the radar blips system
        var hitscanLines = _blips.GetHitscanLines();
        foreach (var line in hitscanLines)
        {
            var startPosInView = Vector2.Transform(line.Start, worldToView);
            var endPosInView = Vector2.Transform(line.End, worldToView);

            // Only draw lines if at least one endpoint is within view
            if (monoViewBounds.Contains(startPosInView) || monoViewBounds.Contains(endPosInView))
            {
                // Draw the line with the specified thickness and color
                handle.DrawLine(startPosInView, endPosInView, line.Color);

                // For thicker lines, draw multiple lines side by side
                if (line.Thickness > 1.0f)
                {
                    // Calculate perpendicular vector for thickness
                    var dir = (endPosInView - startPosInView).Normalized();
                    var perpendicular = new Vector2(-dir.Y, dir.X) * 0.5f;

                    // Draw additional lines for thickness
                    for (float i = 1; i <= line.Thickness; i += 1.0f)
                    {
                        var offset = perpendicular * i;
                        handle.DrawLine(startPosInView + offset, endPosInView + offset, line.Color);
                        handle.DrawLine(startPosInView - offset, endPosInView - offset, line.Color);
                    }
                }
            }
        }

        DrawBssNavigation(handle, xform.MapID, ourGridId, worldToView);
        DrawKoronusBoundary(handle, xform.MapID, observerPosition, worldToView);
        #endregion
    }

    private void DrawBssNavigation(
        DrawingHandleScreen handle,
        MapId mapId,
        EntityUid? ourGridId,
        Matrix3x2 worldToView)
    {
        if (TargetingMode == ShuttleNavTargetingMode.None || ourGridId == null || !_isMouseInside)
            return;

        var targetCoordinates = GetMouseCoordinatesFromCenter();
        if (!targetCoordinates.IsValid(EntManager))
            return;

        string? capturedName = null;
        if (TargetingMode == ShuttleNavTargetingMode.Autopilot &&
            TryGetTargetGrid(targetCoordinates, out var targetGrid) &&
            EntManager.TryGetComponent(targetGrid, out PhysicsComponent? targetBody))
        {
            targetCoordinates = new EntityCoordinates(targetGrid, targetBody.LocalCenter);
            capturedName = EntManager.GetComponent<MetaDataComponent>(targetGrid).EntityName;
        }
        else if (TargetingMode == ShuttleNavTargetingMode.Bss &&
                 TryGetTargetBeacon(targetCoordinates, out var targetBeacon))
        {
            targetCoordinates = EntManager.GetCoordinates(targetBeacon.Coordinates);
            capturedName = targetBeacon.Name;
        }

        var targetMapCoordinates = _transform.ToMapCoordinates(targetCoordinates);
        if (targetMapCoordinates.MapId != mapId)
            return;

        var targetColor = Color.LimeGreen;
        if (TargetingMode == ShuttleNavTargetingMode.Bss &&
            !_shuttles.FTLFree(ourGridId.Value, targetCoordinates, TargetAngle, _bssExclusions))
        {
            targetColor = Color.Magenta;
        }

        var targetPosition = Vector2.Transform(targetMapCoordinates.Position, worldToView);
        // The green NAV diamond marks the movable camera origin. Travel, however, starts at the
        // shuttle's physics centre, which is also what FTL range checks and autopilot steering use.
        if (!EntManager.TryGetComponent(ourGridId.Value, out PhysicsComponent? ourBody) ||
            !EntManager.TryGetComponent(ourGridId.Value, out TransformComponent? ourTransform))
        {
            return;
        }

        var shuttleMapPosition = Maps.GetGridPosition((ourGridId.Value, ourBody, ourTransform));
        var startPosition = Vector2.Transform(shuttleMapPosition, worldToView);

        handle.DrawDottedLine(startPosition, targetPosition, targetColor, (float) _timing.RealTime.TotalSeconds * 30f);
        handle.DrawCircle(targetPosition, 13f, targetColor.WithAlpha(0.08f));
        handle.DrawCircle(targetPosition, 13f, targetColor, filled: false);
        handle.DrawLine(targetPosition - Vector2.UnitX * 7f, targetPosition + Vector2.UnitX * 7f, targetColor);
        handle.DrawLine(targetPosition - Vector2.UnitY * 7f, targetPosition + Vector2.UnitY * 7f, targetColor);

        var direction = Vector2.TransformNormal(TargetAngle.RotateVec(new Vector2(0f, -1f)), worldToView);
        if (direction.LengthSquared() > 0.001f)
        {
            direction = Vector2.Normalize(direction) * 24f;
            var tip = targetPosition + direction;
            var normal = new Vector2(-direction.Y, direction.X) * 0.22f;
            handle.DrawLine(targetPosition, tip, targetColor);
            handle.DrawLine(tip, tip - direction * 0.35f + normal, targetColor);
            handle.DrawLine(tip, tip - direction * 0.35f - normal, targetColor);
        }

        if (!string.IsNullOrEmpty(capturedName))
            handle.DrawString(Font, targetPosition + new Vector2(15f, -18f) * UIScale, capturedName, 0.82f * UIScale, targetColor);
    }

    protected DetectionLevel GetGridDetected(EntityUid grid)
    {
        if (Detectors != null)
            return _detection.IsGridDetected(grid, Detectors);

        return _consoleEntity == null ? DetectionLevel.Undetected : _detection.IsGridDetected(grid, _consoleEntity.Value);
    }

    private (Vector2 Top, Vector2 Left, Vector2 Offset) GetSize(Box2Rotated bounds)
    {
        var top = (bounds.TopLeft + bounds.TopRight) * 0.5f;
        var left = (bounds.TopLeft + bounds.BottomLeft) * 0.5f;
        var offset = (bounds.TopRight + bounds.BottomLeft) * 0.5f;

        return (top - offset, left - offset, offset);
    }

    private void DrawCelestialNavigation(DrawingHandleScreen handle, Matrix3x2 worldToView)
    {
        _planetHitTargets.Clear();
        if (!_planetaryState.Available)
            return;

        var stellarPosition = Vector2.Transform(_planetaryState.StellarCenter, worldToView);
        var orbitingBodies = _planetaryState.Bodies.Where(body =>
            body.OrbitRadius > 0f && MathF.Abs(body.OrbitAngularSpeed) > float.Epsilon);

        foreach (var body in orbitingBodies)
        {
            var orbitRadius = body.OrbitRadius * MinimapScale;
            if (orbitRadius > 0f)
            {
                // A dark shoulder and a brighter inner trace keep the orbit readable over both the
                // tactical grid and the animated celestial shaders without turning it into a halo.
                handle.DrawCircle(
                    stellarPosition,
                    orbitRadius + UIScale,
                    KoronusOrbitShadowColor,
                    filled: false);
                handle.DrawCircle(stellarPosition, orbitRadius, KoronusOrbitColor, filled: false);
            }
        }

        var star = _planetaryState.Bodies.FirstOrDefault(body => body.BodyType == "Star");
        var sunRadius = star?.NavVisualRadius * MinimapScale ?? 0f;
        if (sunRadius > 0f)
            _sunRenderer.Draw(handle, stellarPosition, sunRadius);

        var phaseTime = (float) IoCManager.Resolve<IGameTiming>().CurTime.TotalSeconds;
        foreach (var body in _planetaryState.Bodies)
        {
            if (body.OrbitRadius <= 0f)
                continue;

            var position = GetCelestialPosition(body, phaseTime);
            var viewPosition = Vector2.Transform(position, worldToView);
            var radius = body.NavVisualRadius * MinimapScale;
            var color = GetCelestialColor(body);

            if (radius <= 0f)
                continue;

            handle.DrawCircle(viewPosition, radius + 3f * UIScale, Color.Black.WithAlpha(0.75f));
            var renderedAsPlanet = false;
            if ((body.BodyType is "Planet" or "Moon" or "Asteroid") &&
                _prototypeManager.TryIndex<KoronusCelestialBodyPrototype>(body.Id, out var bodyPrototype))
            {
                renderedAsPlanet = _planetRenderer.Draw(
                    handle,
                    viewPosition,
                    radius,
                    bodyPrototype,
                    stellarPosition - viewPosition);
            }

            if (!renderedAsPlanet)
                handle.DrawCircle(viewPosition, radius, color);

            handle.DrawCircle(viewPosition, radius + 1.5f * UIScale, Color.White.WithAlpha(0.55f), filled: false);

            if (viewPosition.X >= -radius * 2f &&
                viewPosition.X <= PixelWidth + radius * 2f &&
                viewPosition.Y >= -radius * 2f &&
                viewPosition.Y <= PixelHeight + radius * 2f)
            {
                var label = body.Name;
                var labelSize = handle.GetDimensions(Font, label, 0.6f * UIScale);
                handle.DrawString(
                    Font,
                    viewPosition + new Vector2(-labelSize.X * 0.5f, radius + 4f * UIScale),
                    label,
                    0.6f * UIScale,
                    Color.White.WithAlpha(0.84f));
            }

            var visualRadius = renderedAsPlanet ? radius * 1.25f : radius;
            var hitRadius = MathF.Max(visualRadius, 8f * UIScale) + 6f * UIScale;
            _planetHitTargets.Add(new PlanetHitTarget(body, viewPosition, hitRadius, visualRadius));
        }
    }

    private bool TrySelectPlanet(Vector2 position)
    {
        foreach (var target in _planetHitTargets)
        {
            if (Vector2.DistanceSquared(position, target.Position) > target.HitRadius * target.HitRadius)
                continue;

            PlanetSelected?.Invoke(target.Body);
            return true;
        }

        return false;
    }

    private Vector2 GetCelestialPosition(KoronusCelestialBodyState body, float time)
    {
        var phase = (body.OrbitPhase + body.OrbitAngularSpeed * time) * MathF.PI / 180f;
        return _planetaryState.StellarCenter + new Vector2(MathF.Cos(phase), MathF.Sin(phase)) * body.OrbitRadius;
    }

    private static Color GetCelestialColor(KoronusCelestialBodyState body)
    {
        return body.BodyType switch
        {
            "Moon" => Color.FromHex("#A9B0B6"),
            "Asteroid" => Color.FromHex("#8F856C"),
            "Station" => Color.FromHex("#76C2D0"),
            _ => Color.FromHex("#8CC971"),
        };
    }

    private readonly record struct PlanetHitTarget(
        KoronusCelestialBodyState Body,
        Vector2 Position,
        float HitRadius,
        float VisualRadius);

    private void DrawKoronusBoundary(
        DrawingHandleScreen handle,
        MapId mapId,
        Vector2 observerPosition,
        Matrix3x2 worldToView)
    {
        var mapUid = _mapManager.GetMapEntityId(mapId);
        if (!EntManager.TryGetComponent<KoronusSystemBoundaryComponent>(mapUid, out var boundary))
            return;

        var center = Vector2.Transform(boundary.Origin, worldToView);
        var boundaryRadius = boundary.Radius * MinimapScale;
        var warningRadius = boundary.Radius * boundary.WarningFraction;
        if (boundaryRadius <= 0f ||
            Vector2.DistanceSquared(observerPosition, boundary.Origin) < warningRadius * warningRadius)
            return;

        var outerRadius = MathF.Max(
                              MathF.Max(
                                  Vector2.Distance(center, Vector2.Zero),
                                  Vector2.Distance(center, new Vector2(PixelSize.X, 0f))),
                              MathF.Max(
                                  Vector2.Distance(center, new Vector2(0f, PixelSize.Y)),
                                  Vector2.Distance(center, PixelSize))) + 2f;

        DrawKoronusDangerBand(handle, center, boundaryRadius, outerRadius);
        handle.DrawCircle(center, boundaryRadius, Color.FromHex("#E02828").WithAlpha(0.96f), filled: false);
    }

    private void DrawKoronusDangerBand(DrawingHandleScreen handle, Vector2 center, float innerRadius, float outerRadius)
    {
        if (outerRadius <= innerRadius)
            return;

        for (var i = 0; i <= KoronusBoundaryBandSegments; i++)
        {
            var direction = KoronusBoundaryBandDirections[i];
            var vertex = i * 2;
            _koronusBoundaryBandVertices[vertex] = center + direction * innerRadius;
            _koronusBoundaryBandVertices[vertex + 1] = center + direction * outerRadius;
        }

        handle.DrawPrimitives(
            DrawPrimitiveTopology.TriangleStrip,
            _koronusBoundaryBandVertices,
            Color.FromHex("#4A0606").WithAlpha(0.78f));
    }

    private static Vector2[] CreateKoronusBoundaryBandDirections()
    {
        var directions = new Vector2[KoronusBoundaryBandSegments + 1];
        for (var i = 0; i <= KoronusBoundaryBandSegments; i++)
        {
            var angle = MathF.Tau * i / KoronusBoundaryBandSegments;
            directions[i] = new Vector2(MathF.Cos(angle), MathF.Sin(angle));
        }

        return directions;
    }

    private void DrawBlipShape(DrawingHandleScreen handle, Vector2 position, Box2Rotated bounds, Color color, RadarBlipShape shape)
    {
        switch (shape)
        {
            case RadarBlipShape.Circle:
                DrawCircle(handle, position, bounds, color);
                break;
            case RadarBlipShape.Square:
                var boxPoints = new Vector2[]
                {
                    position + bounds.TopLeft,
                    position + bounds.TopRight,
                    position + bounds.BottomRight,
                    position + bounds.BottomLeft
                };
                handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, boxPoints, color);
                break;
            case RadarBlipShape.Triangle:
                var points = new Vector2[]
                {
                    position + bounds.Origin + bounds.Rotation.RotateVec((bounds.TopLeft + bounds.TopRight) * 0.5f - bounds.Origin),
                    position + bounds.BottomLeft,
                    position + bounds.BottomRight
                };
                handle.DrawPrimitives(DrawPrimitiveTopology.TriangleList, points, color);
                break;
            case RadarBlipShape.Star:
                DrawStar(handle, position, bounds, color);
                break;
            case RadarBlipShape.Diamond:
                var size = GetSize(bounds);
                var diamondPoints = new Vector2[]
                {
                    position + size.Offset + size.Top,
                    position + size.Offset + size.Left,
                    position + size.Offset - size.Top,
                    position + size.Offset - size.Left
                };
                handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, diamondPoints, color);
                break;
            case RadarBlipShape.Hexagon:
                DrawHexagon(handle, position, bounds, color);
                break;
            case RadarBlipShape.Arrow:
                DrawArrow(handle, position, bounds, color);
                break;
        }
    }

    private void DrawCircle(DrawingHandleScreen handle, Vector2 position, Box2Rotated bounds, Color color)
    {
        const int segments = 64;
        var buffer = new Vector2[segments + 1];
        var size = GetSize(bounds);
        var offsetPos = position + size.Offset;

        for (var i = 0; i <= segments; i++)
        {
            var angle = i * MathF.Tau / segments;
            var pos = size.Left * MathF.Sin(angle) + size.Top * MathF.Cos(angle);

            buffer[i] = offsetPos + pos;
        }

        handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, buffer, color);
    }

    private void DrawStar(DrawingHandleScreen handle, Vector2 position, Box2Rotated bounds, Color color)
    {
        const int points = 5;
        const float innerRatio = 0.4f;
        var vertices = new Vector2[points * 2];
        var size = GetSize(bounds);
        var offsetPos = position + size.Offset;

        for (var i = 0; i < points * 2; i++)
        {
            var angle = i * MathF.PI / points;
            var radius = i % 2 == 0 ? 1f : innerRatio;
            vertices[i] = offsetPos + radius * MathF.Sin(angle) * size.Left - radius * MathF.Cos(angle) * size.Top;
        }

        handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, vertices, color);
    }

    private void DrawHexagon(DrawingHandleScreen handle, Vector2 position, Box2Rotated bounds, Color color)
    {
        var vertices = new Vector2[6];
        var size = GetSize(bounds);
        var offsetPos = position + size.Offset;

        for (var i = 0; i < 6; i++)
        {
            var angle = i * MathF.PI / 3;
            vertices[i] = offsetPos + MathF.Sin(angle) * size.Top - MathF.Cos(angle) * size.Left;
        }

        handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, vertices, color);
    }

    private void DrawArrow(DrawingHandleScreen handle, Vector2 position, Box2Rotated bounds, Color color)
    {
        var size = GetSize(bounds);
        var offsetPos = position + size.Offset;

        var vertices = new Vector2[]
        {
            offsetPos - size.Top,                    // Tip
            offsetPos + size.Left + size.Top * 0.5f, // Left wing
            offsetPos + size.Top,                    // Bottom
            offsetPos - size.Left + size.Top * 0.5f  // Right wing
        };

        handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, vertices, color);
    }

    private void DrawDocks(DrawingHandleScreen handle, EntityUid uid, Matrix3x2 gridToView)
    {
        if (!ShowDocks)
            return;

        const float DockScale = 0.6f;
        var nent = EntManager.GetNetEntity(uid);

        const float sqrt2 = 1.41421356f;
        const float dockRadius = DockScale * sqrt2;
        // Worst-case bounds used to cull a dock:
        Box2 viewBounds = new Box2(-dockRadius, -dockRadius, PixelSize.X + dockRadius, PixelSize.Y + dockRadius); // Frontier: Size<PixelSize
        if (_docks.TryGetValue(nent, out var docks))
        {
            foreach (var state in docks)
            {
                var position = state.Coordinates.Position;

                var positionInView = Vector2.Transform(position, gridToView);
                if (!viewBounds.Contains(positionInView))
                {
                    continue;
                }

                //var color = Color.ToSrgb(Color.Magenta); // Frontier
                var color = Color.ToSrgb(state.HighlightedRadarColor); // Frontier

                var verts = new[]
                {
                    Vector2.Transform(position + new Vector2(-DockScale, -DockScale), gridToView),
                    Vector2.Transform(position + new Vector2(DockScale, -DockScale), gridToView),
                    Vector2.Transform(position + new Vector2(DockScale, DockScale), gridToView),
                    Vector2.Transform(position + new Vector2(-DockScale, DockScale), gridToView),
                };

                handle.DrawPrimitives(DrawPrimitiveTopology.TriangleFan, verts, color.WithAlpha(0.8f));
                handle.DrawPrimitives(DrawPrimitiveTopology.LineStrip, verts, color);
            }

            // Frontier: draw dock labels (done last to appear on top of all docks, still fights with other grids)
            var labeled = new HashSet<string>();
            foreach (var state in docks)
            {
                if (state.LabelName == null || labeled.Contains(state.LabelName))
                    continue;

                var position = state.Coordinates.Position;
                var uiPosition = Vector2.Transform(position, gridToView);

                if (!viewBounds.Contains(uiPosition))
                    continue;

                labeled.Add(state.LabelName);
                var labelDimensions = handle.GetDimensions(Font, state.LabelName, 0.9f);
                handle.DrawString(Font, (uiPosition / UIScale - labelDimensions / 2) * UIScale, state.LabelName, UIScale * 0.9f, _dockLabelColor);
            }
            // End Frontier
        }
    }

    protected Vector2 InverseScalePosition(Vector2 value)
    {
        var scaledValue = value * UIScale;
        return (scaledValue - MidPointVector) / MinimapScale;
    }

    // Mono
    protected EntityCoordinates GetMouseEntityCoordinates(Vector2 relativePosition)
    {
        if (_coordinates is not { } cord || _rotation is not { } rot)
            return EntityCoordinates.Invalid;

        // Keep selection as the exact inverse of the matrix used by Draw(). Maintaining a second,
        // hand-written offset/rotation conversion caused the preview and requested coordinates to
        // diverge increasingly as NAV zoom changed or the view was panned.
        var mapOrigin = _transform.ToMapCoordinates(cord).Offset(rot.RotateVec(Offset));
        if (mapOrigin.MapId == MapId.Nullspace || MinimapScale <= float.Epsilon)
            return EntityCoordinates.Invalid;

        var worldToView = Matrix3Helpers.CreateTranslation(-mapOrigin.Position) *
                          Matrix3Helpers.CreateRotation(-rot) *
                          Matrix3x2.CreateScale(new Vector2(MinimapScale, -MinimapScale)) *
                          Matrix3x2.CreateTranslation(MidPointVector);
        if (!Matrix3x2.Invert(worldToView, out var viewToWorld))
            return EntityCoordinates.Invalid;

        var worldPosition = Vector2.Transform(relativePosition * UIScale, viewToWorld);
        return _transform.ToCoordinates(new MapCoordinates(worldPosition, mapOrigin.MapId));
    }

    public class BlipData
    {
        public bool IsOutsideRadarCircle { get; set; }
        public Vector2 UiPosition { get; set; }
        public Vector2 VectorToPosition { get; set; }
        public Color Color { get; set; }
    }

    private const int RadarBlipSize = 15;
    private const int RadarFontSize = 8;

    private void DrawShields(DrawingHandleScreen handle, TransformComponent consoleXform, Matrix3x2 matrix)
    {
        var shields = EntManager.AllEntityQueryEnumerator<ShipShieldVisualsComponent, FixturesComponent, TransformComponent>();
        while (shields.MoveNext(out var uid, out var visuals, out var fixtures, out var xform))
        {
            if (!EntManager.TryGetComponent<TransformComponent>(xform.GridUid, out var parentXform))
                continue;

            if (xform.MapID != consoleXform.MapID)
                continue;

            // Don't draw shields when in FTL
            if (EntManager.HasComponent<FTLComponent>(parentXform.Owner))
                continue;

            var detectionLevel = _consoleEntity == null ? DetectionLevel.Detected : GetGridDetected(parentXform.Owner);
            if (detectionLevel != DetectionLevel.Detected)
                continue;

            var shieldFixture = fixtures.Fixtures.TryGetValue("shield", out var fixture) ? fixture : null;

            if (shieldFixture == null || shieldFixture.Shape is not ChainShape)
                continue;

            ChainShape chain = (ChainShape) shieldFixture.Shape;

            var count = chain.Count;
            var verticies = chain.Vertices;

            var center = _transform.WithEntityId(xform.Coordinates, xform.GridUid.Value).Position;

            for (int i = 1; i < count; i++)
            {
                var v1 = Vector2.Add(center, verticies[i - 1]);
                v1 = Vector2.Transform(v1, parentXform.WorldMatrix); // transform to world matrix
                v1 = Vector2.Transform(v1, matrix); // get back to local matrix for drawing
                v1.Y = -v1.Y;
                v1 = ScalePosition(v1);
                var v2 = Vector2.Add(center, verticies[i]);
                v2 = Vector2.Transform(v2, parentXform.WorldMatrix);
                v2 = Vector2.Transform(v2, matrix);
                v2.Y = -v2.Y;
                v2 = ScalePosition(v2);
                handle.DrawLine(v1, v2, visuals.ShieldColor);
            }
        }
    }
}
