using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared._WH40K.SectorMap.BUI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class ShuttleConsoleWindow : FancyWindow,
    IComputerWindow<ShuttleBoundUserInterfaceState>
{
    [Dependency] private IEntityManager _entManager = default!;

    private ShuttleConsoleMode _mode = ShuttleConsoleMode.Nav;

    public event Action<MapCoordinates, Angle>? RequestFTL;
    public event Action<NetEntity, Angle>? RequestBeaconFTL;

    // Mono
    public event Action<MapCoordinates, Angle>? RequestAutopilot;
    public event Action<NetEntity>? RequestAutopilotGrid;
    public event Action? RequestAutoDock;
    public event Action<string>? RequestSectorJump;
    public event Action<string, string>? RequestPlanetaryLanding;
    public event Action? RequestPlanetaryLaunch;

    public event Action<NetEntity, NetEntity>? DockRequest;
    public event Action<NetEntity>? UndockRequest;
    public event Action<List<NetEntity>>? UndockAllRequest;
    public event Action<List<NetEntity>, bool>? ToggleFTLLockRequest;
    public event Action<bool>? ToggleAutoDockRequest;

    public ShuttleConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Mode switching
        NavModeButton.OnPressed += NavPressed;
        DockModeButton.OnPressed += DockPressed;
        SectorModeButton.OnPressed += SectorPressed;

        // Modes are exclusive
        var group = new ButtonGroup();

        NavModeButton.Group = group;
        DockModeButton.Group = group;
        SectorModeButton.Group = group;

        NavModeButton.Pressed = true;
        SetupMode(_mode);

        NavContainer.RequestFTL += (coords, angle) =>
        {
            RequestFTL?.Invoke(coords, angle);
        };

        NavContainer.RequestBeaconFTL += (ent, angle) =>
        {
            RequestBeaconFTL?.Invoke(ent, angle);
        };

        // Mono
        NavContainer.RequestAutopilot += (coords, angle) =>
        {
            RequestAutopilot?.Invoke(coords, angle);
        };

        NavContainer.RequestAutopilotGrid += targetGrid =>
        {
            RequestAutopilotGrid?.Invoke(targetGrid);
        };

        NavContainer.AutoDockRequest += () =>
        {
            RequestAutoDock?.Invoke();
        };

        SectorContainer.RequestSectorJump += targetSystemId =>
        {
            RequestSectorJump?.Invoke(targetSystemId);
        };

        NavContainer.PlanetaryLandingRequest += (bodyId, siteId) =>
        {
            RequestPlanetaryLanding?.Invoke(bodyId, siteId);
        };

        NavContainer.PlanetaryLaunchRequest += () =>
        {
            RequestPlanetaryLaunch?.Invoke();
        };

        DockContainer.DockRequest += (entity, netEntity) =>
        {
            DockRequest?.Invoke(entity, netEntity);
        };

        DockContainer.UndockRequest += entity =>
        {
            UndockRequest?.Invoke(entity);
        };

        DockContainer.UndockAllRequest += dockEntities =>
        {
            UndockAllRequest?.Invoke(dockEntities);
        };

        DockContainer.ToggleFTLLockRequest += (dockEntities, enabled) =>
        {
            ToggleFTLLockRequest?.Invoke(dockEntities, enabled);
        };

        DockContainer.ToggleAutoDockRequest += enabled =>
        {
            ToggleAutoDockRequest?.Invoke(enabled);
        };

        NfInitialize(); // Frontier Initialization for the ShuttleConsoleWindow
    }

    private void ClearModes(ShuttleConsoleMode mode)
    {
        if (mode != ShuttleConsoleMode.Nav)
        {
            NavContainer.Visible = false;
        }

        if (mode != ShuttleConsoleMode.Dock)
        {
            DockContainer.Visible = false;
        }

        if (mode != ShuttleConsoleMode.Sector)
        {
            SectorContainer.Visible = false;
        }

    }

    private void NavPressed(BaseButton.ButtonEventArgs obj)
    {
        SwitchMode(ShuttleConsoleMode.Nav);
    }

    private void DockPressed(BaseButton.ButtonEventArgs obj)
    {
        SwitchMode(ShuttleConsoleMode.Dock);
    }

    private void SectorPressed(BaseButton.ButtonEventArgs obj)
    {
        SwitchMode(ShuttleConsoleMode.Sector);
    }

    private void SetupMode(ShuttleConsoleMode mode)
    {
        switch (mode)
        {
            case ShuttleConsoleMode.Nav:
                NavContainer.Visible = true;
                break;
            case ShuttleConsoleMode.Dock:
                DockContainer.Visible = true;
                break;
            case ShuttleConsoleMode.Sector:
                SectorContainer.Visible = true;
                break;
            default:
                throw new NotImplementedException();
        }
    }

    public void SwitchMode(ShuttleConsoleMode mode)
    {
        if (_mode == mode)
            return;

        _mode = mode;
        ClearModes(mode);
        SetupMode(_mode);
    }

    public enum ShuttleConsoleMode : byte
    {
        Nav,
        Dock,
        Sector,
    }

    public void UpdateState(EntityUid owner, ShuttleBoundUserInterfaceState cState)
    {
        var coordinates = _entManager.GetCoordinates(cState.NavState.Coordinates);
        NavContainer.SetShuttle(coordinates?.EntityId);
        NavContainer.SetConsole(owner);
        NavContainer.UpdateState(cState.NavState);
        NavContainer.UpdateMapState(cState.MapState);
        DockContainer.UpdateState(coordinates?.EntityId, cState.DockState);
        SectorContainer.UpdateState(cState.SectorState);
        NavContainer.UpdatePlanetaryState(cState.PlanetaryState);
    }
}
