using System;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.CCVar;
using Content.Shared.Dataset;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using Robust.Shared.Network;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;

namespace Content.Client.Launcher
{
    [GenerateTypedNameReferences]
    public sealed partial class LauncherConnectingGui : Control
    {
        private const float RedialWaitTimeSeconds = 15f;
        private readonly LauncherConnecting _state;
        private float _waitTime;

        // Pressing reconnect will redial instead of simply reconnecting.
        private bool _redial;

        private readonly IRobustRandom _random;
        private readonly IPrototypeManager _prototype;
        private readonly IConfigurationManager _cfg;
        private readonly IClipboardManager _clipboard;
        private readonly ExtendedDisconnectInformationManager _extendedDisconnectInformationManager;

        public LauncherConnectingGui(LauncherConnecting state, IRobustRandom random,
            IPrototypeManager prototype, IConfigurationManager config, IClipboardManager clipboard)
        {
            _state = state;
            _random = random;
            _prototype = prototype;
            _cfg = config;
            _clipboard = clipboard;
            _extendedDisconnectInformationManager = IoCManager.Resolve<ExtendedDisconnectInformationManager>();

            RobustXamlLoader.Load(this);

            LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);

            Stylesheet = IoCManager.Resolve<IStylesheetManager>().SheetSpace;

            ChangeLoginTip();
            ExitButton.Text = Loc.GetString(state.UsesManualConnectTarget ? "connecting-back" : "connecting-exit");
            RetryButton.OnPressed += ReconnectButtonPressed;
            ReconnectButton.OnPressed += ReconnectButtonPressed;

            CopyButton.OnPressed += CopyButtonPressed;
            CopyButtonDisconnected.OnPressed += CopyButtonDisconnectedPressed;
            ExitButton.OnPressed += ExitButtonPressed;

            var addr = state.Address;
            if (addr != null)
                ConnectingAddress.Text = addr;

            state.PageChanged += OnPageChanged;
            state.ConnectFailReasonChanged += ConnectFailReasonChanged;
            state.ConnectionStateChanged += ConnectionStateChanged;
            state.ConnectFailed += HandleDisconnectReason;
            _cfg.OnValueChanged(CCVars.UiWindowOpacity, ApplyConfiguredWindowOpacity, true);

            ConnectionStateChanged(state.ConnectionState);

            // Redial flag setup
            _extendedDisconnectInformationManager.LastNetDisconnectedArgsChanged += LastNetDisconnectedArgsChanged;
            LastNetDisconnectedArgsChanged(_extendedDisconnectInformationManager.LastNetDisconnectedArgs);
        }

        [Obsolete]
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _state.PageChanged -= OnPageChanged;
                _state.ConnectFailReasonChanged -= ConnectFailReasonChanged;
                _state.ConnectionStateChanged -= ConnectionStateChanged;
                _state.ConnectFailed -= HandleDisconnectReason;
                _extendedDisconnectInformationManager.LastNetDisconnectedArgsChanged -= LastNetDisconnectedArgsChanged;
                _cfg.UnsubValueChanged(CCVars.UiWindowOpacity, ApplyConfiguredWindowOpacity);

                RetryButton.OnPressed -= ReconnectButtonPressed;
                ReconnectButton.OnPressed -= ReconnectButtonPressed;
                CopyButton.OnPressed -= CopyButtonPressed;
                CopyButtonDisconnected.OnPressed -= CopyButtonDisconnectedPressed;
                ExitButton.OnPressed -= ExitButtonPressed;
            }

#pragma warning disable CS0618
            base.Dispose(disposing);
#pragma warning restore CS0618
        }

        // Just button, there's only one at once anyways :)
        private void ReconnectButtonPressed(BaseButton.ButtonEventArgs args)
        {
            if (_redial)
            {
                // Redial shouldn't fail, but if it does, try a reconnect (maybe we're being run from debug)
                if (_state.Redial())
                    return;
            }

            _state.RetryConnect();
        }

        private void CopyButtonPressed(BaseButton.ButtonEventArgs args)
        {
            CopyText(ConnectFailReason.Text);
        }

        private void CopyButtonDisconnectedPressed(BaseButton.ButtonEventArgs args)
        {
            CopyText(DisconnectReason.Text);
        }

        private void CopyText(string? text)
        {
            if (!string.IsNullOrEmpty(text))
            {
                _clipboard.SetText(text);
            }
        }

        private void ExitButtonPressed(BaseButton.ButtonEventArgs args)
        {
            _state.Leave();
        }

        private void ConnectFailReasonChanged(string? reason)
        {
            ConnectFailReason.SetMessage(reason == null
                ? ""
                : Loc.GetString("connecting-fail-reason", ("reason", reason)));
        }

        private void LastNetDisconnectedArgsChanged(NetDisconnectedArgs? args)
        {
            HandleDisconnectReason(args);
        }

        private void HandleDisconnectReason(INetStructuredReason? reason)
        {
            if (reason == null)
            {
                _waitTime = 0;
                _redial = false;
            }
            else
            {
                _redial = reason.RedialFlag;

                if (reason.Message.Int32Of("delay") is { } delay)
                {
                    _waitTime = delay;
                }
                else if (_redial)
                {
                    _waitTime = RedialWaitTimeSeconds;
                }
            }
        }

        private void ChangeLoginTip()
        {
            var tipsDataset = _cfg.GetCVar(CCVars.LoginTipsDataset);
            var loginTipsEnabled = _prototype.TryIndex<LocalizedDatasetPrototype>(tipsDataset, out var tips);

            LoginTips.Visible = loginTipsEnabled;
            if (!loginTipsEnabled)
            {
                return;
            }

            var tipList = tips!.Values;

            if (tipList.Count == 0)
                return;

            var randomIndex = _random.Next(tipList.Count);
            var tip = tipList[randomIndex];
            LoginTip.SetMessage(Loc.GetString(tip));

            LoginTipTitle.Text = Loc.GetString("connecting-window-tip", ("numberTip", randomIndex + 1));
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);

            var button = _state.CurrentPage == LauncherConnecting.Page.ConnectFailed
                ? RetryButton
                : ReconnectButton;

            _waitTime -= args.DeltaSeconds;
            if (_waitTime <= 0)
            {
                button.Disabled = false;
                var key = _redial
                    ? "connecting-redial"
                    : _state.CurrentPage == LauncherConnecting.Page.ConnectFailed
                        ? "connecting-reconnect"
                        : "connecting-retry";

                button.Text = Loc.GetString(key);
            }
            else
            {
                var seconds = Math.Max(1, (int) Math.Ceiling(_waitTime));
                button.Disabled = true;
                button.Text = Loc.GetString("connecting-redial-wait", ("time", seconds));
            }
        }

        private void OnPageChanged(LauncherConnecting.Page page)
        {
            ConnectingStatus.Visible = page == LauncherConnecting.Page.Connecting;
            ConnectFail.Visible = page == LauncherConnecting.Page.ConnectFailed;
            Disconnected.Visible = page == LauncherConnecting.Page.Disconnected;

            if (page == LauncherConnecting.Page.Disconnected)
                DisconnectReason.Text = _state.LastDisconnectReason;
        }

        private void ConnectionStateChanged(ClientConnectionState state)
        {
            ConnectStatus.Text = Loc.GetString($"connecting-state-{state}");
        }

        private void ApplyConfiguredWindowOpacity(float opacity)
        {
            WindowOpacityHelper.ApplyPanelOpacity(ConnectingPanel, opacity);
            WindowOpacityHelper.ApplyPanelOpacity(ConnectingFooterDivider, opacity, Color.FromHex("#444444"));
            WindowOpacityHelper.ApplyPanelOpacity(LoginTips, opacity);
            WindowOpacityHelper.ApplySelfModulateOpacity(LoginTipsHeaderStripe, opacity);
        }
    }
}
