using System.Numerics;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Screens;

[GenerateTypedNameReferences]
public sealed partial class DefaultGameScreen : InGameScreen
{
    private HudVisibilityState? _hudVisibilityState;
    private bool _hudHidden;

    public DefaultGameScreen()
    {
        RobustXamlLoader.Load(this);

        AutoscaleMaxResolution = new Vector2i(1080, 770);

        SetAnchorPreset(MainViewport, LayoutPreset.Wide);
        SetAnchorPreset(ViewportContainer, LayoutPreset.Wide);
        SetAnchorAndMarginPreset(TopLeft, LayoutPreset.TopLeft, margin: 10);
        SetAnchorAndMarginPreset(Ghost, LayoutPreset.BottomWide, margin: 80);
        SetAnchorAndMarginPreset(Inventory, LayoutPreset.BottomLeft, margin: 5);
        SetAnchorAndMarginPreset(Hotbar, LayoutPreset.BottomWide, margin: 5);
        SetAnchorAndMarginPreset(Chat, LayoutPreset.TopRight, margin: 10);
        SetAnchorAndMarginPreset(Alerts, LayoutPreset.TopRight, margin: 10);
        SetAnchorAndMarginPreset(Targeting, LayoutPreset.BottomRight, margin: 5); // Shitmed Change

        Chat.OnResized += ChatOnResized;
        Chat.OnChatResizeFinish += ChatOnResizeFinish;
        MainViewport.OnResized += ResizeActionContainer;
        MainViewport.OnResized += ResizeAlertsContainer;
        Inventory.OnResized += ResizeActionContainer;
    }

    private void ResizeActionContainer()
    {
        float indent = Inventory.Size.Y + TopBar.Size.Y + 40;
        Actions.ActionsContainer.MaxGridHeight = MainViewport.Size.Y - indent;
    }

    private void ResizeAlertsContainer()
    {
        float indent = Chat.Size.Y + Targeting.Size.Y + 120;
        Alerts.AlertContainer.MaxGridHeight = Math.Max(MainViewport.Size.Y - indent, 1);
    }

    private void ChatOnResizeFinish(Vector2 _)
    {
        var marginBottom = Chat.GetValue<float>(MarginBottomProperty);
        var marginLeft = Chat.GetValue<float>(MarginLeftProperty);
        OnChatResized?.Invoke(new Vector2(marginBottom, marginLeft));
    }

    private void ChatOnResized()
    {
        var marginBottom = Chat.GetValue<float>(MarginBottomProperty);
        SetMarginTop(Alerts, marginBottom);
    }

    public override ChatBox ChatBox => Chat;

    //TODO: There's probably a better way to do this... but this is also the easiest way.
    public override void SetChatSize(Vector2 size)
    {
        SetMarginBottom(Chat, size.X);
        SetMarginLeft(Chat, size.Y);
        SetMarginTop(Alerts, size.X);
    }

    public override void SetHudVisible(bool visible)
    {
        if (visible)
        {
            if (!_hudHidden || _hudVisibilityState == null)
                return;

            TopBar.Visible = _hudVisibilityState.TopBar;
            VoteMenu.Visible = _hudVisibilityState.VoteMenu;
            Actions.Visible = _hudVisibilityState.Actions;
            Ghost.Visible = _hudVisibilityState.Ghost;
            Inventory.Visible = _hudVisibilityState.Inventory;
            Hotbar.Visible = _hudVisibilityState.Hotbar;
            Targeting.Visible = _hudVisibilityState.Targeting;
            Chat.Visible = _hudVisibilityState.Chat;
            Alerts.Visible = _hudVisibilityState.Alerts;
            _hudHidden = false;
            return;
        }

        if (_hudHidden)
            return;

        _hudVisibilityState = new HudVisibilityState(
            TopBar.Visible,
            VoteMenu.Visible,
            Actions.Visible,
            Ghost.Visible,
            Inventory.Visible,
            Hotbar.Visible,
            Targeting.Visible,
            Chat.Visible,
            Alerts.Visible);

        TopBar.Visible = true;
        VoteMenu.Visible = false;
        Actions.Visible = false;
        Ghost.Visible = false;
        Inventory.Visible = false;
        Hotbar.Visible = false;
        Targeting.Visible = false;
        Chat.Visible = false;
        Alerts.Visible = false;
        _hudHidden = true;
    }

    public override void AttachDialogueOverlay(Control overlay)
    {
        if (overlay.Parent != this)
        {
            overlay.Orphan();
            AddChild(overlay);
            SetAnchorPreset(overlay, LayoutPreset.Wide);
        }

        overlay.SetPositionInParent(1);
    }

    private sealed record HudVisibilityState(
        bool TopBar,
        bool VoteMenu,
        bool Actions,
        bool Ghost,
        bool Inventory,
        bool Hotbar,
        bool Targeting,
        bool Chat,
        bool Alerts);
}
