using System.Numerics;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Screens;

[GenerateTypedNameReferences]
public sealed partial class SeparatedChatGameScreen : InGameScreen
{
    private HudVisibilityState? _hudVisibilityState;
    private bool _hudHidden;

    public SeparatedChatGameScreen()
    {
        RobustXamlLoader.Load(this);

        AutoscaleMaxResolution = new Vector2i(1080, 770);

        SetAnchorPreset(ScreenContainer, LayoutPreset.Wide);
        SetAnchorPreset(ViewportContainer, LayoutPreset.Wide);
        SetAnchorPreset(MainViewport, LayoutPreset.Wide);
        SetAnchorAndMarginPreset(Inventory, LayoutPreset.BottomLeft, margin: 5);
        SetAnchorAndMarginPreset(TopLeftContainer, LayoutPreset.TopLeft, margin: 10);
        SetAnchorAndMarginPreset(Ghost, LayoutPreset.BottomWide, margin: 80);
        SetAnchorAndMarginPreset(Hotbar, LayoutPreset.BottomWide, margin: 5);
        SetAnchorAndMarginPreset(Alerts, LayoutPreset.CenterRight, margin: 10);
        SetAnchorAndMarginPreset(Targeting, LayoutPreset.BottomRight, margin: 5);
        
        ScreenContainer.OnSplitResizeFinished += () =>
            OnChatResized?.Invoke(new Vector2(ScreenContainer.SplitFraction, 0));

        ViewportContainer.OnResized += ResizeActionContainer;
    }

    private void ResizeActionContainer()
    {
        float indent = 20;
        Actions.ActionsContainer.MaxGridWidth = ViewportContainer.Size.X - indent;
    }

    public override ChatBox ChatBox => GetWidget<ChatBox>()!;

    public override void SetChatSize(Vector2 size)
    {
        ScreenContainer.ResizeMode = SplitContainer.SplitResizeMode.RespectChildrenMinSize;
    }

    public override void SetHudVisible(bool visible)
    {
        if (visible)
        {
            if (!_hudHidden || _hudVisibilityState == null)
                return;

            TopBar.Visible = _hudVisibilityState.TopBar;
            ChatContainer.Visible = _hudVisibilityState.ChatContainer;
            Ghost.Visible = _hudVisibilityState.Ghost;
            Inventory.Visible = _hudVisibilityState.Inventory;
            Hotbar.Visible = _hudVisibilityState.Hotbar;
            Targeting.Visible = _hudVisibilityState.Targeting;
            TopLeftContainer.Visible = _hudVisibilityState.TopLeftContainer;
            Alerts.Visible = _hudVisibilityState.Alerts;
            _hudHidden = false;
            return;
        }

        if (_hudHidden)
            return;

        _hudVisibilityState = new HudVisibilityState(
            TopBar.Visible,
            ChatContainer.Visible,
            Ghost.Visible,
            Inventory.Visible,
            Hotbar.Visible,
            Targeting.Visible,
            TopLeftContainer.Visible,
            Alerts.Visible);

        TopBar.Visible = true;
        ChatContainer.Visible = false;
        Ghost.Visible = false;
        Inventory.Visible = false;
        Hotbar.Visible = false;
        Targeting.Visible = false;
        TopLeftContainer.Visible = false;
        Alerts.Visible = false;
        _hudHidden = true;
    }

    public override void AttachDialogueOverlay(Control overlay)
    {
        if (overlay.Parent != ViewportContainer)
        {
            overlay.Orphan();
            ViewportContainer.AddChild(overlay);
            SetAnchorPreset(overlay, LayoutPreset.Wide);
        }

        overlay.SetPositionInParent(1);
    }

    private sealed record HudVisibilityState(
        bool TopBar,
        bool ChatContainer,
        bool Ghost,
        bool Inventory,
        bool Hotbar,
        bool Targeting,
        bool TopLeftContainer,
        bool Alerts);
}
