using System.Linq;
using Content.Client.Message;
using Content.Shared._WH40K.CharacterCreation;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._WH40K.CharacterCreation;

/// <summary>
///     Selection of one of the five introductory HeretekRT classes.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class Wh40kClassesPage : BoxContainer
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    private readonly List<Wh40kCharacterClassPrototype> _classes = new();
    private Wh40kOnboardingDraft? _draft;

    public IReadOnlyList<Wh40kCharacterClassPrototype> Classes => _classes;

    public event Action<Wh40kOnboardingDraft>? OnDraftChanged;

    /// <summary>
    ///     Lets the outer left-hand navigation update its visual selection.
    /// </summary>
    public event Action<Wh40kCharacterClassPrototype>? OnClassSelected;

    public Wh40kClassesPage()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _classes.AddRange(_prototypeManager
            .EnumeratePrototypes<Wh40kCharacterClassPrototype>()
            .OrderBy(characterClass => characterClass.Order));

    }

    public void SetDraft(Wh40kOnboardingDraft draft)
    {
        _draft = draft;

        if (_classes.Count == 0)
            return;

        var selectedId = draft.Profile.Wh40kBuild.ClassId;
        if (selectedId is null || !_classes.Any(characterClass => characterClass.ID == selectedId))
            selectedId = _classes[0].ID;

        SelectClass(selectedId);
    }

    public void ClearDraft()
    {
        _draft = null;
    }

    public void SelectClass(string id)
    {
        if (_draft is null)
            return;

        var characterClass = _classes.FirstOrDefault(candidate => candidate.ID == id);
        if (characterClass is null)
            return;

        var currentBuild = _draft.Profile.Wh40kBuild;
        if (currentBuild.ClassId != characterClass.ID)
        {
            var updatedBuild = currentBuild.Clone();
            updatedBuild.ClassId = characterClass.ID;
            _draft.UpdateProfile(_draft.Profile.WithWh40kCharacterBuild(updatedBuild));
            OnDraftChanged?.Invoke(_draft);
        }

        ClassTitle.Text = Loc.GetString(characterClass.Name);
        ClassDescription.SetMarkup(Loc.GetString(characterClass.Description));
        ClassLoreNote.SetMarkup(Loc.GetString(characterClass.LoreNote));
        ClassModifiers.SetMarkup(string.Join("\n", characterClass.CharacteristicModifiers
            .Where(pair => pair.Value != 0)
            .OrderBy(pair => pair.Key)
            .Select(pair => $"• {Loc.GetString(Wh40kCharacteristicsPage.GetNameLocId(pair.Key))} {pair.Value:+0;-0;0}")));
        ClassActiveAbility.SetMarkup(Loc.GetString(characterClass.ActiveAbility));
        ClassPassiveAbility.SetMarkup(Loc.GetString(characterClass.PassiveAbility));
        OnClassSelected?.Invoke(characterClass);
    }
}
