using System.Linq;
using System.Numerics;
using Content.Client.Humanoid;
using Content.Shared.CCVar;
using Content.Shared._WH40K.CharacterCreation;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Enums;
using Robust.Shared.GameObjects;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._WH40K.CharacterCreation;

[GenerateTypedNameReferences]
public sealed partial class Wh40kAppearancePage : BoxContainer
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private MarkingManager _markingManager = default!;
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private IResourceCache _resourceCache = default!;
    [Dependency] private IEntityManager _entityManager = default!;

    private const int PortraitGridColumns = 5;
    private const float PortraitGridHorizontalSeparation = 10f;
    private const float PortraitAspectRatio = 336f / 260f;
    private const float PortraitChoiceBadgeHeight = 24f;
    private const float PortraitHoverLift = 3f;
    private const int FlavorTextMaxLength = HumanoidCharacterProfile.MaxDescLength;
    private static readonly HashSet<string> HiddenOnboardingSpecies = new(StringComparer.Ordinal)
    {
        "Astartes",
        "Ork",
    };

    private readonly List<SpeciesPrototype> _species = new();
    private readonly List<PortraitPresentation> _portraits = new();
    private Wh40kOnboardingDraft? _draft;
    private ColorSelectorSliders _rgbSkinColorSelector = default!;
    private bool _loadingControls;
    private string? _selectedPortraitId;

    public event Action<Wh40kOnboardingDraft>? OnDraftChanged;
    public event Action<Wh40kPortraitPrototype?>? OnPortraitHoverChanged;
    public bool IsPortraitSectionVisible => Visible && PortraitsSection.Visible;

    public Wh40kAppearancePage()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        ApplyOnboardingControlTheme();

        FlavorNote.Text = Loc.GetString("heretek-onboarding-appearance-flavor-note");

        RgbSkinColorContainer.AddChild(_rgbSkinColorSelector = new ColorSelectorSliders
        {
            SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv,
            HorizontalExpand = true,
        });

        _rgbSkinColorSelector.OnColorChanged += _ => UpdateSkinColorFromControls();
        SkinToneSlider.OnValueChanged += _ => UpdateSkinColorFromControls();
        HeightSlider.OnValueChanged += _ => SetHeight(HeightSlider.Value);
        WidthSlider.OnValueChanged += _ => SetWidth(WidthSlider.Value);

        AgeEdit.OnTextChanged += args =>
        {
            if (!_loadingControls && int.TryParse(args.Text, out var age))
                SetAge(age);
        };

        SpeciesButton.OnItemSelected += args =>
        {
            SpeciesButton.SelectId(args.Id);
            if (!_loadingControls && args.Id >= 0 && args.Id < _species.Count)
                SetSpecies(_species[args.Id].ID);
        };

        SexButton.OnItemSelected += args =>
        {
            SexButton.SelectId(args.Id);
            if (!_loadingControls)
                SetSex((Sex) args.Id);
        };

        PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-male-text"), (int) Gender.Male);
        PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-female-text"), (int) Gender.Female);
        PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-epicene-text"), (int) Gender.Epicene);
        PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-neuter-text"), (int) Gender.Neuter);
        PronounsButton.OnItemSelected += args =>
        {
            PronounsButton.SelectId(args.Id);
            if (!_loadingControls)
                SetGender((Gender) args.Id);
        };

        foreach (var priority in Enum.GetValues<SpawnPriorityPreference>())
        {
            SpawnPriorityButton.AddItem(
                Loc.GetString($"humanoid-profile-editor-preference-spawn-priority-{priority.ToString().ToLower()}"),
                (int) priority);
        }

        SpawnPriorityButton.OnItemSelected += args =>
        {
            SpawnPriorityButton.SelectId(args.Id);
            if (!_loadingControls)
                SetSpawnPriority((SpawnPriorityPreference) args.Id);
        };

        ShowClothesButton.OnToggled += args =>
        {
            if (_loadingControls || _draft is null)
                return;

            _draft.ShowClothes = args.Pressed;
            NotifyDraftChanged();
        };

        HairStylePicker.OnMarkingSelect += marking => SetHairStyle(marking.id);
        HairStylePicker.OnColorChanged += marking => SetHairColor(marking.marking.MarkingColors[0]);
        HairStylePicker.OnSlotRemove += _ => RemoveHair();
        HairStylePicker.OnSlotAdd += AddHair;

        FacialHairPicker.OnMarkingSelect += marking => SetFacialHairStyle(marking.id);
        FacialHairPicker.OnColorChanged += marking => SetFacialHairColor(marking.marking.MarkingColors[0]);
        FacialHairPicker.OnSlotRemove += _ => RemoveFacialHair();
        FacialHairPicker.OnSlotAdd += AddFacialHair;

        EyeColorPicker.OnEyeColorPicked += SetEyeColor;
        AppearanceMarkings.OnMarkingAdded += SetMarkings;
        AppearanceMarkings.OnMarkingRemoved += SetMarkings;
        AppearanceMarkings.OnMarkingColorChange += SetMarkings;
        AppearanceMarkings.OnMarkingRankChange += SetMarkings;
        OnboardingFlavorText.OnFlavorTextChanged += flavorText =>
        {
            if (flavorText.Length > FlavorTextMaxLength)
            {
                OnboardingFlavorText.CFlavorTextInput.TextRope = new Rope.Leaf(flavorText[..FlavorTextMaxLength]);
                return;
            }

            if (!_loadingControls)
                UpdateProfile(profile => profile.WithFlavorText(flavorText));
        };
        OnboardingFlavorText.CFlavorTextInput.OnTextChanged += _ => UpdateFlavorTextCharacterCount();
        UpdateFlavorTextCharacterCount();
        FlavorTextSection.Visible = false;

        PortraitGrid.OnResized += UpdatePortraitCardSizing;

        RefreshSpecies();
        SelectSection(Wh40kAppearanceSection.Portraits);
    }

    private void ApplyOnboardingControlTheme()
    {
        foreach (var option in new[]
                 {
                     SpeciesButton,
                     SexButton,
                     PronounsButton,
                     SpawnPriorityButton,
                 })
        {
            option.StyleBoxOverride = CreateOnboardingFieldStyle("#10110FEE", "#B6975470");
        }

        AgeEdit.StyleBoxOverride = CreateOnboardingFieldStyle("#0D0F0CE8", "#B697547A");
        ShowClothesButton.StyleBoxOverride = CreateOnboardingFieldStyle("#2B2311D0", "#B69754A8");
        ShowClothesButton.Label.FontColorOverride = Color.FromHex("#DFD7C3");

        foreach (var slider in new[] { HeightSlider, WidthSlider, SkinToneSlider })
        {
            slider.BackgroundStyleBoxOverride = CreateOnboardingFieldStyle("#0D0F0CE8", "#B697545C");
            slider.FillStyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#B69754"),
            };
            slider.GrabberStyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#E5C879"),
                BorderColor = Color.FromHex("#4A3B19"),
                BorderThickness = new Thickness(1),
            };
        }
    }

    private static StyleBoxFlat CreateOnboardingFieldStyle(string background, string border)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(background),
            BorderColor = Color.FromHex(border),
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 9,
            ContentMarginRightOverride = 9,
            ContentMarginTopOverride = 6,
            ContentMarginBottomOverride = 6,
        };
    }

    public void SetDraft(Wh40kOnboardingDraft draft)
    {
        if (_portraits.Count == 0)
            CreatePortraitsFromPrototypes();

        _draft = draft;
        if (draft.PortraitId is { } portraitId &&
            !_portraits.Any(portrait => portrait.Id == portraitId))
        {
            draft.ClearPortrait();
        }

        _selectedPortraitId = draft.PortraitId;
        // MarkingPicker queries MarkingManager in this setter. Setting it from XAML happens while the
        // lobby screen is constructed, before MarkingManager has cached prototypes.
        AppearanceMarkings.IgnoreCategories = "Hair,FacialHair";
        _loadingControls = true;
        RefreshAllControls();
        _loadingControls = false;
        UpdatePortraitStyles();
    }

    public void ClearDraft()
    {
        _draft = null;
        _selectedPortraitId = null;
        OnPortraitHoverChanged?.Invoke(null);
        UpdatePortraitStyles();
    }

    public void SelectSection(Wh40kAppearanceSection section)
    {
        PortraitsSection.Visible = section == Wh40kAppearanceSection.Portraits;
        BasicsSection.Visible = section == Wh40kAppearanceSection.Basics;
        HairSection.Visible = section == Wh40kAppearanceSection.Hair;
        EyesSection.Visible = section == Wh40kAppearanceSection.Eyes;
        MarkingsSection.Visible = section == Wh40kAppearanceSection.Markings;
        FlavorTextSection.Visible = section == Wh40kAppearanceSection.FlavorText &&
                                    _cfg.GetCVar(CCVars.FlavorText);
    }

    private void RefreshAllControls()
    {
        if (_draft is null)
            return;

        RefreshSpecies();
        UpdateSexControls();
        PronounsButton.SelectId((int) _draft.Profile.Gender);
        SpawnPriorityButton.SelectId((int) _draft.Profile.SpawnPriority);
        ShowClothesButton.Pressed = _draft.ShowClothes;
        AgeEdit.Text = _draft.Profile.Age.ToString();
        HeightSlider.Value = _draft.Profile.Appearance.Height;
        WidthSlider.Value = _draft.Profile.Appearance.Width;
        UpdateSkinColorControls();
        UpdateEyeControls();
        UpdateHairPickers();
        UpdateMarkings();
        OnboardingFlavorText.CFlavorTextInput.TextRope = new Rope.Leaf(_draft.Profile.FlavorText);
        UpdateFlavorTextCharacterCount();
    }

    private void UpdateFlavorTextCharacterCount()
    {
        OnboardingFlavorTextCount.Text = $"{OnboardingFlavorText.CFlavorTextInput.TextLength} / {FlavorTextMaxLength}";
    }

    private void RefreshSpecies()
    {
        SpeciesButton.Clear();
        _species.Clear();
        _species.AddRange(_prototypeManager
            .EnumeratePrototypes<SpeciesPrototype>()
            .Where(species => species.RoundStart && !HiddenOnboardingSpecies.Contains(species.ID)));

        for (var index = 0; index < _species.Count; index++)
        {
            SpeciesButton.AddItem(Loc.GetString(_species[index].Name), index);
            if (_draft?.Profile.Species == _species[index].ID)
                SpeciesButton.SelectId(index);
        }
    }

    private void UpdateSexControls()
    {
        if (_draft is null)
            return;

        SexButton.Clear();
        IEnumerable<Sex> sexes = _prototypeManager.TryIndex<SpeciesPrototype>(_draft.Profile.Species, out var species)
            ? species.Sexes
            : new[] { Sex.Unsexed };

        foreach (var sex in sexes)
        {
            SexButton.AddItem(Loc.GetString($"humanoid-profile-editor-sex-{sex.ToString().ToLower()}-text"), (int) sex);
        }

        SexButton.SelectId((int) _draft.Profile.Sex);
    }

    private void UpdateSkinColorControls()
    {
        if (_draft is null || !_prototypeManager.TryIndex<SpeciesPrototype>(_draft.Profile.Species, out var species))
            return;

        var skinColor = _draft.Profile.Appearance.SkinColor;
        switch (species.SkinColoration)
        {
            case HumanoidSkinColor.HumanToned:
                SkinToneSlider.Visible = true;
                RgbSkinColorContainer.Visible = false;
                SkinToneSlider.Value = SkinColor.HumanSkinToneFromColor(skinColor);
                break;
            case HumanoidSkinColor.AnimalFur:
                SkinToneSlider.Visible = false;
                RgbSkinColorContainer.Visible = true;
                _rgbSkinColorSelector.Color = SkinColor.ClosestAnimalFurColor(skinColor);
                break;
            case HumanoidSkinColor.Hues:
            case HumanoidSkinColor.TintedHues:
                SkinToneSlider.Visible = false;
                RgbSkinColorContainer.Visible = true;
                _rgbSkinColorSelector.Color = skinColor;
                break;
            case HumanoidSkinColor.VoxFeathers:
                SkinToneSlider.Visible = false;
                RgbSkinColorContainer.Visible = true;
                _rgbSkinColorSelector.Color = SkinColor.ClosestVoxColor(skinColor);
                break;
        }
    }

    private void UpdateEyeControls()
    {
        if (_draft is null)
            return;

        EyeColorPicker.SetData(_draft.Profile.Appearance.EyeColor);
        AppearanceMarkings.SetEyeColor(_draft.Profile.Appearance.EyeColor);
    }

    private void UpdateHairPickers()
    {
        if (_draft is null)
            return;

        var appearance = _draft.Profile.Appearance;
        var hair = appearance.HairStyleId == HairStyles.DefaultHairStyle
            ? new List<Marking>()
            : new List<Marking> { new(appearance.HairStyleId, new List<Color> { appearance.HairColor }) };
        var facialHair = appearance.FacialHairStyleId == HairStyles.DefaultFacialHairStyle
            ? new List<Marking>()
            : new List<Marking> { new(appearance.FacialHairStyleId, new List<Color> { appearance.FacialHairColor }) };

        HairStylePicker.UpdateData(hair, _draft.Profile.Species, 1);
        FacialHairPicker.UpdateData(facialHair, _draft.Profile.Species, 1);
    }

    private void UpdateMarkings()
    {
        if (_draft is null)
            return;

        var profile = _draft.Profile;
        AppearanceMarkings.SetData(
            profile.Appearance.Markings,
            profile.Species,
            profile.Sex,
            profile.Appearance.SkinColor,
            profile.Appearance.EyeColor);

        AppearanceMarkings.HairMarking = profile.Appearance.HairStyleId == HairStyles.DefaultHairStyle
            ? null
            : new Marking(profile.Appearance.HairStyleId, new List<Color> { profile.Appearance.HairColor });
        AppearanceMarkings.FacialHairMarking = profile.Appearance.FacialHairStyleId == HairStyles.DefaultFacialHairStyle
            ? null
            : new Marking(profile.Appearance.FacialHairStyleId, new List<Color> { profile.Appearance.FacialHairColor });
    }

    private void SetAge(int age)
    {
        UpdateProfile(profile => profile.WithAge(age));
    }

    private void SetSpecies(string species)
    {
        if (!_prototypeManager.TryIndex<SpeciesPrototype>(species, out var speciesPrototype))
            return;

        UpdateProfile(profile => NormalizeProfileForSpecies(profile, speciesPrototype, profile.Sex));
        _loadingControls = true;
        UpdateSexControls();
        AgeEdit.Text = _draft!.Profile.Age.ToString();
        UpdateSkinColorControls();
        UpdateHairPickers();
        UpdateMarkings();
        _loadingControls = false;
    }

    private void SetSex(Sex sex)
    {
        UpdateProfile(profile =>
        {
            var updated = profile.WithSex(sex);
            updated = sex switch
            {
                Sex.Male => updated.WithGender(Gender.Male),
                Sex.Female => updated.WithGender(Gender.Female),
                _ => updated.WithGender(Gender.Epicene),
            };

            return _prototypeManager.TryIndex<SpeciesPrototype>(updated.Species, out var species)
                ? NormalizeProfileForSpecies(updated, species, sex)
                : updated;
        });

        _loadingControls = true;
        PronounsButton.SelectId((int) _draft!.Profile.Gender);
        UpdateHairPickers();
        UpdateMarkings();
        _loadingControls = false;
    }

    /// <summary>
    ///     Applies the same profile constraints that the shared character validator applies before save,
    ///     so the onboarding controls and preview never retain values that the selected species cannot use.
    /// </summary>
    private HumanoidCharacterProfile NormalizeProfileForSpecies(
        HumanoidCharacterProfile profile,
        SpeciesPrototype species,
        Sex requestedSex)
    {
        var sex = species.Sexes.Contains(requestedSex)
            ? requestedSex
            : species.Sexes.Count > 0
                ? species.Sexes[0]
                : Sex.Unsexed;

        var appearance = HumanoidCharacterAppearance.EnsureValid(profile.Appearance, species.ID, sex);
        var supportedHair = _markingManager.MarkingsByCategoryAndSpeciesAndSex(
            MarkingCategories.Hair,
            species.ID,
            sex);
        var supportedFacialHair = _markingManager.MarkingsByCategoryAndSpeciesAndSex(
            MarkingCategories.FacialHair,
            species.ID,
            sex);

        if (!supportedHair.ContainsKey(appearance.HairStyleId))
            appearance = appearance.WithHairStyleName(HairStyles.DefaultHairStyle);

        if (!supportedFacialHair.ContainsKey(appearance.FacialHairStyleId))
            appearance = appearance.WithFacialHairStyleName(HairStyles.DefaultFacialHairStyle);

        return profile
            .WithSpecies(species.ID)
            .WithSex(sex)
            .WithAge(Math.Clamp(profile.Age, species.MinAge, species.MaxAge))
            .WithCharacterAppearance(appearance);
    }

    private void SetGender(Gender gender)
    {
        UpdateProfile(profile => profile.WithGender(gender));
    }

    private void SetSpawnPriority(SpawnPriorityPreference priority)
    {
        UpdateProfile(profile => profile.WithSpawnPriorityPreference(priority));
    }

    private void SetHeight(float height)
    {
        if (_loadingControls)
            return;

        UpdateProfile(profile => profile.WithCharacterAppearance(profile.Appearance.WithHeight(height)));
    }

    private void SetWidth(float width)
    {
        if (_loadingControls)
            return;

        UpdateProfile(profile => profile.WithCharacterAppearance(profile.Appearance.WithWidth(width)));
    }

    private void UpdateSkinColorFromControls()
    {
        if (_loadingControls || _draft is null ||
            !_prototypeManager.TryIndex<SpeciesPrototype>(_draft.Profile.Species, out var species))
            return;

        var color = species.SkinColoration switch
        {
            HumanoidSkinColor.HumanToned => SkinColor.HumanSkinTone((int) SkinToneSlider.Value),
            HumanoidSkinColor.AnimalFur => SkinColor.ClosestAnimalFurColor(_rgbSkinColorSelector.Color),
            HumanoidSkinColor.Hues => _rgbSkinColorSelector.Color,
            HumanoidSkinColor.TintedHues => SkinColor.TintedHues(_rgbSkinColorSelector.Color),
            HumanoidSkinColor.VoxFeathers => SkinColor.ClosestVoxColor(_rgbSkinColorSelector.Color),
            _ => _draft.Profile.Appearance.SkinColor,
        };

        UpdateProfile(profile => profile.WithCharacterAppearance(profile.Appearance.WithSkinColor(color)));
        AppearanceMarkings.SetSkinColor(color);
    }

    private void SetHairStyle(string style)
    {
        UpdateProfile(profile => profile.WithCharacterAppearance(profile.Appearance.WithHairStyleName(style)));
        UpdateMarkings();
    }

    private void SetHairColor(Color color)
    {
        UpdateProfile(profile => profile.WithCharacterAppearance(profile.Appearance.WithHairColor(color)));
        UpdateMarkings();
    }

    private void SetFacialHairStyle(string style)
    {
        UpdateProfile(profile => profile.WithCharacterAppearance(profile.Appearance.WithFacialHairStyleName(style)));
        UpdateMarkings();
    }

    private void SetFacialHairColor(Color color)
    {
        UpdateProfile(profile => profile.WithCharacterAppearance(profile.Appearance.WithFacialHairColor(color)));
        UpdateMarkings();
    }

    private void AddHair()
    {
        if (_draft is null)
            return;

        var style = _markingManager.MarkingsByCategoryAndSpecies(MarkingCategories.Hair, _draft.Profile.Species)
            .Keys.FirstOrDefault();
        if (!string.IsNullOrEmpty(style))
            SetHairStyle(style);

        UpdateHairPickers();
    }

    private void AddFacialHair()
    {
        if (_draft is null)
            return;

        var style = _markingManager.MarkingsByCategoryAndSpecies(MarkingCategories.FacialHair, _draft.Profile.Species)
            .Keys.FirstOrDefault();
        if (!string.IsNullOrEmpty(style))
            SetFacialHairStyle(style);

        UpdateHairPickers();
    }

    private void RemoveHair()
    {
        SetHairStyle(HairStyles.DefaultHairStyle);
        UpdateHairPickers();
    }

    private void RemoveFacialHair()
    {
        SetFacialHairStyle(HairStyles.DefaultFacialHairStyle);
        UpdateHairPickers();
    }

    private void SetEyeColor(Color color)
    {
        if (_loadingControls)
            return;

        UpdateProfile(profile => profile.WithCharacterAppearance(profile.Appearance.WithEyeColor(color)));
        AppearanceMarkings.SetEyeColor(color);
    }

    private void SetMarkings(MarkingSet markings)
    {
        UpdateProfile(profile => profile.WithCharacterAppearance(
            profile.Appearance.WithMarkings(markings.GetForwardEnumerator().ToList())));
    }

    private void UpdateProfile(Func<HumanoidCharacterProfile, HumanoidCharacterProfile> update)
    {
        if (_loadingControls || _draft is null)
            return;

        _draft.UpdateProfile(update(_draft.Profile));
        NotifyDraftChanged();
    }

    private void NotifyDraftChanged()
    {
        if (_draft is not null)
            OnDraftChanged?.Invoke(_draft);
    }

    private void CreatePortraitsFromPrototypes()
    {
        var portraitIndexFont = Wh40kOnboardingTypography.Technical(
            _resourceCache,
            Wh40kOnboardingTypography.TechnicalMetaSize);
        var portraitChoiceFont = Wh40kOnboardingTypography.TextBold(
            _resourceCache,
            Wh40kOnboardingTypography.TechnicalSmallSize);

        var displayIndex = 1;
        foreach (var prototype in _prototypeManager
                     .EnumeratePrototypes<Wh40kPortraitPrototype>()
                     .OrderBy(portrait => portrait.Order)
                     .ThenBy(portrait => portrait.ID, StringComparer.Ordinal))
        {
            var id = prototype.ID;
            var cardStyle = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#0D0E0B"),
                BorderColor = Color.FromHex("#B6975466"),
                BorderThickness = new Thickness(1f),
                ContentMarginLeftOverride = 4,
                ContentMarginRightOverride = 4,
                ContentMarginTopOverride = 4,
                ContentMarginBottomOverride = 4,
            };
            var card = new PanelContainer
            {
                SetSize = new Vector2(132f, 170f),
                HorizontalExpand = true,
                RectClipContent = true,
                RectDrawClipMargin = 16,
                PanelOverride = cardStyle,
            };
            var layout = new LayoutContainer
            {
                HorizontalExpand = true,
                VerticalExpand = true,
                InheritChildMeasure = false,
            };
            var button = new TextureButton
            {
                TextureNormal = _entityManager.System<SpriteSystem>().Frame0(prototype.SmallSprite),
                HorizontalExpand = true,
                VerticalExpand = true,
                DefaultCursorShape = Control.CursorShape.Hand,
            };
            var choiceBadgeStyle = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#271F0DF2"),
                BorderColor = Color.Transparent,
                ContentMarginLeftOverride = 7,
                ContentMarginRightOverride = 7,
                ContentMarginTopOverride = 6,
                ContentMarginBottomOverride = 6,
            };
            var choiceBadge = new PanelContainer
            {
                MouseFilter = MouseFilterMode.Ignore,
                SetHeight = PortraitChoiceBadgeHeight,
                PanelOverride = choiceBadgeStyle,
                Modulate = Color.Transparent,
            };
            var choiceContent = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                VerticalExpand = true,
                SeparationOverride = 6,
                MouseFilter = MouseFilterMode.Ignore,
            };
            var selectedMarker = new TextureRect
            {
                TexturePath = "/Textures/Interface/NavMap/beveled_star.png",
                SetSize = new Vector2(12f, 12f),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                CanShrink = true,
                ModulateSelfOverride = Color.FromHex("#E5C879"),
                VerticalAlignment = VAlignment.Center,
                MouseFilter = MouseFilterMode.Ignore,
                Visible = false,
            };
            var choiceLabel = new Label
            {
                FontOverride = portraitChoiceFont,
                HorizontalExpand = true,
                VerticalExpand = true,
                HorizontalAlignment = HAlignment.Left,
                VerticalAlignment = VAlignment.Center,
                VAlign = Label.VAlignMode.Center,
            };
            choiceContent.AddChild(selectedMarker);
            choiceContent.AddChild(choiceLabel);
            choiceBadge.AddChild(choiceContent);

            var numberBadge = new PanelContainer
            {
                SetSize = new Vector2(19f, 14f),
                MouseFilter = MouseFilterMode.Ignore,
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = Color.FromHex("#050605BF"),
                    BorderColor = Color.Transparent,
                    BorderThickness = new Thickness(0f),
                    ContentMarginLeftOverride = 0,
                    ContentMarginRightOverride = 0,
                    ContentMarginTopOverride = 0,
                    ContentMarginBottomOverride = 0,
                },
            };
            numberBadge.AddChild(new Label
            {
                Text = displayIndex.ToString("D2"),
                FontOverride = portraitIndexFont,
                FontColorOverride = Color.FromHex("#DFD7C3C7"),
                HorizontalExpand = true,
                VerticalExpand = true,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                Align = Label.AlignMode.Center,
                VAlign = Label.VAlignMode.Center,
            });

            layout.AddChild(button);
            LayoutContainer.SetAnchorPreset(button, LayoutContainer.LayoutPreset.Wide);
            LayoutContainer.SetGrowHorizontal(button, LayoutContainer.GrowDirection.Constrain);
            LayoutContainer.SetGrowVertical(button, LayoutContainer.GrowDirection.Constrain);
            layout.AddChild(choiceBadge);
            LayoutContainer.SetAnchorAndMarginPreset(choiceBadge, LayoutContainer.LayoutPreset.BottomWide);
            LayoutContainer.SetGrowHorizontal(choiceBadge, LayoutContainer.GrowDirection.Constrain);
            LayoutContainer.SetGrowVertical(choiceBadge, LayoutContainer.GrowDirection.Constrain);
            layout.AddChild(numberBadge);
            LayoutContainer.SetAnchorAndMarginPreset(numberBadge, LayoutContainer.LayoutPreset.TopLeft, margin: 1);
            LayoutContainer.SetGrowHorizontal(numberBadge, LayoutContainer.GrowDirection.Constrain);
            LayoutContainer.SetGrowVertical(numberBadge, LayoutContainer.GrowDirection.Constrain);
            card.AddChild(layout);

            var portrait = new PortraitPresentation(
                prototype,
                displayIndex,
                card,
                button,
                choiceBadge,
                selectedMarker,
                choiceLabel,
                cardStyle,
                choiceBadgeStyle);
            _portraits.Add(portrait);

            button.OnMouseEntered += _ =>
            {
                portrait.Hovered = true;
                portrait.VisualDirty = true;
                OnPortraitHoverChanged?.Invoke(portrait.Prototype);
            };
            button.OnMouseExited += _ =>
            {
                portrait.Hovered = false;
                portrait.VisualDirty = true;
                OnPortraitHoverChanged?.Invoke(
                    _portraits.FirstOrDefault(candidate => candidate.Hovered)?.Prototype);
            };
            button.OnPressed += _ => SelectPortrait(portrait);

            PortraitGrid.AddChild(card);
            displayIndex++;
        }

        UpdatePortraitStyles();
    }

    /// <summary>
    /// Uses five fractional portrait columns. The old fixed-width
    /// cards gave the grid a 700px minimum and let it escape the onboarding frame.
    /// The grid now owns their width and this preserves the original portrait ratio.
    /// </summary>
    private void UpdatePortraitCardSizing()
    {
        var gridWidth = PortraitGrid.Width;
        if (gridWidth <= 0f)
            return;

        var cardWidth = MathF.Max(
            1f,
            (gridWidth - PortraitGridHorizontalSeparation * (PortraitGridColumns - 1)) / PortraitGridColumns);
        var cardHeight = MathF.Round(cardWidth * PortraitAspectRatio);

        foreach (var portrait in _portraits)
        {
            if (MathF.Abs(portrait.Card.SetWidth - cardWidth) < 0.5f &&
                MathF.Abs(portrait.Card.SetHeight - cardHeight) < 0.5f)
            {
                continue;
            }

            portrait.Card.SetSize = new Vector2(cardWidth, cardHeight);
        }
    }

    private void SelectPortrait(PortraitPresentation portrait)
    {
        if (_draft is null)
            return;

        if (_selectedPortraitId == portrait.Id)
        {
            _selectedPortraitId = null;
            _draft.ClearPortrait();
        }
        else
        {
            _selectedPortraitId = portrait.Id;
            _draft.SelectPortrait(portrait.Id);
        }

        UpdatePortraitStyles();
        OnDraftChanged?.Invoke(_draft);
    }

    private void UpdatePortraitStyles()
    {
        foreach (var portrait in _portraits)
        {
            var selected = _draft is not null && _selectedPortraitId == portrait.Id;
            if (portrait.Selected != selected)
            {
                portrait.Selected = selected;
                portrait.VisualDirty = true;
            }

            portrait.ChoiceLabel.Text = Loc.GetString(selected
                ? "heretek-onboarding-portrait-selected-badge"
                : "heretek-onboarding-portrait-choice");
            portrait.ChoiceLabel.FontColorOverride = selected ? Color.FromHex("#F5E1A0") : Color.FromHex("#DFD7C3");
            portrait.SelectedMarker.Visible = selected;
        }

        var selectedPortrait = _portraits.FirstOrDefault(portrait => portrait.Selected);
        SelectedPortraitLabel.Text = selectedPortrait is not null
            ? Loc.GetString(
                "heretek-onboarding-portrait-selected-number",
                ("number", selectedPortrait.DisplayIndex.ToString("D2")))
            : Loc.GetString("heretek-onboarding-portrait-select-prompt");
    }

    public void UpdatePortraitVisualEffects(float deltaSeconds, bool reducedMotion)
    {
        if (!IsPortraitSectionVisible)
            return;

        foreach (var portrait in _portraits)
        {
            var hovered = portrait.Button.IsHovered;
            if (portrait.Hovered != hovered)
            {
                portrait.Hovered = hovered;
                portrait.VisualDirty = true;
            }

            var previous = portrait.HoverAmount;
            var target = hovered || portrait.Selected ? 1f : 0f;
            portrait.HoverAmount = ApproachPresentation(previous, target, deltaSeconds, reducedMotion);
            if (portrait.HoverAmount == previous && !portrait.VisualDirty)
                continue;

            ApplyPortraitVisual(portrait);
        }
    }

    private static void ApplyPortraitVisual(PortraitPresentation portrait)
    {
        var emphasis = portrait.HoverAmount;
        var choiceAmount = portrait.Selected ? 1f : emphasis;

        portrait.CardStyle.BackgroundColor = LerpColor(
            Color.FromHex("#0D0E0B"),
            Color.FromHex("#483817"),
            emphasis);
        portrait.CardStyle.BorderColor = LerpColor(
            Color.FromHex("#B6975466"),
            Color.FromHex("#E5C879"),
            emphasis);
        portrait.Card.Margin = new Thickness(
            0f,
            -PortraitHoverLift * emphasis,
            0f,
            PortraitHoverLift * emphasis);

        portrait.ChoiceBadgeStyle.BackgroundColor = LerpColor(
            Color.FromHex("#080907E0"),
            Color.FromHex("#271F0DF2"),
            choiceAmount);
        portrait.ChoiceBadge.Modulate = Color.White.WithAlpha(choiceAmount);
        var badgeOffset = 10f * (1f - choiceAmount);
        LayoutContainer.SetMarginTop(
            portrait.ChoiceBadge,
            -PortraitChoiceBadgeHeight + badgeOffset);
        LayoutContainer.SetMarginBottom(portrait.ChoiceBadge, badgeOffset);
        portrait.VisualDirty = false;
    }

    private static float ApproachPresentation(float value, float target, float deltaSeconds, bool reducedMotion)
    {
        if (reducedMotion)
            return target;

        var speed = Math.Clamp(deltaSeconds / 0.16f, 0f, 1f);
        var approached = value + (target - value) * speed;
        return MathF.Abs(approached - target) <= 0.002f ? target : approached;
    }

    private static Color LerpColor(Color from, Color to, float progress)
    {
        progress = Math.Clamp(progress, 0f, 1f);
        return new Color(
            from.R + (to.R - from.R) * progress,
            from.G + (to.G - from.G) * progress,
            from.B + (to.B - from.B) * progress,
            from.A + (to.A - from.A) * progress);
    }

    private sealed class PortraitPresentation
    {
        public Wh40kPortraitPrototype Prototype { get; }
        public string Id => Prototype.ID;
        public int DisplayIndex { get; }
        public PanelContainer Card { get; }
        public TextureButton Button { get; }
        public PanelContainer ChoiceBadge { get; }
        public TextureRect SelectedMarker { get; }
        public Label ChoiceLabel { get; }
        public StyleBoxFlat CardStyle { get; }
        public StyleBoxFlat ChoiceBadgeStyle { get; }
        public bool Hovered { get; set; }
        public bool Selected { get; set; }
        public float HoverAmount { get; set; }
        public bool VisualDirty { get; set; } = true;

        public PortraitPresentation(
            Wh40kPortraitPrototype prototype,
            int displayIndex,
            PanelContainer card,
            TextureButton button,
            PanelContainer choiceBadge,
            TextureRect selectedMarker,
            Label choiceLabel,
            StyleBoxFlat cardStyle,
            StyleBoxFlat choiceBadgeStyle)
        {
            Prototype = prototype;
            DisplayIndex = displayIndex;
            Card = card;
            Button = button;
            ChoiceBadge = choiceBadge;
            SelectedMarker = selectedMarker;
            ChoiceLabel = choiceLabel;
            CardStyle = cardStyle;
            ChoiceBadgeStyle = choiceBadgeStyle;
        }
    }
}

public enum Wh40kAppearanceSection : byte
{
    Portraits,
    Basics,
    Hair,
    Eyes,
    Markings,
    FlavorText,
}
