using System.Linq;
using Content.Client.Message;
using Content.Shared._WH40K.CharacterCreation;
using Content.Shared.Preferences;
using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._WH40K.CharacterCreation;

/// <summary>
/// Read-only summary of the first-character draft. Persistence remains outside this control.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class Wh40kResultPage : BoxContainer
{
    [Dependency] private IPrototypeManager _prototypes = default!;
    [Dependency] private IEntityManager _entityManager = default!;

    private static readonly SpriteSpecifier DiceSprite = new SpriteSpecifier.Rsi(
        new ResPath("/Textures/Objects/Fun/dice.rsi"),
        "d6_6");

    private Wh40kOnboardingDraft? _draft;
    private StyleBoxFlat _generateNameButtonFrameStyle = default!;
    private bool _settingName;

    public event Action<Wh40kOnboardingDraft>? OnDraftChanged;

    public Wh40kResultPage()
    {
        RobustXamlLoader.Load(this);

        NameEdit.StyleBoxOverride = CreateFieldStyle("#0D0F0CE8", "#B697547A");
        _generateNameButtonFrameStyle = CreateFieldStyle("#17140DDE", "#8D6E35A8");
        GenerateNameButtonFrame.PanelOverride = _generateNameButtonFrameStyle;
        IoCManager.InjectDependencies(this);

        GenerateNameButton.OnMouseEntered += _ => SetGenerateNameButtonFrameStyle("#3A2D14EE", "#E5C879");
        GenerateNameButton.OnMouseExited += _ => SetGenerateNameButtonFrameStyle("#17140DDE", "#8D6E35A8");
        GenerateNameButton.OnButtonDown += _ => SetGenerateNameButtonFrameStyle("#141007EE", "#A9823C");
        GenerateNameButton.OnButtonUp += _ => SetGenerateNameButtonFrameStyle(
            GenerateNameButton.IsHovered ? "#3A2D14EE" : "#17140DDE",
            GenerateNameButton.IsHovered ? "#E5C879" : "#8D6E35A8");
        GenerateNameButton.OnPressed += _ =>
        {
            if (_draft is null)
                return;

            NameEdit.Text = HumanoidCharacterProfile.GetName(_draft.Profile.Species, _draft.Profile.Gender);
            NameEdit.CursorPosition = 0;
        };
        NameEdit.OnTextChanged += args =>
        {
            if (_settingName || _draft is null)
                return;

            _draft.UpdateProfile(_draft.Profile.WithName(args.Text));
            OnDraftChanged?.Invoke(_draft);
        };
    }

    public void SetDraft(Wh40kOnboardingDraft draft)
    {
        GenerateNameButton.TextureNormal ??= _entityManager.System<SpriteSystem>().Frame0(DiceSprite);
        _draft = draft;
        RefreshForDraft();
    }

    public void ClearDraft()
    {
        _draft = null;
        _settingName = true;
        NameEdit.Text = string.Empty;
        NameEdit.CursorPosition = 0;
        _settingName = false;
        ResultHomeworld.Text = string.Empty;
        ResultOrigin.Text = string.Empty;
        ResultClass.Text = string.Empty;
        ResultTraits.Text = string.Empty;
        ResultMeleePoints.Text = string.Empty;
        ResultRangedPoints.Text = string.Empty;
        ResultEndurancePoints.Text = string.Empty;
        ResultIntelligencePoints.Text = string.Empty;
        ResultAgilityPoints.Text = string.Empty;
        ResultActiveAbility.SetMarkup(string.Empty);
        ResultPassiveAbility.SetMarkup(string.Empty);
    }

    public void RefreshForDraft()
    {
        if (_draft is null)
            return;

        var build = _draft.Profile.Wh40kBuild;
        var homeworld = build.HomeworldId is not null &&
                        _prototypes.TryIndex<Wh40kHomeworldPrototype>(build.HomeworldId, out var homeworldPrototype)
            ? homeworldPrototype
            : null;
        var origin = build.OriginId is not null &&
                     _prototypes.TryIndex<Wh40kOriginPrototype>(build.OriginId, out var originPrototype)
            ? originPrototype
            : null;
        var characterClass = build.ClassId is not null &&
                             _prototypes.TryIndex<Wh40kCharacterClassPrototype>(build.ClassId, out var classPrototype)
            ? classPrototype
            : null;
        ResultHomeworld.Text = GetName<Wh40kHomeworldPrototype>(build.HomeworldId);
        ResultOrigin.Text = GetName<Wh40kOriginPrototype>(build.OriginId);
        ResultClass.Text = GetName<Wh40kCharacterClassPrototype>(build.ClassId);

        var traits = _draft.Profile.TraitPreferences
            .Select(id => _prototypes.TryIndex<TraitPrototype>(id, out var trait) ? trait : null)
            .Where(trait => trait is not null)
            .OrderBy(trait => Loc.GetString(trait!.Name))
            .Select(trait => Loc.GetString(trait!.Name))
            .ToList();
        ResultTraits.Text = traits.Count == 0
            ? Loc.GetString("heretek-onboarding-result-no-traits")
            : string.Join(", ", traits);

        _settingName = true;
        NameEdit.Text = _draft.Profile.Name;
        NameEdit.CursorPosition = 0;
        _settingName = false;

        ResultMeleePoints.Text = build.GetCharacteristicTotal(Wh40kCharacteristic.Melee, homeworld, origin, characterClass).ToString();
        ResultRangedPoints.Text = build.GetCharacteristicTotal(Wh40kCharacteristic.Ranged, homeworld, origin, characterClass).ToString();
        ResultEndurancePoints.Text = build.GetCharacteristicTotal(Wh40kCharacteristic.Endurance, homeworld, origin, characterClass).ToString();
        ResultIntelligencePoints.Text = build.GetCharacteristicTotal(Wh40kCharacteristic.Intelligence, homeworld, origin, characterClass).ToString();
        ResultAgilityPoints.Text = build.GetCharacteristicTotal(Wh40kCharacteristic.Agility, homeworld, origin, characterClass).ToString();

        ResultActiveAbility.SetMarkup(characterClass is null
            ? string.Empty
            : Loc.GetString(characterClass.ActiveAbility));
        ResultPassiveAbility.SetMarkup(characterClass is null
            ? string.Empty
            : Loc.GetString(characterClass.PassiveAbility));
    }

    private static StyleBoxFlat CreateFieldStyle(string background, string border)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex(background),
            BorderColor = Color.FromHex(border),
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 10,
            ContentMarginRightOverride = 10,
            ContentMarginTopOverride = 7,
            ContentMarginBottomOverride = 7,
        };
    }

    private void SetGenerateNameButtonFrameStyle(string background, string border)
    {
        _generateNameButtonFrameStyle.BackgroundColor = Color.FromHex(background);
        _generateNameButtonFrameStyle.BorderColor = Color.FromHex(border);
    }

    private string GetName<T>(string? id) where T : class, IPrototype
    {
        return id != null && _prototypes.TryIndex<T>(id, out var prototype)
            ? Loc.GetString(GetPrototypeName(prototype))
            : Loc.GetString("heretek-onboarding-result-not-selected");
    }

    private static string GetPrototypeName(IPrototype prototype)
    {
        return prototype switch
        {
            Wh40kHomeworldPrototype homeworld => homeworld.Name,
            Wh40kOriginPrototype origin => origin.Name,
            Wh40kCharacterClassPrototype characterClass => characterClass.Name,
            _ => string.Empty,
        };
    }
}
