using System.Linq;
using Content.Client.Message;
using Content.Shared.Preferences;
using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client._WH40K.CharacterCreation;

/// <summary>
///     Reuses the actual SS14 physical traits for the introductory character.
///     Positive costs spend the Physical category budget, while negative costs refund it.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class Wh40kTraitsPage : BoxContainer
{
    private const string PhysicalCategory = "Physical";

    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IResourceCache _resourceCache = default!;

    private readonly List<TraitPrototype> _positiveTraits = new();
    private readonly List<TraitPrototype> _negativeTraits = new();
    private Wh40kOnboardingDraft? _draft;
    private TraitPrototype? _selectedTrait;

    public IReadOnlyList<TraitPrototype> PositiveTraits => _positiveTraits;
    public IReadOnlyList<TraitPrototype> NegativeTraits => _negativeTraits;
    public string? SelectedTraitId => _selectedTrait?.ID;
    public int AvailableTraitPoints => TryGetPhysicalTraitBudget(out var available, out _) ? available : 0;

    public event Action<TraitPrototype>? OnTraitSelected;
    public event Action<Wh40kOnboardingDraft>? OnDraftChanged;

    public Wh40kTraitsPage()
    {
        RobustXamlLoader.Load(this);

        TraitActionButton.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#5B461AE8"),
            BorderColor = Color.FromHex("#E5C879E6"),
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 12,
            ContentMarginRightOverride = 12,
            ContentMarginTopOverride = 7,
            ContentMarginBottomOverride = 7,
        };
        TraitActionButton.Label.FontColorOverride = Color.FromHex("#FFF4D3");
        IoCManager.InjectDependencies(this);
        TraitActionButton.Label.FontOverride = Wh40kOnboardingTypography.Text(
            _resourceCache,
            Wh40kOnboardingTypography.BodySmallSize);

        foreach (var trait in _prototypeManager.EnumeratePrototypes<TraitPrototype>())
        {
            if (trait.Category?.Id != PhysicalCategory || trait.Cost == 0)
                continue;

            (trait.Cost > 0 ? _positiveTraits : _negativeTraits).Add(trait);
        }

        _positiveTraits.Sort(CompareTraits);
        _negativeTraits.Sort(CompareTraits);
        TraitActionButton.OnPressed += _ => ToggleSelectedTrait();
    }

    public void SetDraft(Wh40kOnboardingDraft draft)
    {
        _draft = draft;
        RefreshForDraft();
    }

    public void ClearDraft()
    {
        _draft = null;
        _selectedTrait = null;
        TraitsBudget.Text = string.Empty;
        TraitKind.Text = string.Empty;
        TraitTitle.Text = string.Empty;
        TraitDescription.SetMarkup(string.Empty);
        TraitEffect.SetMarkup(string.Empty);
        TraitAvailability.SetMarkup(string.Empty);
        SelectedTraits.SetMarkup(string.Empty);
        TraitActionButton.Disabled = true;
    }

    public void RefreshForDraft()
    {
        if (_draft is null)
            return;

        var removedRestrictedTraits = RemoveSpeciesRestrictedTraits();
        var allTraits = _positiveTraits.Concat(_negativeTraits);
        if (_selectedTrait is null || !allTraits.Any(trait => trait.ID == _selectedTrait.ID))
            _selectedTrait = _positiveTraits.FirstOrDefault() ?? _negativeTraits.FirstOrDefault();

        RefreshSelectedTrait();

        if (removedRestrictedTraits)
            OnDraftChanged?.Invoke(_draft);
    }

    public void SelectTrait(string id)
    {
        var trait = _positiveTraits.Concat(_negativeTraits).FirstOrDefault(candidate => candidate.ID == id);
        if (trait is null)
            return;

        _selectedTrait = trait;
        RefreshSelectedTrait();
    }

    public bool IsTraitSelected(TraitPrototype trait)
    {
        return _draft?.Profile.TraitPreferences.Contains(trait.ID) == true;
    }

    public bool CanSelectTrait(TraitPrototype trait)
    {
        var state = GetTraitSelectionState(trait);
        return state is TraitSelectionState.Selected or TraitSelectionState.Available;
    }

    private TraitSelectionState GetTraitSelectionState(TraitPrototype trait)
    {
        if (_draft is null)
            return TraitSelectionState.NoDraft;

        if (IsTraitSelected(trait))
            return TraitSelectionState.Selected;

        var profile = _draft.Profile;
        if (trait.SpeciesBlacklist.Contains(profile.Species))
            return TraitSelectionState.Incompatible;

        foreach (var selectedId in profile.TraitPreferences)
        {
            if (!_prototypeManager.TryIndex<TraitPrototype>(selectedId, out var selectedTrait))
                continue;

            if (trait.MutuallyExclusiveTraits.Contains(selectedId) || selectedTrait.MutuallyExclusiveTraits.Contains(trait.ID))
                return TraitSelectionState.Incompatible;
        }

        if (trait.Category is null ||
            !_prototypeManager.TryIndex<TraitCategoryPrototype>(trait.Category, out var category) ||
            category.MaxTraitPoints is null || category.MaxTraitPoints < 0)
        {
            return TraitSelectionState.Available;
        }

        var currentPoints = profile.TraitPreferences
            .Select(id => _prototypeManager.TryIndex<TraitPrototype>(id, out var selected) ? selected : null)
            .Where(selected => selected?.Category == trait.Category)
            .Sum(selected => selected!.Cost);
        return currentPoints + trait.Cost <= category.MaxTraitPoints
            ? TraitSelectionState.Available
            : TraitSelectionState.InsufficientPoints;
    }

    private void ToggleSelectedTrait()
    {
        if (_draft is null || _selectedTrait is null)
            return;

        var profile = _draft.Profile;
        if (IsTraitSelected(_selectedTrait))
        {
            _draft.UpdateProfile(profile.WithoutTraitPreference(_selectedTrait.ID, _prototypeManager));
        }
        else
        {
            if (!CanSelectTrait(_selectedTrait))
                return;

            _draft.UpdateProfile(profile.WithTraitPreference(_selectedTrait.ID, _prototypeManager));
        }

        RefreshSelectedTrait(notifySelection: false);
        OnDraftChanged?.Invoke(_draft);
    }

    private void RefreshSelectedTrait(bool notifySelection = true)
    {
        if (_draft is null || _selectedTrait is null)
            return;

        var selected = IsTraitSelected(_selectedTrait);
        var positive = _selectedTrait.Cost > 0;
        TraitKind.Text = Loc.GetString(positive
            ? "heretek-onboarding-traits-positive-title"
            : "heretek-onboarding-traits-negative-title");
        TraitTitle.Text = Loc.GetString(_selectedTrait.Name);
        TraitDescription.SetMarkup(_selectedTrait.Description is { } description
            ? Loc.GetString(description)
            : Loc.GetString("heretek-onboarding-traits-no-description"));
        TraitEffect.SetMarkup(Loc.GetString(positive
            ? "heretek-onboarding-traits-positive-effect"
            : "heretek-onboarding-traits-negative-effect",
            ("points", Math.Abs(_selectedTrait.Cost))));

        var selectionState = GetTraitSelectionState(_selectedTrait);
        TraitAvailability.SetMarkup(selectionState switch
        {
            TraitSelectionState.Selected => Loc.GetString("heretek-onboarding-traits-selected"),
            TraitSelectionState.Available => Loc.GetString("heretek-onboarding-traits-available"),
            TraitSelectionState.Incompatible => Loc.GetString("heretek-onboarding-traits-incompatible"),
            TraitSelectionState.InsufficientPoints => Loc.GetString("heretek-onboarding-traits-insufficient-points"),
            _ => Loc.GetString("heretek-onboarding-traits-unavailable"),
        });
        TraitActionButton.Text = Loc.GetString(selected
            ? "heretek-onboarding-traits-remove"
            : "heretek-onboarding-traits-select");
        TraitActionButton.Disabled = selectionState != TraitSelectionState.Selected &&
                                     selectionState != TraitSelectionState.Available;

        RefreshBudget();
        RefreshSelectedTraits();
        if (notifySelection)
            OnTraitSelected?.Invoke(_selectedTrait);
    }

    private void RefreshBudget()
    {
        if (!TryGetPhysicalTraitBudget(out var available, out var maximum))
        {
            TraitsBudget.Text = string.Empty;
            return;
        }

        TraitsBudget.Text = Loc.GetString(
            "heretek-onboarding-traits-budget",
            ("available", available),
            ("maximum", maximum));
    }

    private bool TryGetPhysicalTraitBudget(out int available, out int maximum)
    {
        available = 0;
        maximum = 0;
        if (_draft is null ||
            !_prototypeManager.TryIndex<TraitCategoryPrototype>(PhysicalCategory, out var category) ||
            category.MaxTraitPoints is null || category.MaxTraitPoints < 0)
        {
            return false;
        }

        maximum = category.MaxTraitPoints.Value;
        var spent = _draft.Profile.TraitPreferences
            .Select(id => _prototypeManager.TryIndex<TraitPrototype>(id, out var trait) ? trait : null)
            .Where(trait => trait?.Category?.Id == PhysicalCategory)
            .Sum(trait => trait!.Cost);
        available = maximum - spent;
        return true;
    }

    private void RefreshSelectedTraits()
    {
        if (_draft is null)
            return;

        var traits = _draft.Profile.TraitPreferences
            .Select(id => _prototypeManager.TryIndex<TraitPrototype>(id, out var trait) ? trait : null)
            .Where(trait => trait?.Category?.Id == PhysicalCategory)
            .OrderBy(trait => Loc.GetString(trait!.Name))
            .Select(trait => Loc.GetString(trait!.Name))
            .ToList();
        SelectedTraits.SetMarkup(traits.Count > 0
            ? string.Join(", ", traits)
            : Loc.GetString("heretek-onboarding-traits-none-selected"));
    }

    private bool RemoveSpeciesRestrictedTraits()
    {
        if (_draft is null)
            return false;

        var profile = _draft.Profile;
        var restricted = profile.TraitPreferences
            .Where(id => _prototypeManager.TryIndex<TraitPrototype>(id, out var trait) && trait.SpeciesBlacklist.Contains(profile.Species))
            .ToList();
        if (restricted.Count == 0)
            return false;

        foreach (var traitId in restricted)
        {
            profile = profile.WithoutTraitPreference(traitId, _prototypeManager);
        }

        _draft.UpdateProfile(profile);
        return true;
    }

    private static int CompareTraits(TraitPrototype left, TraitPrototype right)
    {
        return string.Compare(Loc.GetString(left.Name), Loc.GetString(right.Name), StringComparison.CurrentCulture);
    }

    private enum TraitSelectionState : byte
    {
        NoDraft,
        Selected,
        Available,
        Incompatible,
        InsufficientPoints,
    }
}
