using Content.Client.Message;
using Content.Shared._WH40K.CharacterCreation;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client._WH40K.CharacterCreation;

[GenerateTypedNameReferences]
public sealed partial class Wh40kCharacteristicsPage : BoxContainer
{
    private static readonly Wh40kCharacteristic[] CharacteristicValues = Enum.GetValues<Wh40kCharacteristic>();

    [Dependency] private IPrototypeManager _prototypeManager = default!;

    private Wh40kOnboardingDraft? _draft;
    private Wh40kCharacteristic _selectedCharacteristic = Wh40kCharacteristic.Melee;

    public IReadOnlyList<Wh40kCharacteristic> Characteristics => CharacteristicValues;
    public Wh40kCharacteristic SelectedCharacteristic => _selectedCharacteristic;
    public int RemainingPoints => Wh40kCharacterBuild.MaximumAttributePoints - GetSpentPoints();

    public event Action<Wh40kCharacteristic>? OnCharacteristicSelected;
    public event Action<Wh40kOnboardingDraft>? OnDraftChanged;

    public Wh40kCharacteristicsPage()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        DecreaseButton.StyleBoxOverride = CreateStepStyle(Color.FromHex("#12130FDB"));
        IncreaseButton.StyleBoxOverride = CreateStepStyle(Color.FromHex("#2B2311D0"));
        DecreaseButton.OnPressed += _ => AdjustSelectedCharacteristic(-1);
        IncreaseButton.OnPressed += _ => AdjustSelectedCharacteristic(1);
    }

    public void SetDraft(Wh40kOnboardingDraft draft)
    {
        _draft = draft;
        SelectCharacteristic(_selectedCharacteristic);
    }

    public void ClearDraft()
    {
        _draft = null;
    }

    public void RefreshForDraft()
    {
        if (_draft is not null)
            RefreshCard();
    }

    public int GetCharacteristicTotal(Wh40kCharacteristic characteristic)
    {
        return _draft is null
            ? 0
            : _draft.Profile.Wh40kBuild.GetCharacteristicTotal(
                characteristic,
                GetSelectedHomeworld(),
                GetSelectedOrigin(),
                GetSelectedClass());
    }

    public void SelectCharacteristic(Wh40kCharacteristic characteristic)
    {
        if (!CharacteristicValues.Contains(characteristic))
            return;

        _selectedCharacteristic = characteristic;
        RefreshCard();
        OnCharacteristicSelected?.Invoke(characteristic);
    }

    public static string GetNameLocId(Wh40kCharacteristic characteristic)
    {
        return characteristic switch
        {
            Wh40kCharacteristic.Melee => "heretek-characteristic-melee-name",
            Wh40kCharacteristic.Ranged => "heretek-characteristic-ranged-name",
            Wh40kCharacteristic.Endurance => "heretek-characteristic-endurance-name",
            Wh40kCharacteristic.Intelligence => "heretek-characteristic-intelligence-name",
            Wh40kCharacteristic.Agility => "heretek-characteristic-agility-name",
            _ => throw new ArgumentOutOfRangeException(nameof(characteristic), characteristic, null),
        };
    }

    public static string GetDescriptionLocId(Wh40kCharacteristic characteristic)
    {
        return characteristic switch
        {
            Wh40kCharacteristic.Melee => "heretek-characteristic-melee-description",
            Wh40kCharacteristic.Ranged => "heretek-characteristic-ranged-description",
            Wh40kCharacteristic.Endurance => "heretek-characteristic-endurance-description",
            Wh40kCharacteristic.Intelligence => "heretek-characteristic-intelligence-description",
            Wh40kCharacteristic.Agility => "heretek-characteristic-agility-description",
            _ => throw new ArgumentOutOfRangeException(nameof(characteristic), characteristic, null),
        };
    }

    public static string GetNavigationDescriptionLocId(Wh40kCharacteristic characteristic)
    {
        return characteristic switch
        {
            Wh40kCharacteristic.Melee => "heretek-characteristic-melee-navigation-description",
            Wh40kCharacteristic.Ranged => "heretek-characteristic-ranged-navigation-description",
            Wh40kCharacteristic.Endurance => "heretek-characteristic-endurance-navigation-description",
            Wh40kCharacteristic.Intelligence => "heretek-characteristic-intelligence-navigation-description",
            Wh40kCharacteristic.Agility => "heretek-characteristic-agility-navigation-description",
            _ => throw new ArgumentOutOfRangeException(nameof(characteristic), characteristic, null),
        };
    }

    private static string GetEffectLocId(Wh40kCharacteristic characteristic)
    {
        return characteristic switch
        {
            Wh40kCharacteristic.Melee => "heretek-characteristic-melee-effect",
            Wh40kCharacteristic.Ranged => "heretek-characteristic-ranged-effect",
            Wh40kCharacteristic.Endurance => "heretek-characteristic-endurance-effect",
            Wh40kCharacteristic.Intelligence => "heretek-characteristic-intelligence-effect",
            Wh40kCharacteristic.Agility => "heretek-characteristic-agility-effect",
            _ => throw new ArgumentOutOfRangeException(nameof(characteristic), characteristic, null),
        };
    }

    private void AdjustSelectedCharacteristic(int delta)
    {
        if (_draft is null || delta == 0)
            return;

        var build = _draft.Profile.Wh40kBuild.Clone();
        var current = build.CharacteristicPoints.GetValueOrDefault(_selectedCharacteristic);
        if (delta > 0 && RemainingPoints <= 0)
            return;
        if (delta < 0 && current <= 0)
            return;

        var updated = Math.Clamp(current + delta, 0, Wh40kCharacterBuild.MaximumAttributePoints);
        if (updated == 0)
            build.CharacteristicPoints.Remove(_selectedCharacteristic);
        else
            build.CharacteristicPoints[_selectedCharacteristic] = updated;

        _draft.UpdateProfile(_draft.Profile.WithWh40kCharacterBuild(build.Validated()));
        RefreshCard();
        OnDraftChanged?.Invoke(_draft);
    }

    private int GetSpentPoints()
    {
        if (_draft is null)
            return 0;

        var total = 0;
        foreach (var value in _draft.Profile.Wh40kBuild.CharacteristicPoints.Values)
            total += Math.Clamp(value, 0, Wh40kCharacterBuild.MaximumAttributePoints);

        return Math.Min(total, Wh40kCharacterBuild.MaximumAttributePoints);
    }

    private void RefreshCard()
    {
        var selectedIndex = Array.IndexOf(CharacteristicValues, _selectedCharacteristic) + 1;
        var points = _draft?.Profile.Wh40kBuild.CharacteristicPoints.GetValueOrDefault(_selectedCharacteristic) ?? 0;
        var modifier = (GetSelectedHomeworld()?.GetCharacteristicModifier(_selectedCharacteristic) ?? 0) +
                       (GetSelectedOrigin()?.GetCharacteristicModifier(_selectedCharacteristic) ?? 0) +
                       (GetSelectedClass()?.GetCharacteristicModifier(_selectedCharacteristic) ?? 0);
        var total = GetCharacteristicTotal(_selectedCharacteristic);

        CharacteristicTitle.Text = Loc.GetString(
            "heretek-onboarding-characteristics-total-title",
            ("name", Loc.GetString(GetNameLocId(_selectedCharacteristic))),
            ("points", total.ToString("+0;-0;0")));
        CharacteristicModifiers.Text = Loc.GetString(
            "heretek-onboarding-characteristics-external-modifiers",
            ("points", modifier.ToString("+0;-0;0")));
        CharacteristicDescription.SetMarkup(Loc.GetString(GetDescriptionLocId(_selectedCharacteristic)));
        CharacteristicEffect.SetMarkup(Loc.GetString(GetEffectLocId(_selectedCharacteristic)));
        SelectedCharacteristicIndex.Text = selectedIndex.ToString("D2");
        SelectedCharacteristicPoints.Text = points.ToString();
        PointBudget.Text = $"{RemainingPoints} / {Wh40kCharacterBuild.MaximumAttributePoints}";
        EffectHeading.Text = $"{Loc.GetString(GetNameLocId(_selectedCharacteristic))} · {Loc.GetString("heretek-onboarding-characteristics-effect-title")}";
        DecreaseButton.Disabled = points <= 0;
        IncreaseButton.Disabled = RemainingPoints <= 0;
    }

    private Wh40kHomeworldPrototype? GetSelectedHomeworld()
    {
        var homeworldId = _draft?.Profile.Wh40kBuild.HomeworldId;
        return homeworldId is not null && _prototypeManager.TryIndex<Wh40kHomeworldPrototype>(homeworldId, out var homeworld)
            ? homeworld
            : null;
    }

    private Wh40kOriginPrototype? GetSelectedOrigin()
    {
        var originId = _draft?.Profile.Wh40kBuild.OriginId;
        return originId is not null && _prototypeManager.TryIndex<Wh40kOriginPrototype>(originId, out var origin)
            ? origin
            : null;
    }

    private Wh40kCharacterClassPrototype? GetSelectedClass()
    {
        var classId = _draft?.Profile.Wh40kBuild.ClassId;
        return classId is not null && _prototypeManager.TryIndex<Wh40kCharacterClassPrototype>(classId, out var characterClass)
            ? characterClass
            : null;
    }

    private static StyleBoxFlat CreateStepStyle(Color background)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = background,
            BorderColor = Color.FromHex("#B697545C"),
            BorderThickness = new Thickness(1f),
            ContentMarginLeftOverride = 0f,
            ContentMarginRightOverride = 0f,
            ContentMarginTopOverride = 0f,
            ContentMarginBottomOverride = 0f,
        };
    }
}
