using System.Linq;
using Content.Client.Message;
using Content.Shared._WH40K.CharacterCreation;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._WH40K.CharacterCreation;

[GenerateTypedNameReferences]
public sealed partial class Wh40kOriginPage : BoxContainer
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    private readonly List<Wh40kOriginPrototype> _origins = new();
    private Wh40kOnboardingDraft? _draft;

    public IReadOnlyList<Wh40kOriginPrototype> Origins => _origins;

    /// <summary>
    ///     Fires after the local build is updated. It is not a preference save.
    /// </summary>
    public event Action<Wh40kOnboardingDraft>? OnDraftChanged;

    /// <summary>
    ///     Lets the outer left-hand navigation update its visual selection.
    /// </summary>
    public event Action<Wh40kOriginPrototype>? OnOriginSelected;

    public Wh40kOriginPage()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _origins.AddRange(_prototypeManager
            .EnumeratePrototypes<Wh40kOriginPrototype>()
            .OrderBy(origin => origin.Order));

    }

    public void SetDraft(Wh40kOnboardingDraft draft)
    {
        _draft = draft;

        if (_origins.Count == 0)
            return;

        var selectedId = draft.Profile.Wh40kBuild.OriginId;
        if (selectedId is null || !_origins.Any(origin => origin.ID == selectedId))
            selectedId = _origins[0].ID;

        SelectOrigin(selectedId);
    }

    public void ClearDraft()
    {
        _draft = null;
    }

    public void SelectOrigin(string id)
    {
        if (_draft is null)
            return;

        var origin = _origins.FirstOrDefault(candidate => candidate.ID == id);
        if (origin is null)
            return;

        var currentBuild = _draft.Profile.Wh40kBuild;
        if (currentBuild.OriginId != origin.ID)
        {
            var updatedBuild = currentBuild.Clone();
            updatedBuild.OriginId = origin.ID;
            _draft.UpdateProfile(_draft.Profile.WithWh40kCharacterBuild(updatedBuild));
            OnDraftChanged?.Invoke(_draft);
        }

        OriginTitle.Text = Loc.GetString(origin.Name);
        OriginKicker.Text = Loc.GetString(origin.Focus);
        OriginDescription.SetMarkup(Loc.GetString(origin.Description));
        FocusDescription.SetMarkup(Loc.GetString(origin.FocusDescription));
        Modifiers.SetMarkup(string.Join("\n", origin.CharacteristicModifiers
            .Where(pair => pair.Value != 0)
            .OrderBy(pair => pair.Key)
            .Select(pair => $"• {Loc.GetString(Wh40kCharacteristicsPage.GetNameLocId(pair.Key))} {pair.Value:+0;-0;0}")));
        LoreNote.SetMarkup(Loc.GetString(origin.LoreNote));
        OnOriginSelected?.Invoke(origin);
    }
}
