using System.Linq;
using Content.Client.Message;
using Content.Shared._WH40K.CharacterCreation;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._WH40K.CharacterCreation;

[GenerateTypedNameReferences]
public sealed partial class Wh40kHomeworldPage : BoxContainer
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    private readonly List<Wh40kHomeworldPrototype> _homeworlds = new();
    private Wh40kOnboardingDraft? _draft;

    public IReadOnlyList<Wh40kHomeworldPrototype> Homeworlds => _homeworlds;

    /// <summary>
    ///     Fires after the local build is updated. This is intentionally not a preference save.
    /// </summary>
    public event Action<Wh40kOnboardingDraft>? OnDraftChanged;

    /// <summary>
    ///     Lets the outer left-hand navigation update only its visual selection.
    /// </summary>
    public event Action<Wh40kHomeworldPrototype>? OnHomeworldSelected;

    public Wh40kHomeworldPage()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _homeworlds.AddRange(_prototypeManager
            .EnumeratePrototypes<Wh40kHomeworldPrototype>()
            .OrderBy(homeworld => homeworld.Order));

    }

    public void SetDraft(Wh40kOnboardingDraft draft)
    {
        _draft = draft;

        if (_homeworlds.Count == 0)
            return;

        var selectedId = draft.Profile.Wh40kBuild.HomeworldId;
        if (selectedId is null || !_homeworlds.Any(homeworld => homeworld.ID == selectedId))
            selectedId = _homeworlds[0].ID;

        SelectHomeworld(selectedId);
    }

    public void ClearDraft()
    {
        _draft = null;
    }

    public void SelectHomeworld(string id)
    {
        if (_draft is null)
            return;

        var homeworld = _homeworlds.FirstOrDefault(candidate => candidate.ID == id);
        if (homeworld is null)
            return;

        var currentBuild = _draft.Profile.Wh40kBuild;
        if (currentBuild.HomeworldId != homeworld.ID)
        {
            var updatedBuild = currentBuild.Clone();
            updatedBuild.HomeworldId = homeworld.ID;
            _draft.UpdateProfile(_draft.Profile.WithWh40kCharacterBuild(updatedBuild));
            OnDraftChanged?.Invoke(_draft);
        }

        HomeworldTitle.Text = Loc.GetString(homeworld.Name);
        HomeworldKicker.Text = Loc.GetString(homeworld.FeatureName);
        HomeworldDescription.SetMarkup(Loc.GetString(homeworld.Description));
        FeatureDescription.SetMarkup(Loc.GetString(homeworld.FeatureDescription));
        Modifiers.SetMarkup(string.Join("\n", homeworld.CharacteristicModifiers
            .Where(pair => pair.Value != 0)
            .OrderBy(pair => pair.Key)
            .Select(pair => $"• {Loc.GetString(Wh40kCharacteristicsPage.GetNameLocId(pair.Key))} {pair.Value:+0;-0;0}")));
        LoreNote.SetMarkup(Loc.GetString(homeworld.LoreNote));
        OnHomeworldSelected?.Invoke(homeworld);
    }
}
