using Content.Client.UserInterface.Controls;
using Content.Shared._WH40K.SectorMap.LandingPads;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WH40K.SectorMap.LandingPads;

[GenerateTypedNameReferences]
public sealed partial class KoronusLandingPadWindow : FancyWindow
{
    public event Action<string, int, bool, bool>? OnSave;

    private string? _serverName;
    private int _serverParkingTime = -1;
    private bool _serverPublicAccess;
    private bool _serverEnabled;

    public KoronusLandingPadWindow()
    {
        RobustXamlLoader.Load(this);
        Save.OnPressed += _ => OnSave?.Invoke(
            PadName.Text,
            Math.Clamp(ParkingTime.Value, 0, 3600),
            PublicAccess.Pressed,
            PadEnabled.Pressed);
    }

    public void UpdateState(KoronusLandingPadBoundUserInterfaceState state)
    {
        if (_serverName != state.Name ||
            _serverParkingTime != state.ParkingTime ||
            _serverPublicAccess != state.PublicAccess ||
            _serverEnabled != state.Enabled)
        {
            _serverName = state.Name;
            _serverParkingTime = state.ParkingTime;
            _serverPublicAccess = state.PublicAccess;
            _serverEnabled = state.Enabled;
            PadName.Text = state.Name;
            ParkingTime.Value = state.ParkingTime;
            PublicAccess.Pressed = state.PublicAccess;
            PadEnabled.Pressed = state.Enabled;
        }

        ConsoleState.Text = !state.PrimaryConsole
            ? Loc.GetString("koronus-landing-pad-console-conflict")
            : !state.Powered
                ? Loc.GetString("koronus-landing-pad-console-unpowered")
                : state.Locked
                    ? Loc.GetString("koronus-landing-pad-console-locked")
                    : Loc.GetString("koronus-landing-pad-console-ready");

        var configurationDisabled = !state.PrimaryConsole || !state.Powered || state.Locked || state.Occupied;
        PadName.Editable = !configurationDisabled;
        ParkingTime.LineEditDisabled = configurationDisabled;
        ParkingTime.SetButtonDisabled(configurationDisabled);
        PublicAccess.Disabled = configurationDisabled;
        PadEnabled.Disabled = configurationDisabled;
        Save.Disabled = configurationDisabled;

        Occupancy.Text = state.Occupied
            ? Loc.GetString("koronus-landing-pad-occupied")
            : Loc.GetString("koronus-landing-pad-empty");
        Shuttle.Text = state.ShuttleName ?? Loc.GetString("koronus-landing-pad-empty");
        Owner.Text = state.ShuttleOwner ?? Loc.GetString("koronus-landing-pad-empty");
        TimeLeft.Text = state.RemainingParkingTime is { } remaining
            ? Loc.GetString("koronus-landing-pad-seconds", ("seconds", MathF.Ceiling(remaining)))
            : Loc.GetString("koronus-landing-pad-unlimited");
    }
}
