using Content.Client.UserInterface.Controls;
using Content.Shared._WH40K.SectorMap.Teleporters;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._WH40K.SectorMap.Teleporters;

[GenerateTypedNameReferences]
public sealed partial class KoronusPlanetaryTeleporterWindow : FancyWindow
{
    private const int ShuttleNameLimit = 15;
    private bool _updating;

    public event Action<string>? OnTargetSelected;
    public event Action<bool>? OnAccessChanged;

    public KoronusPlanetaryTeleporterWindow()
    {
        RobustXamlLoader.Load(this);
        PublicAccess.OnToggled += args =>
        {
            if (!_updating)
                OnAccessChanged?.Invoke(args.Pressed);
        };
    }

    public void UpdateState(KoronusPlanetaryTeleporterState state)
    {
        _updating = true;
        PublicAccess.Pressed = state.PublicAccess;
        _updating = false;
        PublicAccess.Disabled = state.Locked || state.Active || !state.Powered;
        Mode.Text = state.PlanetSide
            ? Loc.GetString("koronus-teleporter-mode-shuttle")
            : Loc.GetString("koronus-teleporter-mode-surface");
        Status.Text = !state.Powered
            ? Loc.GetString("koronus-teleporter-unpowered")
            : state.Active
                ? Loc.GetString("koronus-teleporter-charging")
                : Loc.GetString("koronus-teleporter-ready");
    }

    public void SetTargets(List<KoronusPlanetaryTeleporterTargetState> targets)
    {
        Targets.RemoveAllChildren();
        if (targets.Count == 0)
        {
            Targets.AddChild(new Label { Text = Loc.GetString("koronus-teleporter-no-targets") });
            return;
        }

        foreach (var target in targets)
        {
            var shortName = target.Name.Length > ShuttleNameLimit
                ? target.Name[..(ShuttleNameLimit - 3)] + "..."
                : target.Name;
            var button = new Button
            {
                Text = target.Selected ? $"> {shortName} <" : shortName,
                Disabled = !target.Available,
                ToolTip = target.Name,
                HorizontalExpand = true,
                StyleClasses = { "ButtonSquare" },
            };
            button.Label.FontColorOverride = target.Available
                ? Color.FromHex("#E0E0E0")
                : Color.FromHex("#626866");
            var id = target.Id;
            button.OnPressed += _ => OnTargetSelected?.Invoke(id);
            Targets.AddChild(button);
        }
    }
}
