using System.Linq;
using System.Text.RegularExpressions;
using Content.Client.Stylesheets;
using Content.Shared.Humanoid;
using Content.Shared.Preferences;
using Content.Shared.TTS;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.TTS;

[GenerateTypedNameReferences]
public sealed partial class TTSTab : Control
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public event Action<string>? OnVoiceSelected;
    public event Action<string>? OnPreviewRequested;

    private readonly List<TTSVoicePrototype> _allVoices = [];
    private readonly List<TTSVoicePrototype> _filteredVoices = [];
    private readonly Dictionary<string, List<TTSVoicePrototype>> _categorizedVoices = [];
    private string? _selectedVoiceId;

    private static readonly Regex CategoryRegex = new(@"^(.*?)\s*\(([^)]+)\)\s*$", RegexOptions.Compiled);

    public TTSTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        SearchEdit.OnTextChanged += _ => UpdateResults();
    }

    public void UpdateControls(HumanoidCharacterProfile? profile, Sex sex)
    {
        if (profile == null)
            return;

        _selectedVoiceId = profile.Voice;
        _allVoices.Clear();
        _allVoices.AddRange(_prototypeManager
            .EnumeratePrototypes<TTSVoicePrototype>()
            .Where(voice => HumanoidCharacterProfile.CanHaveVoice(voice, sex))
            .OrderBy(voice => Loc.GetString(voice.Name)));

        _categorizedVoices.Clear();
        foreach (var voice in _allVoices)
        {
            var name = Loc.GetString(voice.Name);
            var category = Loc.GetString("humanoid-profile-editor-voice-other");
            var match = CategoryRegex.Match(name);
            if (match.Success)
                category = match.Groups[2].Value.Trim();

            if (!_categorizedVoices.TryGetValue(category, out var voices))
            {
                voices = [];
                _categorizedVoices.Add(category, voices);
            }

            voices.Add(voice);
        }

        CategoriesContainer.RemoveAllChildren();
        foreach (var category in _categorizedVoices.Keys.OrderBy(category => category))
        {
            var button = new Button
            {
                Text = category,
                ToolTip = Loc.GetString("humanoid-profile-editor-voice-category-tooltip", ("category", category)),
                HorizontalExpand = true,
            };
            button.OnPressed += _ => SearchEdit.Text = category;
            CategoriesContainer.AddChild(button);
        }

        UpdateResults();
    }

    public void SetSelectedVoice(string voiceId)
    {
        _selectedVoiceId = voiceId;
        UpdateResults();
    }

    private void UpdateResults()
    {
        VoicesGrid.RemoveAllChildren();
        _filteredVoices.Clear();

        var search = SearchEdit.Text.ToLowerInvariant();
        foreach (var voice in _allVoices)
        {
            var name = Loc.GetString(voice.Name).ToLowerInvariant();
            if (string.IsNullOrEmpty(search) || name.Contains(search) || voice.ID.ToLowerInvariant().Contains(search))
                _filteredVoices.Add(voice);
        }

        foreach (var voice in _filteredVoices)
        {
            var container = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
            };

            var select = new Button
            {
                Text = Loc.GetString(voice.Name),
                ToolTip = voice.ID,
                HorizontalExpand = true,
                StyleClasses = { StyleNano.ButtonOpenRight },
            };
            if (voice.ID == _selectedVoiceId)
                select.AddStyleClass(StyleBase.ButtonCaution);
            select.OnPressed += _ => OnVoiceSelected?.Invoke(voice.ID);

            var preview = new Button
            {
                Text = Loc.GetString("humanoid-profile-editor-voice-play"),
                MinWidth = 30,
                ToolTip = Loc.GetString("humanoid-profile-editor-voice-tooltip-play"),
                StyleClasses = { StyleNano.ButtonOpenLeft },
            };
            preview.OnPressed += _ => OnPreviewRequested?.Invoke(voice.ID);

            container.AddChild(select);
            container.AddChild(preview);
            VoicesGrid.AddChild(container);
        }

        ResultsLabel.Text = Loc.GetString(
            "humanoid-profile-editor-voice-match",
            ("filtered", _filteredVoices.Count),
            ("all", _allVoices.Count));
    }
}
