using System;
using Content.Shared.Administration.Whitelist;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.WhitelistPanel;

[GenerateTypedNameReferences]
public sealed partial class WhitelistPanelEntry : BoxContainer
{
    private readonly Guid _userId;

    public event Action<Guid>? OnRemoveRequested;

    public WhitelistPanelEntry(WhitelistPanelEntryState entry, bool canRemove)
    {
        RobustXamlLoader.Load(this);
        _userId = entry.UserId;
        CkeyLabel.Text = entry.Ckey;
        RemoveButton.Disabled = !canRemove;
        RemoveButton.OnPressed += _ => OnRemoveRequested?.Invoke(_userId);
    }
}
