using System;
using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Content.Shared.Administration.Whitelist;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.WhitelistPanel;

[GenerateTypedNameReferences]
public sealed partial class WhitelistPanelWindow : FancyWindow
{
    private bool _canModify;
    private bool _whitelistEnabled;
    private WhitelistPanelEntryState[] _entries = Array.Empty<WhitelistPanelEntryState>();
    private PlayerInfo? _selectedOnlinePlayer;

    public event Action? OnCloseRequested;
    public event Action? OnRefreshRequested;
    public event Action<string>? OnPlayerAddRequested;
    public event Action<Guid>? OnPlayerRemoveRequested;
    public event Action<bool>? OnWhitelistEnabledChanged;
    public event Action? OnKickNonWhitelistedRequested;

    public WhitelistPanelWindow()
    {
        RobustXamlLoader.Load(this);

        OnClose += () => OnCloseRequested?.Invoke();
        RefreshButton.OnPressed += _ => OnRefreshRequested?.Invoke();
        AddPlayerButton.OnPressed += _ => AddPlayer();
        AddSelectedPlayerButton.OnPressed += _ => AddSelectedPlayer();
        OnlinePlayerList.FilterPredicate = player => player.Connected;
        OnlinePlayerList.OnSelectionChanged += OnOnlinePlayerSelectionChanged;
        OnlinePlayerList.PopulateList();
        WhitelistFilterLineEdit.OnTextChanged += _ => RefreshWhitelistEntries();
        WhitelistEntriesPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = new Color(54, 54, 54) };
        ToggleWhitelistButton.OnPressed += _ => OnWhitelistEnabledChanged?.Invoke(!_whitelistEnabled);
        KickNonWhitelistedButton.OnPressed += _ => OnKickNonWhitelistedRequested?.Invoke();
    }

    public void UpdateState(WhitelistPanelEuiState state)
    {
        _whitelistEnabled = state.WhitelistEnabled;

        WhitelistStatusLabel.Text = Loc.GetString(
            state.WhitelistEnabled ? "whitelist-panel-status-enabled" : "whitelist-panel-status-disabled");
        WhitelistStatusLabel.FontColorOverride = state.WhitelistEnabled ? Color.LightGreen : Color.OrangeRed;
        ToggleWhitelistButton.Text = Loc.GetString(
            state.WhitelistEnabled ? "whitelist-panel-disable" : "whitelist-panel-enable");
        EntriesLabel.Text = Loc.GetString("whitelist-panel-entries", ("count", state.Entries.Count));

        _canModify = state.CanManageMembers && !state.OperationInProgress;
        _entries = state.Entries.ToArray();

        AddPlayerButton.Disabled = !_canModify;
        RefreshButton.Disabled = !state.CanManageMembers || state.OperationInProgress;
        ToggleWhitelistButton.Disabled = !state.CanToggleWhitelist || state.OperationInProgress;
        KickNonWhitelistedButton.Disabled = !state.CanKickNonWhitelisted ||
            !state.WhitelistEnabled ||
            state.OperationInProgress;

        UpdateSelectedPlayerUi();
        RefreshWhitelistEntries();

        if (state.OperationInProgress)
            NoticeLabel.Text = Loc.GetString("whitelist-panel-operation-in-progress");
    }

    public void ShowNotice(WhitelistPanelNoticeMessage notice)
    {
        NoticeLabel.Text = notice.Message;
        NoticeLabel.FontColorOverride = notice.Level switch
        {
            WhitelistPanelNoticeLevel.Success => Color.LightGreen,
            WhitelistPanelNoticeLevel.Error => Color.OrangeRed,
            _ => Color.Gold,
        };
    }

    private void AddPlayer()
    {
        var ckey = PlayerCkeyLine.Text?.Trim();
        if (string.IsNullOrEmpty(ckey))
        {
            ShowNotice(new WhitelistPanelNoticeMessage(
                Loc.GetString("whitelist-panel-error-enter-ckey"),
                WhitelistPanelNoticeLevel.Error));
            return;
        }

        OnPlayerAddRequested?.Invoke(ckey);
    }

    private void AddSelectedPlayer()
    {
        if (_selectedOnlinePlayer == null || IsSelectedPlayerWhitelisted())
            return;

        OnPlayerAddRequested?.Invoke(_selectedOnlinePlayer.Username);
    }

    private void OnOnlinePlayerSelectionChanged(PlayerInfo? player)
    {
        _selectedOnlinePlayer = player;
        UpdateSelectedPlayerUi();
    }

    private void UpdateSelectedPlayerUi()
    {
        if (_selectedOnlinePlayer == null)
        {
            SelectedPlayerLabel.Text = Loc.GetString("whitelist-panel-no-online-player-selected");
            AddSelectedPlayerButton.Disabled = true;
            return;
        }

        SelectedPlayerLabel.Text = Loc.GetString(
            "whitelist-panel-selected-online-player",
            ("player", _selectedOnlinePlayer.CharacterName),
            ("ckey", _selectedOnlinePlayer.Username));

        var alreadyWhitelisted = IsSelectedPlayerWhitelisted();
        AddSelectedPlayerButton.Disabled = !_canModify || alreadyWhitelisted;
        if (alreadyWhitelisted)
            SelectedPlayerLabel.Text = Loc.GetString("whitelist-panel-selected-player-already-added");
    }

    private bool IsSelectedPlayerWhitelisted()
    {
        return _selectedOnlinePlayer != null &&
               _entries.Any(entry => entry.UserId == _selectedOnlinePlayer.SessionId.UserId);
    }

    private void RefreshWhitelistEntries()
    {
        EntriesContainer.RemoveAllChildren();

        var filter = WhitelistFilterLineEdit.Text?.Trim();
        var entries = _entries
            .Where(entry => string.IsNullOrEmpty(filter) ||
                            entry.Ckey.Contains(filter, StringComparison.OrdinalIgnoreCase))
            .ToArray();

        if (entries.Length == 0)
        {
            EntriesContainer.AddChild(new Label
            {
                Text = Loc.GetString(string.IsNullOrEmpty(filter)
                    ? "whitelist-panel-no-entries"
                    : "whitelist-panel-no-filter-results"),
            });
            return;
        }

        foreach (var entry in entries)
        {
            var control = new WhitelistPanelEntry(entry, _canModify);
            control.OnRemoveRequested += userId => OnPlayerRemoveRequested?.Invoke(userId);
            EntriesContainer.AddChild(control);
        }
    }
}
