using Content.Client.PDA;
using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NetProbeUiFragment : BoxContainer
{
    public NetProbeUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;
    }

    public void UpdateState(List<ProbedNetworkDevice> devices)
    {
        ProbedDeviceContainer.RemoveAllChildren();

        // Reverse the list so the oldest entries appear at the bottom.
        devices.Reverse();

        // Enable horizontal scrolling only when the table can no longer fit in the display.
        ScrollContainer.HScrollEnabled = devices.Count > 9;

        foreach (var device in devices)
        {
            AddProbedDevice(device);
        }
    }

    private void AddProbedDevice(ProbedNetworkDevice device)
    {
        var row = new BoxContainer
        {
            HorizontalExpand = true,
            Orientation = LayoutOrientation.Horizontal,
            Margin = new Thickness(4)
        };

        var nameLabel = new Label
        {
            Text = device.Name,
            FontColorOverride = PdaTerminalPalette.PrimaryText,
            HorizontalExpand = true,
            ClipText = true
        };
        row.AddChild(nameLabel);

        var addressLabel = new Label
        {
            Text = device.Address,
            FontColorOverride = PdaTerminalPalette.PrimaryText,
            HorizontalExpand = true,
            ClipText = true
        };
        row.AddChild(addressLabel);

        var frequencyLabel = new Label
        {
            Text = device.Frequency,
            FontColorOverride = PdaTerminalPalette.PrimaryText,
            HorizontalExpand = true,
            ClipText = true
        };
        row.AddChild(frequencyLabel);

        var networkLabel = new Label
        {
            Text = device.NetId,
            FontColorOverride = PdaTerminalPalette.PrimaryText,
            HorizontalExpand = true,
            ClipText = true
        };
        row.AddChild(networkLabel);

        ProbedDeviceContainer.AddChild(row);
    }
}
