using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._WH40K.DirectionalEmote.UserInterface;

[GenerateTypedNameReferences]
public sealed partial class WH40KDirectionalEmoteWindow : FancyWindow
{
    public NetEntity Source;
    public NetEntity Target;
    public string Text = string.Empty;
    public bool HideName;

    public Action? AcceptPressed;
    public Action? LastEmotePressed;

    public WH40KDirectionalEmoteWindow()
    {
        RobustXamlLoader.Load(this);

        LastEmoteButton.OnPressed += _ => LastEmotePressed?.Invoke();
        AcceptButton.OnPressed += _ => AcceptPressed?.Invoke();
        MessageInput.OnTextChanged += args => Text = Rope.Collapse(args.TextRope).Trim();
        HideNameCheckBox.OnToggled += args => HideName = args.Pressed;
    }

    public void SetText(string text)
    {
        Text = text;
        MessageInput.TextRope = new Rope.Leaf(text);
    }

    public void UpdateHideNameVisibility(bool visible)
    {
        HideNameCheckBox.Visible = visible;
        HideNameCheckBox.Pressed = false;
        HideName = false;
    }
}
