using System.Numerics;
using Content.Client.PDA;
using Content.Shared._WH40K.Progression;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._WH40K.Progression;

[GenerateTypedNameReferences]
public sealed partial class Wh40kPartyUiFragment : BoxContainer
{
    private bool _pending;
    private bool _updating;
    private Wh40kPartyUiSnapshot? _snapshot;

    public event Action<string>? OnInvite;
    public event Action? OnLeave;
    public event Action<Guid>? OnKick;
    public event Action<bool>? OnInvitesAllowedChanged;

    public Wh40kPartyUiFragment()
    {
        RobustXamlLoader.Load(this);

        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        InviteButton.StyleBoxOverride = PdaTerminalPalette.CreateButton(accented: true);
        LeaveButton.StyleBoxOverride = PdaTerminalPalette.CreateButton();
        AllowInvites.SetMessage(
            Loc.GetString("wh40k-rpg-party-allow-invites"),
            Color.FromHex("#D7E0D7"));

        InviteCkey.IsValid = text => text.Length <= Wh40kRpgPdaConstants.MaximumCkeyLength;
        InviteButton.OnPressed += _ => TryInvite();
        InviteCkey.OnTextEntered += _ => TryInvite();
        InviteCkey.OnTextChanged += _ => UpdateActions();
        LeaveButton.OnPressed += _ => OnLeave?.Invoke();
        AllowInvites.OnToggled += args =>
        {
            if (!_updating)
                OnInvitesAllowedChanged?.Invoke(args.Pressed);
        };
    }

    public void UpdateSnapshot(
        Wh40kPartyUiSnapshot? snapshot,
        Wh40kPartyUiOperationStatus status)
    {
        _snapshot = snapshot;
        _pending = false;
        StatusLabel.Visible = status != Wh40kPartyUiOperationStatus.None;
        StatusLabel.SetMessage(GetStatusText(status), Color.FromHex("#E5C879"));

        _updating = true;
        AllowInvites.Pressed = snapshot?.InvitesAllowed ?? false;
        _updating = false;

        MemberList.RemoveAllChildren();
        if (snapshot == null)
        {
            MemberCount.Text = string.Empty;
            ExpiryLabel.Clear();
            AddEmptyState("wh40k-rpg-party-unavailable");
            UpdateActions();
            return;
        }

        MemberCount.Text = Loc.GetString(
            "wh40k-rpg-party-member-count",
            ("count", snapshot.Members.Count),
            ("maximum", 5));

        if (snapshot.PartyId == null)
        {
            ExpiryLabel.SetMessage(
                Loc.GetString("wh40k-rpg-party-no-expiry"),
                Color.FromHex("#93A096"));
            AddEmptyState("wh40k-rpg-party-empty");
        }
        else
        {
            ExpiryLabel.SetMessage(
                Loc.GetString(
                    "wh40k-rpg-party-expires",
                    ("time", FormatExpiry(snapshot.ExpiresAtUtcTicks))),
                Color.FromHex("#93A096"));
            foreach (var member in snapshot.Members)
                MemberList.AddChild(CreateMemberRow(member, snapshot.IsLeader));
        }

        UpdateActions();
    }

    public void SetPending(bool pending)
    {
        _pending = pending;
        UpdateActions();
    }

    private void TryInvite()
    {
        var ckey = InviteCkey.Text.Trim();
        if (string.IsNullOrEmpty(ckey) || ckey.Length > Wh40kRpgPdaConstants.MaximumCkeyLength)
            return;

        OnInvite?.Invoke(ckey);
        InviteCkey.Text = string.Empty;
    }

    private Control CreateMemberRow(Wh40kPartyMemberUiSnapshot member, bool viewerIsLeader)
    {
        var row = new PdaTerminalPanel
        {
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 4),
        };
        var contents = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(7, 5),
        };
        var identity = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };
        var ckeyLabel = new RichTextLabel { HorizontalExpand = true };
        ckeyLabel.SetMessage(member.Ckey, Color.FromHex("#D7E0D7"));
        identity.AddChild(ckeyLabel);

        var statusLabel = new RichTextLabel { HorizontalExpand = true };
        statusLabel.SetMessage(
            GetMemberStatus(member),
            member.IsOnline
                ? Color.FromHex("#88D2A5")
                : Color.FromHex("#667168"));
        identity.AddChild(statusLabel);
        contents.AddChild(identity);

        if (viewerIsLeader && !member.IsSelf)
        {
            var kick = new Button
            {
                Text = "×",
                SetSize = new Vector2(26, 24),
                ToolTip = Loc.GetString("wh40k-rpg-party-kick-tooltip"),
                StyleBoxOverride = PdaTerminalPalette.CreateButton(),
            };
            kick.OnPressed += _ => OnKick?.Invoke(member.UserId);
            contents.AddChild(kick);
        }

        row.AddChild(contents);
        return row;
    }

    private void AddEmptyState(string localizationKey)
    {
        var emptyState = new RichTextLabel
        {
            HorizontalExpand = true,
            Margin = new Thickness(6, 12),
        };
        emptyState.SetMessage(Loc.GetString(localizationKey), Color.FromHex("#93A096"));
        MemberList.AddChild(emptyState);
    }

    private void UpdateActions()
    {
        var hasSnapshot = _snapshot != null;
        var ckey = InviteCkey.Text.Trim();
        var validCkey = ckey.Length <= Wh40kRpgPdaConstants.MaximumCkeyLength;
        AllowInvites.Disabled = !hasSnapshot || _pending;
        InviteCkey.Editable = hasSnapshot && !_pending;
        InviteButton.Disabled = !hasSnapshot || _pending ||
                                string.IsNullOrEmpty(ckey) ||
                                !validCkey;
        LeaveButton.Visible = _snapshot?.PartyId != null;
        LeaveButton.Disabled = _pending;
        LeaveButton.Text = _snapshot?.IsLeader == true
            ? Loc.GetString("wh40k-rpg-party-disband")
            : Loc.GetString("wh40k-rpg-party-leave");

        foreach (var child in MemberList.Children)
        {
            if (child is not PdaTerminalPanel panel)
                continue;

            SetButtonsDisabled(panel, _pending);
        }
    }

    private static void SetButtonsDisabled(Control control, bool disabled)
    {
        foreach (var child in control.Children)
        {
            if (child is Button button)
                button.Disabled = disabled;
            SetButtonsDisabled(child, disabled);
        }
    }

    private static string GetMemberStatus(Wh40kPartyMemberUiSnapshot member)
    {
        var role = member.IsLeader
            ? Loc.GetString("wh40k-rpg-party-member-leader")
            : Loc.GetString("wh40k-rpg-party-member");
        var self = member.IsSelf
            ? Loc.GetString("wh40k-rpg-party-member-self")
            : string.Empty;
        var connection = Loc.GetString(member.IsOnline
            ? "wh40k-rpg-party-member-online"
            : "wh40k-rpg-party-member-offline");
        return Loc.GetString(
            "wh40k-rpg-party-member-status",
            ("role", role),
            ("self", self),
            ("connection", connection));
    }

    private static string FormatExpiry(long utcTicks)
    {
        if (utcTicks <= 0)
            return "—";

        return new DateTime(utcTicks, DateTimeKind.Utc)
            .ToLocalTime()
            .ToString("dd.MM.yyyy HH:mm");
    }

    private static string GetStatusText(Wh40kPartyUiOperationStatus status)
    {
        var key = status switch
        {
            Wh40kPartyUiOperationStatus.Success => "wh40k-rpg-party-status-success",
            Wh40kPartyUiOperationStatus.AccountUnavailable => "wh40k-rpg-party-status-account-unavailable",
            Wh40kPartyUiOperationStatus.InvalidTarget => "wh40k-rpg-party-status-invalid-target",
            Wh40kPartyUiOperationStatus.InvitesDisabled => "wh40k-rpg-party-status-invites-disabled",
            Wh40kPartyUiOperationStatus.AlreadyInParty => "wh40k-rpg-party-status-already-in-party",
            Wh40kPartyUiOperationStatus.NotInParty => "wh40k-rpg-party-status-not-in-party",
            Wh40kPartyUiOperationStatus.PartyNotFound => "wh40k-rpg-party-status-party-not-found",
            Wh40kPartyUiOperationStatus.PartyExpired => "wh40k-rpg-party-status-party-expired",
            Wh40kPartyUiOperationStatus.NotLeader => "wh40k-rpg-party-status-not-leader",
            Wh40kPartyUiOperationStatus.PartyFull => "wh40k-rpg-party-status-party-full",
            Wh40kPartyUiOperationStatus.RevisionMismatch => "wh40k-rpg-party-status-revision",
            Wh40kPartyUiOperationStatus.InvitationNotFound => "wh40k-rpg-party-status-invitation-not-found",
            Wh40kPartyUiOperationStatus.InvitationExpired => "wh40k-rpg-party-status-invitation-expired",
            _ => string.Empty,
        };

        return string.IsNullOrEmpty(key) ? string.Empty : Loc.GetString(key);
    }
}
