using System.Linq;
using Content.Client.PDA;
using Content.Shared._WH40K.CharacterCreation;
using Content.Shared._WH40K.Progression;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client._WH40K.Progression;

[GenerateTypedNameReferences]
public sealed partial class Wh40kPlayerUiFragment : BoxContainer
{
    private readonly IPrototypeManager _prototypes;
    private readonly Dictionary<Wh40kCharacteristic, Wh40kCharacteristicRow> _rows = new();
    private readonly Dictionary<Wh40kCharacteristic, int> _draft = new();
    private Wh40kPlayerProgressUiSnapshot? _snapshot;
    private bool _pending;

    public event Action<List<Wh40kCharacteristicAllocation>>? OnCharacteristicPurchase;
    public event Action? OnClassProgramRequested;

    public Wh40kPlayerUiFragment()
    {
        RobustXamlLoader.Load(this);
        _prototypes = IoCManager.Resolve<IPrototypeManager>();

        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        var dividerStyle = PdaTerminalPalette.CreatePanel(
            PdaTerminalPalette.AccentMuted,
            PdaTerminalPalette.AccentMuted);
        CharacterDivider.PanelOverride = dividerStyle;
        HomeworldDivider.PanelOverride = dividerStyle;
        OriginDivider.PanelOverride = dividerStyle;
        ConfirmAllocationButton.StyleBoxOverride = PdaTerminalPalette.CreateButton(accented: true);
        OpenClassProgramButton.StyleBoxOverride = PdaTerminalPalette.CreateButton();
        ConfirmAllocationButton.OnPressed += _ => ConfirmDraft();
        OpenClassProgramButton.OnPressed += _ => OnClassProgramRequested?.Invoke();

        foreach (var characteristic in Enum.GetValues<Wh40kCharacteristic>())
        {
            var row = new Wh40kCharacteristicRow(characteristic);
            row.OnIncrease += IncreaseDraft;
            row.OnDecrease += DecreaseDraft;
            _rows.Add(characteristic, row);
            _draft.Add(characteristic, 0);
            CharacteristicList.AddChild(row);
        }
    }

    public void UpdateSnapshot(
        Wh40kPlayerProgressUiSnapshot? snapshot,
        Wh40kPlayerUiOperationStatus status)
    {
        _snapshot = snapshot;
        _pending = false;
        ClearDraft();
        StatusLabel.Visible = status != Wh40kPlayerUiOperationStatus.None;
        StatusLabel.SetMessage(GetStatusText(status), Color.FromHex("#E5C879"));

        if (snapshot == null)
        {
            LevelHeader.Text = string.Empty;
            CharacterName.SetMessage(
                Loc.GetString("wh40k-rpg-player-unavailable"),
                Color.FromHex("#D7E0D7"));
            HomeworldLabel.Clear();
            OriginLabel.Clear();
            ClassLabel.Clear();
            OpenClassProgramButton.Disabled = true;
            ExperienceLabel.Clear();
            PointsLabel.Clear();
            ExperienceBar.MaxValue = 1;
            ExperienceBar.Value = 0;
            ConfirmAllocationButton.Text = Loc.GetString("wh40k-rpg-player-confirm-allocation-empty");
            ConfirmAllocationButton.Disabled = true;
            foreach (var row in _rows.Values)
                row.SetUnavailable();
            return;
        }

        LevelHeader.Text = Loc.GetString("wh40k-rpg-player-level-short", ("level", snapshot.Level));
        CharacterName.SetMessage(
            Loc.GetString(
                "wh40k-rpg-player-character-name",
                ("name", snapshot.CharacterName)),
            Color.FromHex("#D7E0D7"));
        HomeworldLabel.SetMessage(
            Loc.GetString(
                "wh40k-rpg-player-homeworld",
                ("homeworld", GetPrototypeName<Wh40kHomeworldPrototype>(snapshot.HomeworldId))),
            Color.FromHex("#D7E0D7"));
        OriginLabel.SetMessage(
            Loc.GetString(
                "wh40k-rpg-player-origin",
                ("origin", GetPrototypeName<Wh40kOriginPrototype>(snapshot.OriginId))),
            Color.FromHex("#D7E0D7"));
        ClassLabel.SetMessage(
            Loc.GetString(
                "wh40k-rpg-player-class",
                ("class", GetPrototypeName<Wh40kCharacterClassPrototype>(snapshot.ClassId))),
            Color.FromHex("#D7E0D7"));
        OpenClassProgramButton.Disabled = false;
        var experienceText = snapshot.CurrentLevelSpanTenths == 0
            ? Loc.GetString(
                "wh40k-rpg-player-xp-maximum",
                ("total", FormatExperience(snapshot.TotalExperienceTenths)))
            : Loc.GetString(
                "wh40k-rpg-player-xp",
                ("current", FormatExperience(snapshot.CurrentLevelExperienceTenths)),
                ("required", FormatExperience(snapshot.CurrentLevelSpanTenths)),
                ("total", FormatExperience(snapshot.TotalExperienceTenths)));
        ExperienceLabel.SetMessage(experienceText, Color.FromHex("#D7E0D7"));

        ExperienceBar.MaxValue = Math.Max(1, snapshot.CurrentLevelSpanTenths);
        ExperienceBar.Value = snapshot.CurrentLevelSpanTenths == 0
            ? ExperienceBar.MaxValue
            : Math.Min(snapshot.CurrentLevelExperienceTenths, snapshot.CurrentLevelSpanTenths);

        RefreshDraftUi();
    }

    public void SetPending(bool pending)
    {
        _pending = pending;
        RefreshDraftUi();
    }

    private void IncreaseDraft(Wh40kCharacteristic characteristic)
    {
        if (_pending || _snapshot == null || GetRemainingPoints() <= 0)
            return;

        _draft[characteristic] = checked(_draft.GetValueOrDefault(characteristic) + 1);
        RefreshDraftUi();
    }

    private void DecreaseDraft(Wh40kCharacteristic characteristic)
    {
        if (_pending || _draft.GetValueOrDefault(characteristic) <= 0)
            return;

        _draft[characteristic]--;
        RefreshDraftUi();
    }

    private void ConfirmDraft()
    {
        if (_pending || _snapshot == null)
            return;

        var allocations = _draft
            .Where(entry => entry.Value > 0)
            .OrderBy(entry => entry.Key)
            .Select(entry => new Wh40kCharacteristicAllocation(entry.Key, entry.Value))
            .ToList();
        if (allocations.Count == 0)
            return;

        _pending = true;
        RefreshDraftUi();
        OnCharacteristicPurchase?.Invoke(allocations);
    }

    private void RefreshDraftUi()
    {
        if (_snapshot == null)
            return;

        var selected = GetSelectedPoints();
        var remaining = GetRemainingPoints();
        var pointsText = selected == 0
            ? Loc.GetString(
                "wh40k-rpg-player-points",
                ("points", _snapshot.UnspentDevelopmentPoints))
            : Loc.GetString(
                "wh40k-rpg-player-points-draft",
                ("remaining", remaining),
                ("selected", selected));
        PointsLabel.SetMessage(pointsText, Color.FromHex("#88D2A5"));

        ConfirmAllocationButton.Text = selected == 0
            ? Loc.GetString("wh40k-rpg-player-confirm-allocation-empty")
            : Loc.GetString(
                "wh40k-rpg-player-confirm-allocation",
                ("points", selected));
        ConfirmAllocationButton.Disabled = _pending || selected == 0;

        foreach (var characteristic in _snapshot.Characteristics)
        {
            if (!_rows.TryGetValue(characteristic.Characteristic, out var row))
                continue;

            var draft = _draft.GetValueOrDefault(characteristic.Characteristic);
            row.UpdateSnapshot(
                characteristic,
                draft,
                !_pending && remaining > 0,
                !_pending && draft > 0);
        }
    }

    private int GetSelectedPoints()
    {
        return _draft.Values.Sum();
    }

    private int GetRemainingPoints()
    {
        return Math.Max(0, (_snapshot?.UnspentDevelopmentPoints ?? 0) - GetSelectedPoints());
    }

    private void ClearDraft()
    {
        foreach (var characteristic in _draft.Keys.ToArray())
            _draft[characteristic] = 0;
    }

    private string GetPrototypeName<T>(string id) where T : class, IPrototype
    {
        if (!_prototypes.TryIndex<T>(id, out var prototype))
            return id;

        return prototype switch
        {
            Wh40kHomeworldPrototype homeworld => Loc.GetString(homeworld.Name),
            Wh40kOriginPrototype origin => Loc.GetString(origin.Name),
            Wh40kCharacterClassPrototype characterClass => Loc.GetString(characterClass.Name),
            _ => id,
        };
    }

    private static string FormatExperience(long tenths)
    {
        return $"{tenths / 10}.{Math.Abs(tenths % 10)}";
    }

    private static string GetStatusText(Wh40kPlayerUiOperationStatus status)
    {
        var key = status switch
        {
            Wh40kPlayerUiOperationStatus.Success => "wh40k-rpg-player-status-success",
            Wh40kPlayerUiOperationStatus.AccountUnavailable => "wh40k-rpg-player-status-account-unavailable",
            Wh40kPlayerUiOperationStatus.InvalidCharacteristic => "wh40k-rpg-player-status-invalid-characteristic",
            Wh40kPlayerUiOperationStatus.InvalidCount => "wh40k-rpg-player-status-invalid-count",
            Wh40kPlayerUiOperationStatus.RevisionMismatch => "wh40k-rpg-player-status-revision",
            Wh40kPlayerUiOperationStatus.InsufficientDevelopmentPoints =>
                "wh40k-rpg-player-status-insufficient-points",
            _ => string.Empty,
        };

        return string.IsNullOrEmpty(key) ? string.Empty : Loc.GetString(key);
    }
}
