using System.Globalization;
using Content.Client.PDA;
using Content.Shared._WH40K.CharacterCreation;
using Content.Shared._WH40K.Progression;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WH40K.Progression;

[GenerateTypedNameReferences]
public sealed partial class Wh40kCharacteristicRow : BoxContainer
{
    private readonly Wh40kCharacteristic _characteristic;

    public event Action<Wh40kCharacteristic>? OnIncrease;
    public event Action<Wh40kCharacteristic>? OnDecrease;

    public Wh40kCharacteristicRow(Wh40kCharacteristic characteristic)
    {
        _characteristic = characteristic;
        RobustXamlLoader.Load(this);

        HorizontalExpand = true;
        RemoveButton.StyleBoxOverride = PdaTerminalPalette.CreateButton();
        AddButton.StyleBoxOverride = PdaTerminalPalette.CreateButton(accented: true);
        RemoveButton.OnPressed += _ => OnDecrease?.Invoke(_characteristic);
        AddButton.OnPressed += _ => OnIncrease?.Invoke(_characteristic);
        CharacteristicName.Text = GetCharacteristicName(characteristic);
    }

    public void UpdateSnapshot(
        Wh40kCharacteristicUiSnapshot snapshot,
        int draft,
        bool canIncrease,
        bool canDecrease)
    {
        var projected = checked(snapshot.Final + draft);
        FinalValue.Text = projected.ToString();
        EffectDescription.SetMessage(
            GetEffectDescription(_characteristic, projected),
            Color.FromHex("#93A096"));
        AddButton.Disabled = !canIncrease;
        RemoveButton.Disabled = !canDecrease;
    }

    public void SetActionsEnabled(bool canIncrease, bool canDecrease)
    {
        AddButton.Disabled = !canIncrease;
        RemoveButton.Disabled = !canDecrease;
    }

    public void SetUnavailable()
    {
        FinalValue.Text = "—";
        EffectDescription.Clear();
        AddButton.Disabled = true;
        RemoveButton.Disabled = true;
    }

    private static string GetCharacteristicName(Wh40kCharacteristic characteristic)
    {
        return Loc.GetString(characteristic switch
        {
            Wh40kCharacteristic.Melee => "heretek-characteristic-melee-name",
            Wh40kCharacteristic.Ranged => "heretek-characteristic-ranged-name",
            Wh40kCharacteristic.Endurance => "heretek-characteristic-endurance-name",
            Wh40kCharacteristic.Intelligence => "heretek-characteristic-intelligence-name",
            Wh40kCharacteristic.Agility => "heretek-characteristic-agility-name",
            _ => throw new ArgumentOutOfRangeException(nameof(characteristic)),
        });
    }

    private static string GetEffectDescription(Wh40kCharacteristic characteristic, int value)
    {
        return characteristic switch
        {
            Wh40kCharacteristic.Melee => GetMeleeDescription(value),
            Wh40kCharacteristic.Ranged => GetRangedDescription(value),
            Wh40kCharacteristic.Endurance => GetEnduranceDescription(value),
            Wh40kCharacteristic.Intelligence => GetIntelligenceDescription(value),
            Wh40kCharacteristic.Agility => GetAgilityDescription(value),
            _ => throw new ArgumentOutOfRangeException(nameof(characteristic)),
        };
    }

    private static string GetMeleeDescription(int value)
    {
        var damage = Wh40kCharacteristicEffects.GetDamageMultiplier(value) - 1f;
        var shorterPause = 1f - Wh40kCharacteristicEffects.GetMeleeCooldownMultiplier(value);
        if (damage > 0f)
        {
            return Loc.GetString(
                "wh40k-rpg-player-effect-melee-positive",
                ("damage", FormatPercent(damage)),
                ("tempo", FormatPercent(shorterPause)));
        }

        if (damage < 0f)
        {
            return Loc.GetString(
                "wh40k-rpg-player-effect-melee-negative",
                ("damage", FormatPercent(damage)),
                ("tempo", FormatPercent(shorterPause)));
        }

        return Loc.GetString("wh40k-rpg-player-effect-melee-zero");
    }

    private static string GetRangedDescription(int value)
    {
        var damage = Wh40kCharacteristicEffects.GetDamageMultiplier(value) - 1f;
        var precision = 1f - Wh40kCharacteristicEffects.GetRangedPrecisionMultiplier(value);
        if (damage > 0f)
        {
            return Loc.GetString(
                "wh40k-rpg-player-effect-ranged-positive",
                ("damage", FormatPercent(damage)),
                ("precision", FormatPercent(precision)));
        }

        if (damage < 0f)
        {
            return Loc.GetString(
                "wh40k-rpg-player-effect-ranged-negative",
                ("damage", FormatPercent(damage)),
                ("precision", FormatPercent(precision)));
        }

        return Loc.GetString("wh40k-rpg-player-effect-ranged-zero");
    }

    private static string GetEnduranceDescription(int value)
    {
        var effect = Wh40kCharacteristicEffects.GetEnduranceEffect(value);
        if (effect > 0)
        {
            return Loc.GetString(
                "wh40k-rpg-player-effect-endurance-positive",
                ("amount", effect));
        }

        if (effect < 0)
        {
            return Loc.GetString(
                "wh40k-rpg-player-effect-endurance-negative",
                ("amount", Math.Abs(effect)));
        }

        return Loc.GetString("wh40k-rpg-player-effect-endurance-zero");
    }

    private static string GetIntelligenceDescription(int value)
    {
        var speed = Wh40kCharacteristicEffects.GetDoAfterSpeedMultiplier(value) - 1f;
        if (speed > 0f)
        {
            return Loc.GetString(
                "wh40k-rpg-player-effect-intelligence-positive",
                ("speed", FormatPercent(speed)));
        }

        if (speed < 0f)
        {
            return Loc.GetString(
                "wh40k-rpg-player-effect-intelligence-negative",
                ("speed", FormatPercent(speed)));
        }

        return Loc.GetString("wh40k-rpg-player-effect-intelligence-zero");
    }

    private static string GetAgilityDescription(int value)
    {
        var speed = Wh40kCharacteristicEffects.GetMovementSpeedMultiplier(value) - 1f;
        var charges = Wh40kCharacteristicEffects.GetPhantomStepCharges(value);
        if (speed > 0f)
        {
            return Loc.GetString(
                "wh40k-rpg-player-effect-agility-positive",
                ("speed", FormatPercent(speed)),
                ("charges", charges));
        }

        if (speed < 0f)
        {
            return Loc.GetString(
                "wh40k-rpg-player-effect-agility-negative",
                ("speed", FormatPercent(speed)),
                ("charges", charges));
        }

        return Loc.GetString(
            "wh40k-rpg-player-effect-agility-zero",
            ("charges", charges));
    }

    private static string FormatPercent(float value)
    {
        return (MathF.Abs(value) * 100f).ToString("0.#", CultureInfo.CurrentCulture);
    }
}
