using Content.Client.PDA;
using System.Linq;
using Content.Shared._WH40K.CharacterCreation;
using Content.Shared._WH40K.ClassProgression;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client._WH40K.Progression;

[GenerateTypedNameReferences]
public sealed partial class Wh40kClassUiFragment : BoxContainer
{
    [Dependency] private IPrototypeManager _prototypes = default!;

    private Wh40kClassUiSnapshot? _snapshot;
    private bool _pending;

    public event Action<string?>? OpenTreeRequested;
    public event Action? Detached;

    public Wh40kClassUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;
        OpenTreeButton.StyleBoxOverride = PdaTerminalPalette.CreateButton(accented: true);
        SpecializationOneButton.StyleBoxOverride = PdaTerminalPalette.CreateButton();
        SpecializationTwoButton.StyleBoxOverride = PdaTerminalPalette.CreateButton();
        OpenTreeButton.OnPressed += _ => OpenTreeRequested?.Invoke(null);
        SpecializationOneButton.OnPressed += _ => OpenSpecialization(0);
        SpecializationTwoButton.OnPressed += _ => OpenSpecialization(1);
        SetUnavailable();
    }

    public void UpdateSnapshot(
        Wh40kClassUiSnapshot? snapshot,
        Wh40kClassUiOperationStatus status)
    {
        _snapshot = snapshot;
        _pending = false;
        StatusLabel.Visible = status != Wh40kClassUiOperationStatus.None;
        StatusLabel.SetMessage(
            Wh40kClassTreeWindowStatus.GetStatusText(status),
            status == Wh40kClassUiOperationStatus.PurchaseSucceeded
                ? Color.FromHex("#E5C879")
                : Color.FromHex("#D56A6A"));

        if (snapshot == null)
        {
            SetUnavailable();
            return;
        }

        ClassNameLabel.Text = GetClassName(snapshot.Tree.ClassId);
        PointsLabel.Text = Loc.GetString(
            "wh40k-class-ui-pda-points",
            ("points", snapshot.Tree.AvailableSkillPoints));
        ClassSummary.SetMessage(
            Loc.GetString(
                "wh40k-class-ui-pda-summary",
                ("level", snapshot.Tree.CurrentLevel),
                ("purchased", snapshot.Tree.PurchasedSkillIds.Count),
                ("total", snapshot.Tree.Specializations.Sum(specialization => specialization.Skills.Count))),
            Color.FromHex("#D7E0D7"));
        UpdateSpecializations();
        UpdateRecentSkills();
        OpenTreeButton.Disabled = false;
    }

    public void SetPending(bool pending)
    {
        _pending = pending;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        Detached?.Invoke();
    }

    private void UpdateSpecializations()
    {
        if (_snapshot == null)
            return;

        var buttons = new[] { SpecializationOneButton, SpecializationTwoButton };
        for (var i = 0; i < buttons.Length; i++)
        {
            if (i >= _snapshot.Tree.Specializations.Count ||
                !_prototypes.TryIndex<Wh40kClassSpecializationPrototype>(
                    _snapshot.Tree.Specializations[i].SpecializationId,
                    out var specialization))
            {
                buttons[i].Visible = false;
                continue;
            }

            var purchased = _snapshot.Tree.Specializations[i].Skills.Count(skill =>
                skill.State == Wh40kClassSkillNodeState.Purchased);
            buttons[i].Visible = true;
            buttons[i].Text = Loc.GetString(
                "wh40k-class-ui-pda-specialization",
                ("name", Loc.GetString(specialization.Name)),
                ("purchased", purchased));
            buttons[i].ToolTip = Loc.GetString(specialization.Description);
        }
    }

    private void UpdateRecentSkills()
    {
        RecentSkills.RemoveAllChildren();
        if (_snapshot == null || _snapshot.RecentPurchasedSkillIds.Count == 0)
        {
            RecentSkills.AddChild(new Label
            {
                Text = Loc.GetString("wh40k-class-ui-recent-empty"),
                FontColorOverride = Color.FromHex("#93A096"),
            });
            return;
        }

        foreach (var skillId in _snapshot.RecentPurchasedSkillIds)
        {
            RecentSkills.AddChild(new Label
            {
                Text = _prototypes.TryIndex<Wh40kClassSkillPrototype>(skillId, out var skill)
                    ? $"• {Loc.GetString(skill.Name)}"
                    : $"• {skillId}",
                FontColorOverride = Color.FromHex("#D7E0D7"),
            });
        }
    }

    private void OpenSpecialization(int index)
    {
        if (_pending || _snapshot == null || index >= _snapshot.Tree.Specializations.Count)
            return;

        OpenTreeRequested?.Invoke(_snapshot.Tree.Specializations[index].SpecializationId);
    }

    private string GetClassName(string classId)
    {
        return _prototypes.TryIndex<Wh40kCharacterClassPrototype>(classId, out var characterClass)
            ? Loc.GetString(characterClass.Name)
            : classId;
    }

    private void SetUnavailable()
    {
        ClassNameLabel.Text = Loc.GetString("wh40k-class-ui-unavailable");
        ClassSummary.Clear();
        PointsLabel.Text = string.Empty;
        SpecializationOneButton.Visible = false;
        SpecializationTwoButton.Visible = false;
        RecentSkills.RemoveAllChildren();
        OpenTreeButton.Disabled = true;
    }
}

internal static class Wh40kClassTreeWindowStatus
{
    public static string GetStatusText(Wh40kClassUiOperationStatus status)
    {
        var key = status switch
        {
            Wh40kClassUiOperationStatus.PurchaseSucceeded => "wh40k-class-ui-status-success",
            Wh40kClassUiOperationStatus.AccountUnavailable => "wh40k-class-tree-error-account-not-found",
            Wh40kClassUiOperationStatus.SkillNotFound => "wh40k-class-tree-error-skill-not-found",
            Wh40kClassUiOperationStatus.ClassMismatch => "wh40k-class-tree-error-class-mismatch",
            Wh40kClassUiOperationStatus.ContentUnavailable => "wh40k-class-tree-error-content-unavailable",
            Wh40kClassUiOperationStatus.InsufficientLevel => "wh40k-class-tree-error-insufficient-level",
            Wh40kClassUiOperationStatus.MissingPrerequisite => "wh40k-class-tree-error-missing-prerequisite",
            Wh40kClassUiOperationStatus.InsufficientPoints => "wh40k-class-tree-error-insufficient-points",
            Wh40kClassUiOperationStatus.AlreadyPurchased => "wh40k-class-tree-error-already-purchased",
            Wh40kClassUiOperationStatus.RevisionMismatch => "wh40k-class-tree-error-revision-mismatch",
            _ => string.Empty,
        };
        return string.IsNullOrEmpty(key) ? string.Empty : Loc.GetString(key);
    }
}
