using Content.Client.PDA;
using Content.Shared._WH40K.Progression;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._WH40K.Progression;

[GenerateTypedNameReferences]
public sealed partial class Wh40kPartyInvitationWindow : DefaultWindow
{
    public Wh40kPartyInvitationWindow()
    {
        RobustXamlLoader.Load(this);
        AcceptButton.StyleBoxOverride = PdaTerminalPalette.CreateButton(accented: true);
        DeclineButton.StyleBoxOverride = PdaTerminalPalette.CreateButton(danger: true);
    }

    public void UpdateState(Wh40kPartyInvitationEuiState state)
    {
        InvitationText.SetMessage(
            Loc.GetString(
                "wh40k-rpg-party-invitation-body",
                ("leader", state.LeaderCkey)),
            Color.FromHex("#D7E0D7"));
        ExpiryText.SetMessage(
            Loc.GetString("wh40k-rpg-party-invitation-expires"),
            Color.FromHex("#93A096"));
    }
}
