using System.Linq;
using System.Text;
using System.Globalization;
using Content.Client.Message;
using Content.Shared.Tag;
using Content.Shared._WH40K.CharacterCreation;
using Content.Shared._WH40K.ClassProgression;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client._WH40K.Progression;

[GenerateTypedNameReferences]
public sealed partial class Wh40kClassTreeWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _prototypes = default!;
    [Dependency] private IEntitySystemManager _entitySystems = default!;

    private readonly SpriteSystem _sprites;

    private Wh40kClassUiSnapshot? _snapshot;
    private string? _selectedSkillId;
    private bool _pending;

    public event Action<string>? SkillSelected;
    public event Action<string>? PurchaseConfirmed;

    public Wh40kClassTreeWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprites = _entitySystems.GetEntitySystem<SpriteSystem>();

        ClassSigil.Texture = _sprites.Frame0(Wh40kClassSkillIconPaths.ClassSigil);

        WindowFrame.PanelOverride = Wh40kClassPalette.CreatePanel();
        GraphPanel.PanelOverride = Wh40kClassPalette.CreatePanel();
        DetailsPanel.PanelOverride = Wh40kClassPalette.CreatePanel(raised: true);
        ConfirmationPanel.PanelOverride = Wh40kClassPalette.CreatePanel();
        LevelPanel.PanelOverride = Wh40kClassPalette.CreatePanel(raised: true);
        ConfirmPurchaseButton.StyleBoxOverride = Wh40kClassPalette.CreateButton(accented: true);
        CancelPurchaseButton.StyleBoxOverride = Wh40kClassPalette.CreateButton(danger: true);
        PurchaseButton.StyleBoxOverride = Wh40kClassPalette.CreateButton(accented: true);
        ClassLevelBar.BackgroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#20211D") };
        ClassLevelBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Wh40kClassPalette.Gold };

        SearchBox.OnTextChanged += args => Graph.SetSearchQuery(args.Text);
        PurchaseButton.OnPressed += _ => BeginConfirmation();
        ConfirmPurchaseButton.OnPressed += _ => ConfirmPurchase();
        CancelPurchaseButton.OnPressed += _ => CancelConfirmation();
        Graph.NodeSelected += SelectSkill;
        Graph.NodeActivated += _ => BeginConfirmation();
        Graph.EscapeRequested += HandleEscape;

        SetUnavailable();
    }

    public void UpdateSnapshot(
        Wh40kClassUiSnapshot? snapshot,
        Wh40kClassUiOperationStatus status,
        string? selectedSkillId)
    {
        _snapshot = snapshot;
        _pending = false;
        StatusLabel.Visible = status != Wh40kClassUiOperationStatus.None;
        StatusLabel.SetMessage(GetStatusText(status), GetStatusColor(status));
        Graph.UpdateSnapshot(snapshot);

        if (snapshot == null)
        {
            SetUnavailable();
            return;
        }

        if (selectedSkillId != null && TryGetSkill(selectedSkillId, out _, out _))
            _selectedSkillId = selectedSkillId;
        else if (_selectedSkillId != null && !TryGetSkill(_selectedSkillId, out _, out _))
            _selectedSkillId = null;

        Graph.SetSelectedSkill(_selectedSkillId);
        UpdateHeader();
        UpdateBonuses();
        UpdateLevelBar();
        UpdateDetails(_selectedSkillId);
        RefreshConfirmation();
    }

    public void SetPending(bool pending)
    {
        _pending = pending;
        RefreshConfirmation();
        PurchaseButton.Disabled = pending || !CanPurchaseSelected();
    }

    public void FocusSpecializationOnOpen(string? specializationId)
    {
        if (specializationId != null)
            Graph.FocusSpecialization(specializationId);
        else
            Graph.FocusTree();
    }

    private void UpdateHeader()
    {
        if (_snapshot == null)
            return;

        PointsHeader.Text = Loc.GetString(
            "wh40k-class-ui-points-header",
            ("available", _snapshot.Tree.AvailableSkillPoints),
            ("earned", _snapshot.Tree.EarnedSkillPoints));
    }

    private void UpdateBonuses()
    {
        BonusList.RemoveAllChildren();
        if (_snapshot == null || _snapshot.Bonuses.Count == 0)
        {
            BonusList.AddChild(new Label
            {
                Text = Loc.GetString("wh40k-class-ui-no-bonuses"),
                FontColorOverride = Wh40kClassPalette.MutedText,
            });
            return;
        }

        foreach (var bonus in _snapshot.Bonuses)
        {
            var skillName = _prototypes.TryIndex<Wh40kClassSkillPrototype>(bonus.SkillId, out var skill)
                ? Loc.GetString(skill.Name)
                : bonus.SkillId;
            var rarity = bonus.AppliedRarityPercent > 0f
                ? Loc.GetString("wh40k-class-ui-bonus-rarity", ("percent", bonus.AppliedRarityPercent))
                : string.Empty;
            BonusList.AddChild(new Label
            {
                Text = Loc.GetString(
                    "wh40k-class-ui-bonus-entry",
                    ("skill", skillName),
                    ("kind", Loc.GetString(GetEffectKindLocId(bonus.Kind))),
                    ("state", Loc.GetString(GetBonusStateLocId(bonus.State))),
                    ("rarity", rarity)),
                FontColorOverride = bonus.State == Wh40kClassBonusActivationState.Active
                    ? Wh40kClassPalette.Text
                    : Wh40kClassPalette.MutedText,
            });
        }
    }

    private void UpdateLevelBar()
    {
        if (_snapshot == null)
            return;

        var level = _snapshot.Tree.CurrentLevel;
        ClassLevelLabel.Text = Loc.GetString(
            "wh40k-class-ui-level",
            ("level", level),
            ("class", GetClassName(_snapshot.Tree.ClassId)));

        if (_snapshot.Tree.CurrentLevelSpanTenths <= 0)
        {
            ClassLevelBar.MaxValue = 1;
            ClassLevelBar.Value = 1;
            ExperienceLabel.Text = Loc.GetString("wh40k-class-ui-experience-maximum");
            ExperienceToNextLabel.Text = Loc.GetString("wh40k-class-ui-level-maximum");
            NextPointLabel.Text = Loc.GetString("wh40k-class-ui-next-point-maximum");
            return;
        }

        var span = _snapshot.Tree.CurrentLevelSpanTenths;
        var current = Math.Clamp(_snapshot.Tree.CurrentLevelExperienceTenths, 0, span);
        ClassLevelBar.MaxValue = span;
        ClassLevelBar.Value = current;
        ExperienceLabel.Text = Loc.GetString(
            "wh40k-class-ui-experience-progress",
            ("current", FormatExperience(current)),
            ("required", FormatExperience(span)));
        ExperienceToNextLabel.Text = Loc.GetString(
            "wh40k-class-ui-experience-remaining",
            ("remaining", FormatExperience(_snapshot.Tree.ExperienceToNextLevelTenths)));
        NextPointLabel.Text = Loc.GetString(
            "wh40k-class-ui-next-point",
            ("level", (level / 5 + 1) * 5));
    }

    private void SelectSkill(string skillId)
    {
        _selectedSkillId = skillId;
        CancelConfirmation();
        UpdateHeader();
        UpdateDetails(skillId);
        SkillSelected?.Invoke(skillId);
    }

    private void UpdateDetails(string? skillId)
    {
        if (skillId == null || !TryGetSkill(skillId, out var skill, out var state))
        {
            SkillIcon.Texture = null;
            SkillTitle.Text = Loc.GetString("wh40k-class-ui-no-selection");
            SkillMeta.Text = string.Empty;
            SkillDescription.Clear();
            RequirementCostLabel.Text = string.Empty;
            RequirementLevelLabel.Text = string.Empty;
            RequirementPrerequisiteLabel.Text = string.Empty;
            RequirementEquipmentLabel.Text = string.Empty;
            SkillEffects.Clear();
            PurchaseButton.Disabled = true;
            return;
        }

        SkillIcon.Texture = _sprites.Frame0(Wh40kClassSkillIconPaths.GetSpecifier(skill));
        SkillTitle.Text = Loc.GetString(skill.Name);
        SkillMeta.Text = Loc.GetString(
            "wh40k-class-ui-node-meta",
            ("kind", Loc.GetString(Wh40kClassTreeGraphControl.GetKindLocId(skill.Kind))),
            ("state", Loc.GetString(Wh40kClassTreeGraphControl.GetStateLocId(state))));
        SkillDescription.SetMarkup(Loc.GetString(skill.Description));

        var prerequisite = skill.Prerequisite is { } prerequisiteId &&
                           _prototypes.TryIndex(prerequisiteId, out Wh40kClassSkillPrototype? prerequisiteSkill)
            ? Loc.GetString(prerequisiteSkill.Name)
            : Loc.GetString("wh40k-class-ui-condition-none");
        var equipment = skill.RequiredEquipmentTags.Count == 0
            ? Loc.GetString("wh40k-class-ui-condition-none")
            : string.Join(", ", skill.RequiredEquipmentTags.Select(GetEquipmentName));
        RequirementCostLabel.Text = Loc.GetString("wh40k-class-ui-requirement-cost", ("cost", skill.Cost));
        RequirementLevelLabel.Text = Loc.GetString("wh40k-class-ui-requirement-level", ("level", skill.MinimumLevel));
        RequirementPrerequisiteLabel.Text = Loc.GetString("wh40k-class-ui-requirement-prerequisite", ("skill", prerequisite));
        RequirementEquipmentLabel.Text = Loc.GetString("wh40k-class-ui-requirement-equipment", ("equipment", equipment));

        var effects = skill.Effects
            .Select(effectId => _prototypes.TryIndex(effectId, out Wh40kClassSkillEffectPrototype? effect)
                ? Loc.GetString(GetEffectKindLocId(effect.Kind))
                : effectId.Id)
            .ToArray();
        SkillEffects.SetMessage(
            Loc.GetString("wh40k-class-ui-effects", ("effects", string.Join(", ", effects))),
            Wh40kClassPalette.Text);
        PurchaseButton.Disabled = _pending || skillId != _selectedSkillId || state != Wh40kClassSkillNodeState.Available;
    }

    private void BeginConfirmation()
    {
        if (_pending || !CanPurchaseSelected() || _selectedSkillId == null)
            return;

        ConfirmationPanel.Visible = true;
        ConfirmationActions.Visible = true;
        RefreshConfirmation();
        ConfirmPurchaseButton.GrabKeyboardFocus();
    }

    private void ConfirmPurchase()
    {
        if (_pending || !CanPurchaseSelected() || _selectedSkillId == null)
            return;

        PurchaseConfirmed?.Invoke(_selectedSkillId);
    }

    private void CancelConfirmation()
    {
        ConfirmationPanel.Visible = false;
        ConfirmationActions.Visible = false;
    }

    private void RefreshConfirmation()
    {
        if (!ConfirmationPanel.Visible || _selectedSkillId == null ||
            !TryGetSkill(_selectedSkillId, out var skill, out var state))
        {
            return;
        }

        var remaining = Math.Max(0, (_snapshot?.Tree.AvailableSkillPoints ?? 0) - skill.Cost);
        var effects = skill.Effects
            .Select(effectId => _prototypes.TryIndex(effectId, out Wh40kClassSkillEffectPrototype? effect)
                ? Loc.GetString(GetEffectKindLocId(effect.Kind))
                : effectId.Id)
            .ToArray();
        ConfirmationText.SetMessage(
            Loc.GetString(
                "wh40k-class-ui-confirmation",
                ("skill", Loc.GetString(skill.Name)),
                ("cost", skill.Cost),
                ("remaining", remaining),
                ("effects", string.Join(", ", effects)),
                ("state", Loc.GetString(Wh40kClassTreeGraphControl.GetStateLocId(state)))),
            Wh40kClassPalette.Text);
        ConfirmPurchaseButton.Disabled = _pending || state != Wh40kClassSkillNodeState.Available;
        CancelPurchaseButton.Disabled = _pending;
    }

    private bool CanPurchaseSelected()
    {
        return _selectedSkillId != null &&
               TryGetSkill(_selectedSkillId, out _, out var state) &&
               state == Wh40kClassSkillNodeState.Available;
    }

    private bool TryGetSkill(
        string skillId,
        out Wh40kClassSkillPrototype skill,
        out Wh40kClassSkillNodeState state)
    {
        skill = default!;
        state = default;
        if (_snapshot == null ||
            !_prototypes.TryIndex<Wh40kClassSkillPrototype>(skillId, out var prototype) ||
            prototype == null)
            return false;

        skill = prototype;

        var found = Wh40kClassUiModel.GetNodeState(_snapshot, skillId);
        if (found == null)
            return false;

        state = found.Value;
        return true;
    }

    private void HandleEscape()
    {
        if (ConfirmationPanel.Visible)
            CancelConfirmation();
        else
            Close();
    }

    private void SetUnavailable()
    {
        PointsHeader.Text = string.Empty;
        PurchaseButton.Disabled = true;
        BonusList.RemoveAllChildren();
        ClassLevelLabel.Text = string.Empty;
        ExperienceLabel.Text = string.Empty;
        ExperienceToNextLabel.Text = string.Empty;
        NextPointLabel.Text = string.Empty;
        ClassLevelBar.Value = 0;
        UpdateDetails(null);
        CancelConfirmation();
    }

    private string GetClassName(string classId)
    {
        return _prototypes.TryIndex<Wh40kCharacterClassPrototype>(classId, out var characterClass)
            ? Loc.GetString(characterClass.Name)
            : classId;
    }

    private string GetEquipmentName(ProtoId<TagPrototype> tag)
    {
        var key = tag.Id switch
        {
            "Wh40kSkillShield" => "wh40k-class-ui-equipment-shield",
            "Wh40kSkillLightMelee" => "wh40k-class-ui-equipment-light-melee",
            "Wh40kSkillAutomaticWeapon" => "wh40k-class-ui-equipment-automatic-weapon",
            "Wh40kSkillMarksmanWeapon" => "wh40k-class-ui-equipment-marksman-weapon",
            "Wh40kSkillMedicalItem" => "wh40k-class-ui-equipment-medical-item",
            "Wh40kSkillTool" => "wh40k-class-ui-equipment-tool",
            "Wh40kMedicalNode" => "wh40k-class-ui-equipment-medical-node",
            "Wh40kClassHackable" => "wh40k-class-ui-equipment-hackable-device",
            "Wh40kSkillDistraction" => "wh40k-class-ui-equipment-distraction-device",
            "Wh40kSkillPoison" => "wh40k-class-ui-equipment-poison",
            "Wh40kCommandBeaconConsumable" => "wh40k-class-ui-equipment-command-beacon",
            _ => "wh40k-class-ui-equipment-generic",
        };
        return key == "wh40k-class-ui-equipment-generic"
            ? Loc.GetString(key)
            : Loc.GetString(key);
    }

    private static string FormatExperience(long tenths)
    {
        var experience = tenths / 10m;
        return experience == decimal.Truncate(experience)
            ? experience.ToString("0", CultureInfo.CurrentCulture)
            : experience.ToString("0.#", CultureInfo.CurrentCulture);
    }

    private static string GetStatusText(Wh40kClassUiOperationStatus status)
    {
        var key = status switch
        {
            Wh40kClassUiOperationStatus.PurchaseSucceeded => "wh40k-class-ui-status-success",
            Wh40kClassUiOperationStatus.AccountUnavailable => "wh40k-class-tree-error-account-not-found",
            Wh40kClassUiOperationStatus.SkillNotFound => "wh40k-class-tree-error-skill-not-found",
            Wh40kClassUiOperationStatus.ClassMismatch => "wh40k-class-tree-error-class-mismatch",
            Wh40kClassUiOperationStatus.ContentUnavailable => "wh40k-class-tree-error-content-unavailable",
            Wh40kClassUiOperationStatus.InsufficientLevel => "wh40k-class-tree-error-insufficient-level",
            Wh40kClassUiOperationStatus.MissingPrerequisite => "wh40k-class-tree-error-missing-prerequisite",
            Wh40kClassUiOperationStatus.InsufficientPoints => "wh40k-class-tree-error-insufficient-points",
            Wh40kClassUiOperationStatus.AlreadyPurchased => "wh40k-class-tree-error-already-purchased",
            Wh40kClassUiOperationStatus.RevisionMismatch => "wh40k-class-tree-error-revision-mismatch",
            _ => string.Empty,
        };
        return string.IsNullOrEmpty(key) ? string.Empty : Loc.GetString(key);
    }

    private static Color GetStatusColor(Wh40kClassUiOperationStatus status)
    {
        return status is Wh40kClassUiOperationStatus.None or Wh40kClassUiOperationStatus.PurchaseSucceeded
            ? Wh40kClassPalette.Gold
            : Wh40kClassPalette.Danger;
    }

    private static string GetEffectKindLocId(Wh40kClassSkillEffectKind kind)
    {
        return $"wh40k-class-ui-effect-{kind.ToString().ToLowerInvariant()}";
    }

    private static string GetBonusStateLocId(Wh40kClassBonusActivationState state)
    {
        return state switch
        {
            Wh40kClassBonusActivationState.Active => "wh40k-class-ui-bonus-active",
            Wh40kClassBonusActivationState.MissingEquipment => "wh40k-class-ui-bonus-missing-equipment",
            _ => "wh40k-class-ui-bonus-content-unavailable",
        };
    }
}
