using Content.Client.Administration.UI.CustomControls;
using Content.Shared._WH40K.Administration.Mute;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.BanList.Mutes;

[GenerateTypedNameReferences]
public sealed partial class MuteListControl : Control
{
    public const int HistoryPageSize = 100;
    public event Action<int>? PageRequested;
    private int _historyOffset;

    public MuteListControl()
    {
        RobustXamlLoader.Load(this);
        PreviousPageButton.OnPressed += _ => PageRequested?.Invoke(Math.Max(0, _historyOffset - HistoryPageSize));
        NextPageButton.OnPressed += _ => PageRequested?.Invoke(_historyOffset + HistoryPageSize);
    }

    public void SetMutes(List<WH40KSharedMute> mutes, int historyOffset, bool hasNextPage)
    {
        _historyOffset = historyOffset;
        PreviousPageButton.Disabled = historyOffset == 0;
        NextPageButton.Disabled = !hasNextPage;
        PageLabel.Text = Loc.GetString("wh40k-mute-list-page", ("page", historyOffset / HistoryPageSize + 1));

        for (var i = Mutes.ChildCount - 1; i >= 1; i--)
        {
            Mutes.GetChild(i).Orphan();
        }

        foreach (var mute in mutes)
        {
            Mutes.AddChild(new HSeparator());
            Mutes.AddChild(new MuteListLine(mute));
        }
    }
}
