using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.BanList.Mutes;

[GenerateTypedNameReferences]
public sealed partial class MuteListHeader : ContainerButton
{
    public MuteListHeader()
    {
        RobustXamlLoader.Load(this);
    }
}
