using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.PDA;

[GenerateTypedNameReferences]
public sealed partial class PdaProgramItem : ContainerButton
{
    public const string StylePropertyBgColor = "backgroundColor";
    public const string NormalBgColor = "#222A25";
    public const string HoverColor = "#30483B";

    private readonly StyleBoxFlat _styleBox = new()
    {
        BackgroundColor = PdaTerminalPalette.ScreenPanel,
        BorderColor = PdaTerminalPalette.Rail,
        BorderThickness = new Thickness(1),
    };

    public Color BackgroundColor
    {
        get => _styleBox.BackgroundColor;
        set => _styleBox.BackgroundColor = value;
    }

    public PdaProgramItem()
    {
        RobustXamlLoader.Load(this);
        Panel.PanelOverride = _styleBox;
        IconPlate.PanelOverride = new PdaTerminalCutCornerStyleBox
        {
            BackgroundColor = PdaTerminalPalette.RaisedPanel,
            BorderColor = PdaTerminalPalette.AccentMuted,
            BorderThickness = new Thickness(1),
            CornerCut = 5f
        };

        // AnimatedTextureRect is a wrapper around a separate TextureRect. Without an
        // explicit layout for that inner control, every RSI frame is drawn from the
        // wrapper's top-left corner instead of from the centre of the icon plate.
        Icon.DisplayRect.HorizontalExpand = true;
        Icon.DisplayRect.VerticalExpand = true;
        Icon.DisplayRect.CanShrink = true;
        Icon.DisplayRect.Stretch = TextureRect.StretchMode.KeepAspectCentered;

        InstallButton.StyleBoxOverride = PdaTerminalPalette.CreateButton(accented: true);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (TryGetStyleProperty<Color>(StylePropertyBgColor, out var bgColor))
            BackgroundColor = bgColor;

    }
}
