using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.PDA;

[Virtual]
[GenerateTypedNameReferences]
public partial class PdaWindow : BaseWindow
{

    public string? BorderColor
    {
        get => DataslateFrame.ActualModulateSelf.ToHex();

        set => DataslateFrame.ModulateSelfOverride = Color.FromHex(value, Color.White);
    }

    public string? AccentHColor
    {
        get => AccentH.ActualModulateSelf.ToHex();

        set
        {
            AccentH.ModulateSelfOverride = Color.FromHex(value, Color.White);
            AccentH.Visible = value != null;
        }
    }

    public string? AccentVColor
    {
        get => AccentV.ActualModulateSelf.ToHex();

        set
        {
            AccentV.ModulateSelfOverride = Color.FromHex(value, Color.White);
            AccentV.Visible = value != null;
        }
    }

    public PdaWindow()
    {
        RobustXamlLoader.Load(this);

        Background.PanelOverride = PdaTerminalPalette.CreatePanel(
            Color.Transparent,
            Color.Transparent,
            new Thickness(0));
        Border.PanelOverride = PdaTerminalPalette.CreatePanel(
            PdaTerminalPalette.Bezel,
            PdaTerminalPalette.Rail,
            new Thickness(2));
        Border.Visible = false;
        ContentBorder.PanelOverride = new PdaTerminalCutCornerStyleBox
        {
            BackgroundColor = PdaTerminalPalette.Screen,
            BorderColor = PdaTerminalPalette.Rail,
            BorderThickness = new Thickness(0),
            CornerCut = 30f
        };
        ContentBackground.PanelOverride = new PdaTerminalCutCornerStyleBox
        {
            BackgroundColor = PdaTerminalPalette.Screen,
            BorderColor = PdaTerminalPalette.Screen,
            BorderThickness = new Thickness(0),
            CornerCut = 26f
        };
        AccentH.PanelOverride = PdaTerminalPalette.CreatePanel(
            PdaTerminalPalette.AccentMuted,
            PdaTerminalPalette.AccentMuted);
        AccentV.PanelOverride = PdaTerminalPalette.CreatePanel(
            PdaTerminalPalette.AccentMuted,
            PdaTerminalPalette.AccentMuted);

        CloseButton.OnPressed += _ => Close();
        XamlChildren = ContentsContainer.Children;

        AccentH.Visible = false;
        AccentV.Visible = false;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.Move;
    }
}
