using Content.Shared.CCVar;
using Content.Shared.Preferences;
using Content.Shared._WH40K.CharacterDescription;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Content.Client.Stylesheets;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client._WH40K.CharacterDescription;

[GenerateTypedNameReferences]
public sealed partial class Wh40kExtendedDescription : Control
{
    [Dependency] private readonly IConfigurationManager _config = default!;

    private bool _settingProfile;
    private readonly Action<bool> _onSectionConfigurationChanged;
    private readonly Action<int> _onLengthConfigurationChanged;

    public event Action<string>? OnFlavorTextChanged;
    public event Action<string>? OnOocFlavorTextChanged;
    public event Action<string>? OnCharacterFlavorTextChanged;
    public event Action<string>? OnGreenFlavorTextChanged;
    public event Action<string>? OnYellowFlavorTextChanged;
    public event Action<string>? OnRedFlavorTextChanged;
    public event Action<string>? OnTagsFlavorTextChanged;
    public event Action<string>? OnLinksFlavorTextChanged;
    public event Action<bool>? OnShareOocFlavorTextChanged;
    public event Action<bool>? OnShareLinksFlavorTextChanged;
    public event Action<bool>? OnSharePreferencesFlavorTextChanged;

    public Wh40kExtendedDescription()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _onSectionConfigurationChanged = _ => UpdateSectionVisibility();
        _onLengthConfigurationChanged = _ => UpdateCharacterCounters();

        _config.OnValueChanged(CCVars.FlavorTraitsEnabled, _onSectionConfigurationChanged, true);
        _config.OnValueChanged(CCVars.FlavorOocEnabled, _onSectionConfigurationChanged, true);
        _config.OnValueChanged(CCVars.FlavorLinksEnabled, _onSectionConfigurationChanged, true);
        _config.OnValueChanged(CCVars.FlavorGyrEnabled, _onSectionConfigurationChanged, true);
        _config.OnValueChanged(CCVars.CharacterDescriptionLength, _onLengthConfigurationChanged, true);
        _config.OnValueChanged(CCVars.OocFlavorTextLength, _onLengthConfigurationChanged, true);
        _config.OnValueChanged(CCVars.FlavorTagsLength, _onLengthConfigurationChanged, true);
        _config.OnValueChanged(CCVars.FlavorLinksLength, _onLengthConfigurationChanged, true);
        _config.OnValueChanged(CCVars.GreenPreferencesLength, _onLengthConfigurationChanged, true);
        _config.OnValueChanged(CCVars.YellowPreferencesLength, _onLengthConfigurationChanged, true);
        _config.OnValueChanged(CCVars.RedPreferencesLength, _onLengthConfigurationChanged, true);

        AppearanceInput.Placeholder = new Rope.Leaf(Loc.GetString("flavor-text-placeholder"));
        CharacterInput.Placeholder = new Rope.Leaf(Loc.GetString("character-flavor-text-placeholder"));
        OocInput.Placeholder = new Rope.Leaf(Loc.GetString("ooc-flavor-text-placeholder"));
        TagsInput.Placeholder = new Rope.Leaf(Loc.GetString("tags-flavor-text-placeholder"));
        LinksInput.Placeholder = new Rope.Leaf(Loc.GetString("links-flavor-text-placeholder"));
        GreenInput.Placeholder = new Rope.Leaf(Loc.GetString("green-flavor-text-placeholder"));
        YellowInput.Placeholder = new Rope.Leaf(Loc.GetString("yellow-flavor-text-placeholder"));
        RedInput.Placeholder = new Rope.Leaf(Loc.GetString("red-flavor-text-placeholder"));

        AppearanceInput.OnTextChanged += _ => OnTextChanged(AppearanceInput, OnFlavorTextChanged);
        OocInput.OnTextChanged += _ => OnTextChanged(OocInput, OnOocFlavorTextChanged);
        CharacterInput.OnTextChanged += _ => OnTextChanged(CharacterInput, OnCharacterFlavorTextChanged);
        GreenInput.OnTextChanged += _ => OnTextChanged(GreenInput, OnGreenFlavorTextChanged);
        YellowInput.OnTextChanged += _ => OnTextChanged(YellowInput, OnYellowFlavorTextChanged);
        RedInput.OnTextChanged += _ => OnTextChanged(RedInput, OnRedFlavorTextChanged);
        TagsInput.OnTextChanged += _ => OnTextChanged(TagsInput, OnTagsFlavorTextChanged);
        LinksInput.OnTextChanged += _ => OnTextChanged(LinksInput, OnLinksFlavorTextChanged);
        ShareOocCheck.OnToggled += args => OnVisibilityChanged(args.Pressed, OnShareOocFlavorTextChanged);
        ShareLinksCheck.OnToggled += args => OnVisibilityChanged(args.Pressed, OnShareLinksFlavorTextChanged);
        SharePreferencesCheck.OnToggled += args => OnVisibilityChanged(args.Pressed, OnSharePreferencesFlavorTextChanged);

        DescriptionTabs.SetTabTitle(0, Loc.GetString("flavor-tab-flavor"));
        DescriptionTabs.SetTabTitle(1, Loc.GetString("flavor-tab-character"));
        DescriptionTabs.SetTabTitle(2, Loc.GetString("flavor-tab-ooc-flavor"));
        DescriptionTabs.SetTabTitle(3, Loc.GetString("flavor-tab-gyr"));
        DescriptionTabs.SetTabTitle(4, Loc.GetString("flavor-tab-preview"));

        PreviewTabs.SetTabTitle(0, Loc.GetString("flavor-tab-flavor"));
        PreviewTabs.SetTabTitle(1, Loc.GetString("flavor-tab-character"));
        PreviewTabs.SetTabTitle(2, Loc.GetString("flavor-tab-gyr"));

        SetPreviewText(PreviewAppearance, string.Empty, "detail-examinable-empty-flavor");
        SetPreviewText(PreviewTraits, string.Empty, "detail-examinable-empty-character");
        SetPreviewText(PreviewOoc, string.Empty, "detail-examinable-empty-ooc");
        SetPreviewText(PreviewGreen, string.Empty, "detail-examinable-empty-green");
        SetPreviewText(PreviewYellow, string.Empty, "detail-examinable-empty-yellow");
        SetPreviewText(PreviewRed, string.Empty, "detail-examinable-empty-red");
        UpdateCharacterCounters();
    }

    public void SetProfile(HumanoidCharacterProfile? profile)
    {
        _settingProfile = true;
        try
        {
            AppearanceInput.TextRope = new Rope.Leaf(profile?.FlavorText ?? string.Empty);
            OocInput.TextRope = new Rope.Leaf(profile?.OocFlavorText ?? string.Empty);
            CharacterInput.TextRope = new Rope.Leaf(profile?.CharacterFlavorText ?? string.Empty);
            GreenInput.TextRope = new Rope.Leaf(profile?.GreenFlavorText ?? string.Empty);
            YellowInput.TextRope = new Rope.Leaf(profile?.YellowFlavorText ?? string.Empty);
            RedInput.TextRope = new Rope.Leaf(profile?.RedFlavorText ?? string.Empty);
            TagsInput.TextRope = new Rope.Leaf(profile?.TagsFlavorText ?? string.Empty);
            LinksInput.TextRope = new Rope.Leaf(profile?.LinksFlavorText ?? string.Empty);
            ShareOocCheck.Pressed = profile?.ShareOocFlavorText ?? true;
            ShareLinksCheck.Pressed = profile?.ShareLinksFlavorText ?? true;
            SharePreferencesCheck.Pressed = profile?.SharePreferencesFlavorText ?? true;
        }
        finally
        {
            _settingProfile = false;
        }

        PreviewName.Text = profile?.Name ?? string.Empty;
        PreviewSummary.Text = profile is null ? string.Empty : profile.Summary;
        UpdatePreview();
        UpdateCharacterCounters();
    }

    public void SetPreviewEntity(EntityUid entity)
    {
        PreviewSprite.SetEntity(entity);
    }

    public void SetPortrait(Texture? portrait)
    {
        PreviewPortrait.Texture = portrait;
    }

    private void OnTextChanged(TextEdit input, Action<string>? callback)
    {
        if (_settingProfile)
            return;

        callback?.Invoke(Rope.Collapse(input.TextRope).Trim());
        UpdatePreview();
        UpdateCharacterCounters();
    }

    private void OnVisibilityChanged(bool share, Action<bool>? callback)
    {
        if (_settingProfile)
            return;

        callback?.Invoke(share);
    }

    private void UpdateSectionVisibility()
    {
        var showTraits = _config.GetCVar(CCVars.FlavorTraitsEnabled);
        var showOoc = _config.GetCVar(CCVars.FlavorOocEnabled);
        var showLinks = _config.GetCVar(CCVars.FlavorLinksEnabled);
        var showPreferences = _config.GetCVar(CCVars.FlavorGyrEnabled);

        DescriptionTabs.SetTabVisible(1, showTraits);
        DescriptionTabs.SetTabVisible(2, showOoc || showLinks);
        DescriptionTabs.SetTabVisible(3, showPreferences);
        LinksEditor.Visible = showLinks;
        OocInput.Visible = showOoc;
        ShareOocCheck.Visible = showOoc;
        ShareLinksCheck.Visible = showLinks;
        SharePreferencesCheck.Visible = showPreferences;

        PreviewTabs.SetTabVisible(1, showTraits);
        PreviewTabs.SetTabVisible(2, showPreferences);
        PreviewOocSection.Visible = showOoc;
        PreviewLinksSection.Visible = showLinks;

        if (DescriptionTabs.CurrentTab == 1 && !showTraits ||
            DescriptionTabs.CurrentTab == 2 && !showOoc && !showLinks ||
            DescriptionTabs.CurrentTab == 3 && !showPreferences)
        {
            DescriptionTabs.CurrentTab = 0;
        }

        if (PreviewTabs.CurrentTab == 1 && !showTraits ||
            PreviewTabs.CurrentTab == 2 && !showPreferences)
        {
            PreviewTabs.CurrentTab = 0;
        }
    }

    private void UpdatePreview()
    {
        SetPreviewText(PreviewAppearance, TextOf(AppearanceInput), "detail-examinable-empty-flavor");
        SetPreviewText(PreviewTraits, TextOf(CharacterInput), "detail-examinable-empty-character");
        SetPreviewText(PreviewOoc, TextOf(OocInput), "detail-examinable-empty-ooc");
        SetPreviewText(PreviewGreen, TextOf(GreenInput), "detail-examinable-empty-green");
        SetPreviewText(PreviewYellow, TextOf(YellowInput), "detail-examinable-empty-yellow");
        SetPreviewText(PreviewRed, TextOf(RedInput), "detail-examinable-empty-red");
        PreviewTags.Text = TextOf(TagsInput);
        UpdateLinks(TextOf(LinksInput));
    }

    private void UpdateLinks(string linksText)
    {
        PreviewLinks.RemoveAllChildren();
        if (string.IsNullOrWhiteSpace(linksText))
        {
            PreviewLinks.AddChild(new Label
            {
                Text = Loc.GetString("detail-examinable-empty-links"),
                HorizontalAlignment = HAlignment.Center,
            });
            return;
        }

        foreach (var link in linksText.Split(new[] { ',', ' ', '\n', '\r', '\t' }, StringSplitOptions.RemoveEmptyEntries))
        {
            var text = link.Trim();
            if (IsExternalLink(text))
            {
                var button = new Button
                {
                    Text = GetLinkDisplayText(text),
                    ToolTip = Loc.GetString("humanoid-profile-editor-link-tooltip", ("url", text)),
                    HorizontalExpand = true,
                    HorizontalAlignment = HAlignment.Center,
                    StyleClasses = { StyleBase.ButtonOpenBoth },
                };
                button.OnPressed += _ => OpenLink(text);
                PreviewLinks.AddChild(button);
            }
            else
            {
                PreviewLinks.AddChild(new Label
                {
                    Text = text,
                    HorizontalExpand = true,
                    HorizontalAlignment = HAlignment.Center,
                    FontColorOverride = Color.Gray,
                });
            }
        }
    }

    private static bool IsExternalLink(string link)
    {
        return link.StartsWith("http://", StringComparison.OrdinalIgnoreCase) ||
               link.StartsWith("https://", StringComparison.OrdinalIgnoreCase) ||
               link.StartsWith("www.", StringComparison.OrdinalIgnoreCase);
    }

    private static string GetLinkDisplayText(string link)
    {
        return link.Length > 40 ? link[..37] + "..." : link;
    }

    private static void OpenLink(string link)
    {
        if (link.StartsWith("www.", StringComparison.OrdinalIgnoreCase))
            link = "https://" + link;

        IoCManager.Resolve<IUriOpener>().OpenUri(link);
    }

    private static string TextOf(TextEdit input)
    {
        return Rope.Collapse(input.TextRope).Trim();
    }

    private void UpdateCharacterCounters()
    {
        SetCharacterCounter(AppearanceCounter, AppearanceInput, HumanoidCharacterProfile.MaxDescLength);
        SetCharacterCounter(CharacterCounter, CharacterInput, _config.GetCVar(CCVars.CharacterDescriptionLength));
        SetCharacterCounter(OocCounter, OocInput, _config.GetCVar(CCVars.OocFlavorTextLength));
        SetCharacterCounter(TagsCounter, TagsInput, _config.GetCVar(CCVars.FlavorTagsLength));
        SetCharacterCounter(LinksCounter, LinksInput, _config.GetCVar(CCVars.FlavorLinksLength));
        SetCharacterCounter(GreenCounter, GreenInput, _config.GetCVar(CCVars.GreenPreferencesLength));
        SetCharacterCounter(YellowCounter, YellowInput, _config.GetCVar(CCVars.YellowPreferencesLength));
        SetCharacterCounter(RedCounter, RedInput, _config.GetCVar(CCVars.RedPreferencesLength));
    }

    private static void SetCharacterCounter(Label counter, TextEdit input, int maxLength)
    {
        var currentLength = Rope.Collapse(input.TextRope).Length;
        var limitExceeded = currentLength > maxLength;
        counter.Text = Loc.GetString(
            "wh40k-description-character-count",
            ("current", currentLength),
            ("maximum", maxLength));
        counter.FontColorOverride = limitExceeded ? Color.FromHex("#D45B5B") : null;
        counter.ToolTip = limitExceeded
            ? Loc.GetString("wh40k-description-character-limit-exceeded")
            : null;
    }

    private static void SetPreviewText(RichTextLabel label, string content, string emptyKey)
    {
        var text = string.IsNullOrWhiteSpace(content) ? Loc.GetString(emptyKey) : content;
        var sanitized = Wh40kDescriptionMarkup.SanitizeBasic(text);
        label.SetMessage(FormattedMessage.FromMarkupPermissive(sanitized), Wh40kDescriptionMarkupTags.Basic);
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            _config.UnsubValueChanged(CCVars.FlavorTraitsEnabled, _onSectionConfigurationChanged);
            _config.UnsubValueChanged(CCVars.FlavorOocEnabled, _onSectionConfigurationChanged);
            _config.UnsubValueChanged(CCVars.FlavorLinksEnabled, _onSectionConfigurationChanged);
            _config.UnsubValueChanged(CCVars.FlavorGyrEnabled, _onSectionConfigurationChanged);
            _config.UnsubValueChanged(CCVars.CharacterDescriptionLength, _onLengthConfigurationChanged);
            _config.UnsubValueChanged(CCVars.OocFlavorTextLength, _onLengthConfigurationChanged);
            _config.UnsubValueChanged(CCVars.FlavorTagsLength, _onLengthConfigurationChanged);
            _config.UnsubValueChanged(CCVars.FlavorLinksLength, _onLengthConfigurationChanged);
            _config.UnsubValueChanged(CCVars.GreenPreferencesLength, _onLengthConfigurationChanged);
            _config.UnsubValueChanged(CCVars.YellowPreferencesLength, _onLengthConfigurationChanged);
            _config.UnsubValueChanged(CCVars.RedPreferencesLength, _onLengthConfigurationChanged);
        }

        base.Dispose(disposing);
    }
}
