using Content.Client.Info;
using Content.Client.Info.PlaytimeStats;
using Content.Client.Resources;
using Content.Client.Administration.Managers;
using Content.Client._WH40K.MetaProgress;
using Content.Shared.CCVar;
using Content.Shared.Administration;
using Content.Shared._WH40K.CharacterCreation;
using Content.Shared._WH40K.MetaProgress;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Client.Lobby.UI
{
    /// <summary>
    /// Holds the entire character setup GUI, from character picks to individual character editing.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class CharacterSetupGui : Control
    {
        [Dependency] private IClientPreferencesManager _preferencesManager = default!;
        [Dependency] private IEntityManager _entManager = default!;
        [Dependency] private IPrototypeManager _protomanager = default!;
        [Dependency] private IResourceCache _resourceCache = default!;
        [Dependency] private IConfigurationManager _cfg = default!;
        [Dependency] private IClientAdminManager _adminManager = default!;

        private readonly Button _createNewCharacterButton;
        private BaseWindow? _decorationsWindow;

        public event Action<int>? SelectCharacter;
        public event Action<int>? DeleteCharacter;

        public CharacterSetupGui(HumanoidProfileEditor profileEditor)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            var panelTex = _resourceCache.GetTexture("/Textures/Interface/Nano/button.svg.96dpi.png");
            var back = new StyleBoxTexture
            {
                Texture = panelTex,
                Modulate = new Color(37, 37, 42)
            };
            back.SetPatchMargin(StyleBox.Margin.All, 10);

            BackgroundPanel.PanelOverride = back;

            _createNewCharacterButton = new Button
            {
                Text = Loc.GetString("character-setup-gui-create-new-character-button"),
            };

            _createNewCharacterButton.OnPressed += args =>
            {
                if (!CanModifyCharacterSlots)
                    return;

                _preferencesManager.CreateCharacter(HumanoidCharacterProfile.Random());
                ReloadCharacterPickers();
                args.Event.Handle();
            };

            CharEditor.AddChild(profileEditor);
            RulesButton.OnPressed += _ => new RulesAndInfoWindow().Open();

            StatsButton.OnPressed += _ => new PlaytimeStatsWindow().OpenCentered();
            DecorationsButton.OnPressed += _ =>
            {
                if (CanUseDecorations)
                    OpenOrFocus(ref _decorationsWindow, () => new PlayerDecorationsWindow());
            };

            _cfg.OnValueChanged(CCVars.SeeOwnNotes, p => AdminRemarksButton.Visible = p, true);
            _cfg.OnValueChanged(CCVars.Wh40kDecorationsMode, OnDecorationsModeChanged, true);
            _adminManager.AdminStatusUpdated += RefreshDecorationsButton;
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (!disposing)
                return;

            _cfg.UnsubValueChanged(CCVars.Wh40kDecorationsMode, OnDecorationsModeChanged);
            _adminManager.AdminStatusUpdated -= RefreshDecorationsButton;
            _decorationsWindow?.Dispose();
            _decorationsWindow = null;
        }

        private static void OpenOrFocus(ref BaseWindow? window, Func<BaseWindow> factory)
        {
            if (window?.IsOpen == true)
            {
                window.MoveToFront();
                return;
            }

            window = factory();
            window.OpenCentered();
        }

        /// <summary>
        /// Disposes and reloads all character picker buttons from the preferences data.
        /// </summary>
        public void ReloadCharacterPickers()
        {
            _createNewCharacterButton.Orphan();
            Characters.DisposeAllChildren();

            var numberOfFullSlots = 0;
            var characterButtonsGroup = new ButtonGroup();

            if (!_preferencesManager.ServerDataLoaded)
            {
                return;
            }

            _createNewCharacterButton.ToolTip =
                Loc.GetString("character-setup-gui-create-new-character-button-tooltip",
                    ("maxCharacters", _preferencesManager.Settings!.MaxCharacterSlots));

            var selectedSlot = _preferencesManager.Preferences?.SelectedCharacterIndex;

            foreach (var (slot, character) in _preferencesManager.Preferences!.Characters)
            {
                numberOfFullSlots++;
                var characterPickerButton = new CharacterPickerButton(_entManager,
                    _protomanager,
                    characterButtonsGroup,
                    character,
                    slot == selectedSlot,
                    CanModifyCharacterSlots);

                Characters.AddChild(characterPickerButton);

                characterPickerButton.OnPressed += args =>
                {
                    SelectCharacter?.Invoke(slot);
                };

                characterPickerButton.OnDeletePressed += () =>
                {
                    DeleteCharacter?.Invoke(slot);
                };
            }

            _createNewCharacterButton.Disabled = !CanModifyCharacterSlots ||
                                                 numberOfFullSlots >= _preferencesManager.Settings.MaxCharacterSlots;
            Characters.AddChild(_createNewCharacterButton);
        }

        private bool CanModifyCharacterSlots =>
            Wh40kProfileEditPolicy.ParseMode(_cfg.GetCVar(CCVars.Wh40kProfileEditMode)) == Wh40kProfileEditMode.Disabled ||
            (_cfg.GetCVar(CCVars.Wh40kProfileEditAdminBypass) &&
             _adminManager.IsActive() &&
             (_adminManager.HasFlag(AdminFlags.Admin) || _adminManager.HasFlag(AdminFlags.Moderator)));

        private bool CanUseDecorations
        {
            get
            {
                return WH40KDecorationAccessPolicy.ParseMode(_cfg.GetCVar(CCVars.Wh40kDecorationsMode)) switch
                {
                    WH40KDecorationAccessMode.All => true,
                    WH40KDecorationAccessMode.Admins => _adminManager.IsActive() &&
                                                        (_adminManager.HasFlag(AdminFlags.Admin) ||
                                                         _adminManager.HasFlag(AdminFlags.Moderator)),
                    _ => false,
                };
            }
        }

        private void RefreshDecorationsButton()
        {
            var available = CanUseDecorations;
            DecorationsButton.Visible = available;
            if (!available)
                _decorationsWindow?.Close();
        }

        private void OnDecorationsModeChanged(string value)
        {
            RefreshDecorationsButton();
        }
    }
}
