using Content.Client.Credits;
using Content.Client.Message;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Content.Client.UserInterface.Systems.Guidebook;
using Content.Shared.CCVar;
using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Maths;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class LobbyGui : UIScreen
{
    private static readonly Color Paper = Color.FromHex("#DFD7C3");
    private static readonly Color Gold = Color.FromHex("#B69754");
    private static readonly Color BrightGold = Color.FromHex("#E5C879");
    private static readonly Color GoldBorder = Color.FromHex("#DFD7C34D");
    private const float ChatSlideSpeed = 11f;
    private const float ChatContentRevealThreshold = 8f;
    private const float DesktopChatWidth = 520f;
    private const float CompactChatBreakpoint = 650f;
    private const float DesktopChatViewportInset = 28f;
    private const float IntroDuration = 1.45f;
    private const float LogoGlowCycleDuration = 3.8f;
    private const float ReadyPulseCycleDuration = 2.3f;

    private static bool _introPlayedThisProcess;

    [Dependency] private IClientConsoleHost _consoleHost = default!;
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private IResourceCache _resourceCache = default!;
    [Dependency] private IUriOpener _uriOpener = default!;

    private readonly VectorFont _logoFont;
    private readonly VectorFont _menuFont;
    private readonly VectorFont _chatTitleFont;
    private readonly VectorFont _technicalFont;
    private readonly VectorFont _technicalStrongFont;
    private readonly LobbyDrawerDecoration _drawerDecoration = new();
    private readonly List<MenuRowPresentation> _menuRows = new();
    private readonly List<UtilityPresentation> _utilityButtons = new();
    private readonly List<CommunityPresentation> _communityButtons = new();
    private readonly List<ChatControlPresentation> _chatControls = new();

    // The opacity CVar can be changed many times during one lobby session.  Keep the
    // original styleboxes here so every new opacity is derived from the same design
    // surface instead of multiplying alpha into the last generated clone.
    private StyleBox? _leftSideTopPanelStyle;
    private StyleBox? _bottomInfoPanelStyle;
    private StyleBox? _rightSidePanelStyle;

    private TextureRect? _aHelpIcon;
    private TextureRect? _voteIcon;
    private TextureRect? _optionsIcon;
    private TextureRect? _chatIcon;
    private CreditsWindow? _creditsWindow;

    private float _chatCurrentWidth;
    private float _lastChatPanelWidth = -1f;
    private bool _chatExpanded;
    private bool _chatPanelAvailable = true;
    private bool _ready;
    private bool _roundStarted;
    private bool _readyHovered;
    private bool _readyPressed;
    private bool _readyVisualDirty;
    private float _readyHoverAmount;
    private bool _authorsHovered;
    private bool _authorsVisualDirty;
    private float _authorsHoverAmount;
    private bool _introActive;
    private float _introElapsed;
    private float _ambientElapsed;
    private float _lastReadyPulse = -1f;
    private float _responsiveDeckWidth = 440f;
    private float _responsiveLeftInset = 72f;
    private float _lastResponsiveViewportWidth = -1f;

    public LobbyGui()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _logoFont = new VectorFont(
            _resourceCache.GetResource<FontResource>("/Fonts/_WH40K/MetalMania/MetalMania-Regular.ttf"), 58);
        _menuFont = new VectorFont(
            _resourceCache.GetResource<FontResource>("/Fonts/_WH40K/CormorantSC/CormorantSC-Regular.ttf"), 16);
        _chatTitleFont = new VectorFont(
            _resourceCache.GetResource<FontResource>("/Fonts/_WH40K/CormorantSC/CormorantSC-Regular.ttf"), 18);
        _technicalFont = new VectorFont(
            _resourceCache.GetResource<FontResource>("/EngineFonts/NotoSans/NotoSansMono-Regular.ttf"), 10);
        _technicalStrongFont = new VectorFont(
            _resourceCache.GetResource<FontResource>("/Fonts/NotoSans/NotoSans-Bold.ttf"), 12);

        SetAnchorPreset(MainContainer, LayoutPreset.CenterLeft);
        SetGrowVertical(MainContainer, GrowDirection.Both);
        SetMarginLeft(MainContainer, 72);
        SetAnchorPreset(CharacterSetupState, LayoutPreset.Wide);
        SetAnchorPreset(Background, LayoutPreset.Wide);
        SetAnchorPreset(BackdropEffects, LayoutPreset.Wide);
        SetAnchorPreset(RightSide, LayoutPreset.RightWide);
        SetGrowHorizontal(RightSide, GrowDirection.Begin);
        SetMarginTop(RightSide, 0);
        SetMarginRight(RightSide, 0);
        SetMarginBottom(RightSide, 0);
        SetAnchorPreset(DrawerShadow, LayoutPreset.RightWide);
        SetGrowHorizontal(DrawerShadow, GrowDirection.Begin);
        SetMarginTop(DrawerShadow, 0);
        SetMarginRight(DrawerShadow, 0);
        SetMarginBottom(DrawerShadow, 0);
        SetAnchorPreset(DrawerBlurBackdrop, LayoutPreset.RightWide);
        SetGrowHorizontal(DrawerBlurBackdrop, GrowDirection.Begin);
        SetMarginTop(DrawerBlurBackdrop, 0);
        SetMarginRight(DrawerBlurBackdrop, 0);
        SetMarginBottom(DrawerBlurBackdrop, 0);
        SetAnchorPreset(UtilityBar, LayoutPreset.TopRight);
        SetGrowHorizontal(UtilityBar, GrowDirection.Begin);
        SetMarginTop(UtilityBar, 20);
        SetMarginRight(UtilityBar, -20);

        ConfigureVisuals();
        // A freshly constructed screen does not pass through LobbyState.SwitchState
        // before the first status update.  Establish the default composition here so
        // the utility controls cannot inherit a stale hidden state from XAML.
        SwitchState(LobbyGuiState.Default);

        LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));
        LobbyBackground.SetMarkup(Loc.GetString("lobby-state-background-no-background-text"));

        LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
        OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();
        GuidebookButton.OnPressed += _ => UserInterfaceManager.GetUIController<GuidebookUIController>().ToggleGuidebook();
        UpdatesButton.OnPressed += _ => UserInterfaceManager.GetUIController<ChangelogUIController>().ToggleWindow();
        ReadyButton.OnToggled += args => UpdateReadyButtonVisual(args.Pressed, roundStarted: false);
        ChatToggleButton.OnPressed += _ => SetChatExpanded(!_chatExpanded);
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        UpdateCommunityLinkVisibility();
    }

    private void ConfigureVisuals()
    {
        LogoDisplay.FontOverride = _logoFont;
        LogoDisplay.Pulse = 0f;
        SetAnchorPreset(DeckDecoration, LayoutPreset.Wide);
        DeckDecoration.AnimationTime = 0f;
        LogoDisplay.SubtitleFontOverride = _technicalFont;
        RoundStatus.FontOverride = _technicalStrongFont;
        StartTime.FontOverride = _technicalFont;
        StationTime.FontOverride = _technicalFont;
        ChatTitle.FontOverride = _chatTitleFont;
        ChatTitle.FontColorOverride = Paper;
        ChatChannelIndicator.FontOverride = _technicalFont;
        ChatChannelState.FontOverride = _technicalFont;

        foreach (var index in new[]
                 {
                     ReadyIndex,
                     PersonalizationIndex,
                     GuidebookIndex,
                     UpdatesIndex,
                     ObserveIndex,
                     LeaveIndex,
                 })
        {
            index.FontOverride = _technicalFont;
            index.MouseFilter = MouseFilterMode.Ignore;
        }

        ConfigureActionButton(PersonalizationButton);
        ConfigureActionHover(PersonalizationButton, PersonalizationRow);
        ConfigureActionButton(GuidebookButton);
        ConfigureActionHover(GuidebookButton, GuidebookRow);
        ConfigureActionButton(UpdatesButton);
        ConfigureActionHover(UpdatesButton, UpdatesRow);
        ConfigureActionButton(ObserveButton);
        ConfigureActionHover(ObserveButton, ObserveRow);
        ConfigureActionButton(LeaveButton);
        ConfigureActionHover(LeaveButton, LeaveRow);
        ConfigureActionButton(ReadyButton);
        ConfigureReadyHover();

        ApplyStandardRowVisual(PersonalizationRow, hovered: false);
        ApplyStandardRowVisual(GuidebookRow, hovered: false);
        ApplyStandardRowVisual(UpdatesRow, hovered: false);
        ApplyStandardRowVisual(ObserveRow, hovered: false);
        ApplyStandardRowVisual(LeaveRow, hovered: false);

        foreach (var button in new Button[] { AHelpButton, CallVoteButton, OptionsButton, ChatToggleButton })
        {
            button.DefaultCursorShape = Control.CursorShape.Hand;
            button.StyleBoxOverride = CreateUtilityStyleBox(
                Color.FromHex("#0B0A08B3"),
                GoldBorder,
                cornerRadius: 10f);
            button.TextAlign = Label.AlignMode.Center;
            button.Label.FontOverride = _technicalFont;
            button.Label.FontColorOverride = Paper;
        }

        _aHelpIcon = AddUtilityTexture(AHelpButton, "/Textures/Interface/info.svg.192dpi.png");
        _voteIcon = AddUtilityTexture(CallVoteButton, "/Textures/_WH40K/Interface/Lobby/utility-vote.svg.192dpi.png");
        _optionsIcon = AddUtilityTexture(OptionsButton, "/Textures/_WH40K/Interface/Lobby/utility-settings.svg.192dpi.png");
        _chatIcon = AddUtilityTexture(ChatToggleButton, "/Textures/_WH40K/Interface/Lobby/utility-chat.svg.192dpi.png");
        ConfigureUtilityHover(AHelpButton, color => _aHelpIcon!.ModulateSelfOverride = color);
        ConfigureUtilityHover(CallVoteButton, color => _voteIcon!.ModulateSelfOverride = color);
        ConfigureUtilityHover(OptionsButton, color => _optionsIcon!.ModulateSelfOverride = color);
        ConfigureUtilityHover(ChatToggleButton, color => _chatIcon!.ModulateSelfOverride = color);
        ConfigureCommunityButton(
            DiscordButton,
            "/Textures/_WH40K/Interface/Community/discord.svg.192dpi.png",
            CCVars.InfoLinksDiscord);
        ConfigureCommunityButton(
            GitHubButton,
            "/Textures/_WH40K/Interface/Community/github.svg.192dpi.png",
            CCVars.InfoLinksGithub);
        ConfigureCommunityButton(
            SteamButton,
            "/Textures/_WH40K/Interface/Community/steam.svg.192dpi.png",
            CCVars.InfoLinksSteam);
        ConfigureCommunityButton(
            WebsiteButton,
            "/Textures/_WH40K/Interface/Community/website.svg.192dpi.png",
            CCVars.InfoLinksWebsite);
        ConfigureCommunityButton(
            WikiButton,
            "/Textures/_WH40K/Interface/Community/wiki.svg.192dpi.png",
            CCVars.InfoLinksWiki);
        ConfigureCommunityButton(
            ForumButton,
            "/Textures/_WH40K/Interface/Community/forum.svg.192dpi.png",
            CCVars.InfoLinksForum);
        ConfigureCommunityButton(
            TelegramButton,
            "/Textures/_WH40K/Interface/Community/telegram.svg.192dpi.png",
            CCVars.InfoLinksTelegram);
        ConfigureAuthorsButton();

        RightSide.PanelOverride = CreateDrawerStyleBox();
        _leftSideTopPanelStyle = LeftSideTop.PanelOverride;
        _bottomInfoPanelStyle = BottomInfoPanel.PanelOverride;
        _rightSidePanelStyle = RightSide.PanelOverride;
        RightSide.AddChild(_drawerDecoration);
        SetAnchorPreset(_drawerDecoration, LayoutPreset.Wide);
        // The drawer reserves 14px at the bottom for its footer. The decorative
        // edge belongs to the outer drawer, so extend it through that inset.
        _drawerDecoration.Margin = new Thickness(0f, 0f, 0f, -14f);

        Chat.MinSize = new Vector2(0f, 50f);
        Chat.ChatWindowPanel.PanelOverride = new LobbyRoundedStyleBox
        {
            // One shared surface keeps the history, channel selector, input and
            // filter visually together without adding another full-drawer shade.
            BackgroundColor = Color.FromHex("#0807053D"),
            BorderColor = Color.Transparent,
            BorderThickness = new Thickness(0f),
            CornerRadius = 6f,
            ContentMarginLeftOverride = 7f,
            ContentMarginRightOverride = 7f,
            ContentMarginTopOverride = 7f,
            ContentMarginBottomOverride = 7f,
        };
        Chat.FindControl<OutputPanel>("Contents").StyleBoxOverride = null;
        ConfigureChatInputVisuals();

    }

    private void ConfigureActionButton(Button button)
    {
        button.DefaultCursorShape = Control.CursorShape.Hand;
        button.StyleBoxOverride = CreateStyleBox(
            Color.Transparent,
            Color.Transparent,
            horizontalMargin: 12f,
            verticalMargin: 5f);
        // The standard button label has a stylesheet rule that centres it.  These
        // rows use their own index column, so their labels must remain left-aligned.
        button.Label.RemoveStyleClass(ContainerButton.StyleClassButton);
        button.TextAlign = Label.AlignMode.Left;
        button.Label.FontOverride = _menuFont;
        button.Label.FontColorOverride = Paper;
    }

    private void ConfigureActionHover(Button button, PanelContainer row)
    {
        var presentation = new MenuRowPresentation(button, row);
        _menuRows.Add(presentation);

        // The numeric column belongs to the row surface too, while the real button
        // retains clicks. Hover itself is sampled from the UI manager every frame:
        // storing separate enter/exit flags for a parent and a child can leave a
        // surface lit when the pointer moves between their bounds.
        row.MouseFilter = MouseFilterMode.Pass;
        row.DefaultCursorShape = Control.CursorShape.Hand;
        button.OnButtonDown += _ =>
        {
            presentation.Pressed = true;
            presentation.VisualDirty = true;
        };
        button.OnButtonUp += _ =>
        {
            presentation.Pressed = false;
            presentation.VisualDirty = true;
        };

        UpdateMenuRowPresentation(presentation, reducedMotion: true);
    }

    private void ConfigureReadyHover()
    {
        ReadyRow.MouseFilter = MouseFilterMode.Pass;
        ReadyButton.OnButtonDown += _ =>
        {
            _readyPressed = true;
            _readyVisualDirty = true;
        };
        ReadyButton.OnButtonUp += _ =>
        {
            _readyPressed = false;
            _readyVisualDirty = true;
        };
    }

    private void UpdateMenuRowHoverState(MenuRowPresentation presentation)
    {
        if (presentation.Button.Disabled)
        {
            if (!presentation.Hovered && !presentation.Pressed && presentation.HoverAmount == 0f)
                return;

            presentation.Hovered = false;
            presentation.Pressed = false;
            presentation.HoverAmount = 0f;
            presentation.VisualDirty = true;
            return;
        }

        var hovered = presentation.Button.IsHovered || UserInterfaceManager.CurrentlyHovered == presentation.Row;
        if (presentation.Hovered == hovered)
            return;

        presentation.Hovered = hovered;
        if (!hovered)
            presentation.Pressed = false;
        presentation.VisualDirty = true;
    }

    private void UpdateReadyHoverState()
    {
        var hovered = ReadyButton.IsHovered || UserInterfaceManager.CurrentlyHovered == ReadyRow;
        if (_readyHovered == hovered)
            return;

        _readyHovered = hovered;
        if (!hovered)
            _readyPressed = false;
        _readyVisualDirty = true;
    }

    private void ConfigureUtilityHover(Button button, Action<Color> setIconTint)
    {
        var presentation = new UtilityPresentation(button, setIconTint);
        _utilityButtons.Add(presentation);
        button.OnMouseEntered += _ =>
        {
            presentation.Hovered = true;
            presentation.VisualDirty = true;
        };
        button.OnMouseExited += _ =>
        {
            presentation.Hovered = false;
            presentation.Pressed = false;
            presentation.VisualDirty = true;
        };
        button.OnButtonDown += _ =>
        {
            presentation.Pressed = true;
            presentation.VisualDirty = true;
        };
        button.OnButtonUp += _ =>
        {
            presentation.Pressed = false;
            presentation.VisualDirty = true;
        };
        UpdateUtilityPresentation(presentation, reducedMotion: true);
    }

    private static void ApplyUtilityButtonVisual(Button button, float hoverAmount, bool pressed)
    {
        hoverAmount = Math.Clamp(hoverAmount, 0f, 1f);
        var background = pressed
            ? Color.FromHex("#4A3816E6")
            : LerpColor(Color.FromHex("#0C0C0A8A"), Color.FromHex("#272114D6"), hoverAmount);
        var border = pressed
            ? Color.FromHex("#FFF1C8")
            : LerpColor(GoldBorder, BrightGold, hoverAmount);
        var style = button.StyleBoxOverride as LobbyRoundedStyleBox;
        if (style == null)
        {
            style = CreateUtilityStyleBox(background, border, cornerRadius: 10f);
            button.StyleBoxOverride = style;
        }
        else
        {
            style.BackgroundColor = background;
            style.BorderColor = border;
        }
        button.Label.FontColorOverride = LerpColor(Paper, BrightGold, hoverAmount);
        // Keep the allocated slot fixed: only the button itself rises, never the
        // separator or its neighbours in the top utility bar.
        button.Margin = new Thickness(0f, -2f * hoverAmount, 0f, 2f * hoverAmount);
    }

    private TextureRect AddUtilityTexture(Button button, string texturePath)
    {
        button.Text = string.Empty;
        var icon = new TextureRect
        {
            TexturePath = texturePath,
            TextureScale = new Vector2(0.6f),
            Stretch = TextureRect.StretchMode.KeepCentered,
            MouseFilter = Control.MouseFilterMode.Ignore,
            ModulateSelfOverride = Paper,
        };
        button.AddChild(icon);
        return icon;
    }

    private void ConfigureCommunityButton(Button button, string texturePath, CVarDef<string> linkCVar)
    {
        button.Text = string.Empty;
        button.DefaultCursorShape = Control.CursorShape.Hand;
        var icon = new TextureRect
        {
            TexturePath = texturePath,
            TextureScale = new Vector2(0.25f),
            Stretch = TextureRect.StretchMode.KeepCentered,
            MouseFilter = MouseFilterMode.Ignore,
            ModulateSelfOverride = Paper,
            MinSize = new Vector2(16f),
            SetSize = new Vector2(16f),
        };
        button.AddChild(icon);
        SetAnchorAndMarginPreset(icon, LayoutPreset.Center);
        button.StyleBoxOverride = CreateCommunityStyleBox(
            Color.FromHex("#17140DC7"),
            Color.FromHex("#DFD7C38A"));
        button.OnPressed += _ =>
        {
            var url = _cfg.GetCVar(linkCVar);
            if (url != "")
                _uriOpener.OpenUri(url);
        };

        var presentation = new CommunityPresentation(button, icon, linkCVar);
        _communityButtons.Add(presentation);
        button.OnMouseEntered += _ =>
        {
            presentation.Hovered = true;
            presentation.VisualDirty = true;
        };
        button.OnMouseExited += _ =>
        {
            presentation.Hovered = false;
            presentation.Pressed = false;
            presentation.VisualDirty = true;
        };
        button.OnButtonDown += _ =>
        {
            presentation.Pressed = true;
            presentation.VisualDirty = true;
        };
        button.OnButtonUp += _ =>
        {
            presentation.Pressed = false;
            presentation.VisualDirty = true;
        };
        UpdateCommunityPresentation(presentation, reducedMotion: true);
    }

    private void UpdateCommunityLinkVisibility()
    {
        foreach (var presentation in _communityButtons)
        {
            presentation.Button.Visible = _cfg.GetCVar(presentation.LinkCVar) != "";
        }
    }

    private void ConfigureAuthorsButton()
    {
        AuthorsButton.DefaultCursorShape = Control.CursorShape.Hand;
        AuthorsButton.TextAlign = Label.AlignMode.Right;
        AuthorsButton.StyleBoxOverride = CreateStyleBox(Color.Transparent, Color.Transparent, 0f, 0f);
        AuthorsButton.Label.FontOverride = _technicalFont;
        AuthorsButton.Label.FontColorOverride = Color.FromHex("#8E8879");
        AuthorsButton.OnMouseEntered += _ =>
        {
            _authorsHovered = true;
            _authorsVisualDirty = true;
        };
        AuthorsButton.OnMouseExited += _ =>
        {
            _authorsHovered = false;
            _authorsVisualDirty = true;
        };
        AuthorsButton.OnPressed += _ => ToggleCreditsWindow();
        UpdateAuthorsButtonVisual();
    }

    private void ToggleCreditsWindow()
    {
        if (_creditsWindow is { Disposed: false })
        {
            if (_creditsWindow.IsOpen)
            {
                _creditsWindow.Close();
                return;
            }
        }
        else
        {
            _creditsWindow = new CreditsWindow();
        }

        _creditsWindow.OpenCentered();
    }

    private static StyleBoxFlat CreateStyleBox(Color background, Color border, float horizontalMargin, float verticalMargin)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = new Thickness(1f),
            ContentMarginLeftOverride = horizontalMargin,
            ContentMarginRightOverride = horizontalMargin,
            ContentMarginTopOverride = verticalMargin,
            ContentMarginBottomOverride = verticalMargin,
        };
    }

    private static LobbyRoundedStyleBox CreateUtilityStyleBox(Color background, Color border, float cornerRadius)
    {
        return new LobbyRoundedStyleBox
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = new Thickness(1f),
            CornerRadius = cornerRadius,
            HighlightColor = Color.FromHex("#FFF8E012"),
            ShadowColor = Color.Transparent,
            ContentMarginLeftOverride = 0f,
            ContentMarginRightOverride = 0f,
            ContentMarginTopOverride = 0f,
            ContentMarginBottomOverride = 0f,
        };
    }

    private static LobbyRoundedStyleBox CreateCommunityStyleBox(Color background, Color border)
    {
        return new LobbyRoundedStyleBox
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = new Thickness(1f),
            CornerRadius = 15f,
            HighlightColor = Color.FromHex("#FFF8E019"),
            ShadowColor = Color.Transparent,
            ContentMarginLeftOverride = 0f,
            ContentMarginRightOverride = 0f,
            ContentMarginTopOverride = 0f,
            ContentMarginBottomOverride = 0f,
        };
    }

    private void ConfigureChatInputVisuals()
    {
        const float chatControlHeight = 37f;

        var inputBox = Chat.ChatInput;
        // ChatInputBox normally draws a shared subpanel behind its children.  The
        // lobby keeps channel, input and filter as three independent controls, so
        // only their own borders and backgrounds remain visible.
        inputBox.PanelOverride = CreateTransparentChatInputStyle();
        inputBox.MinHeight = chatControlHeight;
        inputBox.SetHeight = chatControlHeight;
        inputBox.Margin = new Thickness(0f, 8f, 0f, 0f);

        var input = inputBox.Input;
        input.MinHeight = chatControlHeight;
        input.SetHeight = chatControlHeight;
        input.Margin = new Thickness(0f, 0f, 4f, 0f);
        input.StyleBoxOverride = CreateChatControlStyle(
            Color.FromHex("#080705D9"),
            Color.FromHex("#B89F5760"),
            cornerRadius: 3f,
            horizontalMargin: 10f);
        input.OnFocusEnter += _ =>
        {
            var focusStyle = CreateChatControlStyle(
            Color.FromHex("#030302B8"),
            BrightGold,
            cornerRadius: 3f,
            horizontalMargin: 10f);
            input.StyleBoxOverride = focusStyle;
        };
        input.OnFocusExit += _ => input.StyleBoxOverride = CreateChatControlStyle(
            Color.FromHex("#080705D9"),
            Color.FromHex("#B89F5760"),
            cornerRadius: 3f,
            horizontalMargin: 10f);

        inputBox.ChannelSelector.MinHeight = chatControlHeight;
        inputBox.ChannelSelector.SetHeight = chatControlHeight;
        inputBox.ChannelSelector.Margin = new Thickness(0f, 0f, 4f, 0f);
        inputBox.ChannelSelector.Label.FontOverride = _technicalFont;
        inputBox.ChannelSelector.TextAlign = Label.AlignMode.Center;
        inputBox.ChannelSelector.DefaultCursorShape = Control.CursorShape.Hand;
        ConfigureChatPopupHover(inputBox.ChannelSelector, ChatControlKind.Channel);

        inputBox.FilterButton.MinSize = new Vector2(38f, chatControlHeight);
        inputBox.FilterButton.SetSize = new Vector2(38f, chatControlHeight);
        inputBox.FilterButton.DefaultCursorShape = Control.CursorShape.Hand;
        ConfigureChatPopupHover(inputBox.FilterButton, ChatControlKind.Filter);
    }

    private void ConfigureChatPopupHover(Button button, ChatControlKind kind)
    {
        button.DefaultCursorShape = Control.CursorShape.Hand;
        var presentation = new ChatControlPresentation(button, kind);
        _chatControls.Add(presentation);

        button.OnMouseEntered += _ =>
        {
            presentation.Hovered = true;
            presentation.VisualDirty = true;
        };
        button.OnMouseExited += _ =>
        {
            presentation.Hovered = false;
            presentation.Pressed = false;
            presentation.VisualDirty = true;
        };
        button.OnButtonDown += _ =>
        {
            presentation.Pressed = true;
            presentation.VisualDirty = true;
        };
        button.OnButtonUp += _ =>
        {
            presentation.Pressed = false;
            presentation.VisualDirty = true;
        };
        UpdateChatControlPresentation(presentation, reducedMotion: true);
    }

    private static LobbyRoundedStyleBox CreateChatControlStyle(
        Color background,
        Color border,
        float cornerRadius,
        float horizontalMargin = 0f)
    {
        return new LobbyRoundedStyleBox
        {
            BackgroundColor = background,
            BorderColor = border,
            BorderThickness = new Thickness(1f),
            CornerRadius = cornerRadius,
            ContentMarginLeftOverride = horizontalMargin,
            ContentMarginRightOverride = horizontalMargin,
            ContentMarginTopOverride = 0f,
            ContentMarginBottomOverride = 0f,
        };
    }

    private static StyleBoxFlat CreateTransparentChatInputStyle()
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Color.Transparent,
            BorderColor = Color.Transparent,
            BorderThickness = new Thickness(0f),
            ContentMarginLeftOverride = 0f,
            ContentMarginRightOverride = 0f,
            ContentMarginTopOverride = 0f,
            ContentMarginBottomOverride = 0f,
        };
    }

    private static LobbyDrawerStyleBox CreateDrawerStyleBox()
    {
        return new LobbyDrawerStyleBox
        {
            // The blurred backdrop is drawn by a sibling surface. This tint keeps it
            // legible without letting high-contrast art compete with chat text.
            LeftColor = Color.FromHex("#090806DE"),
            MiddleColor = Color.FromHex("#090907F0"),
            RightColor = Color.FromHex("#060605FA"),
            // The animated decoration paints the only visible edge. Keeping this
            // static border as well produced a second, parallel gold stripe.
            BorderColor = Color.Transparent,
            BorderThickness = new Thickness(1f, 0f, 0f, 0f),
            ContentMarginLeftOverride = 24f,
            ContentMarginRightOverride = 24f,
            ContentMarginTopOverride = 0f,
            ContentMarginBottomOverride = 14f,
        };
    }

    private static void ApplyStandardRowVisual(PanelContainer row, bool hovered, bool pressed = false)
    {
        ApplyStandardRowVisual(row, hovered ? 1f : 0f, pressed);
    }

    private static void ApplyStandardRowVisual(PanelContainer row, float hoverAmount, bool pressed = false)
    {
        hoverAmount = Math.Clamp(hoverAmount, 0f, 1f);
        var normal = Color.Transparent;
        var hovered = pressed
            ? Color.FromHex("#7B5E214D")
            : Color.FromHex("#684C1B4F");
        var style = GetMenuRowStyle(row);
        style.LeftColor = LerpColor(normal, hovered, hoverAmount);
        style.MiddleColor = Color.Transparent;
        style.RightColor = Color.FromHex("#34271100");
        style.MiddleStop = 0f;
        style.AccentColor = BrightGold.WithAlpha((pressed ? 1f : 0.78f) * hoverAmount);
        style.DrawAccent = hoverAmount > 0.01f || pressed;
        style.DrawDivider = true;
    }

    private void ApplyReadyRowVisual(bool ready, bool roundStarted, float pulse)
    {
        if (roundStarted)
        {
            ApplyStandardRowVisual(ReadyRow, _readyHoverAmount, _readyPressed);
            ReadyIndex.FontColorOverride = Gold;
            return;
        }

        var intensity = 0.64f + 0.30f * pulse + _readyHoverAmount * 0.06f;
        var middleIntensity = 0.50f + 0.13f * pulse + _readyHoverAmount * 0.06f;
        var baseLeft = ready ? Color.FromHex("#845D18") : Color.FromHex("#80261D");
        var hoverLeft = ready ? Color.FromHex("#A57620") : Color.FromHex("#9D3124");
        var left = LerpColor(baseLeft, hoverLeft, _readyHoverAmount).WithAlpha(intensity);
        var baseMiddle = ready ? Color.FromHex("#684812") : Color.FromHex("#711E18");
        var hoverMiddle = ready ? Color.FromHex("#8A601A") : Color.FromHex("#81251F");
        var middle = LerpColor(baseMiddle, hoverMiddle, _readyHoverAmount).WithAlpha(middleIntensity);
        var style = GetMenuRowStyle(ReadyRow);
        style.LeftColor = left;
        style.MiddleColor = middle;
        style.RightColor = middle.WithAlpha(0f);
        style.MiddleStop = 0.72f;
        style.AccentColor = ready ? BrightGold : Color.FromHex("#FF906D");
        style.DrawAccent = true;
        style.DrawDivider = false;
        ReadyIndex.FontColorOverride = ready ? BrightGold : Color.FromHex("#FFB080");
    }

    private static LobbyMenuRowStyleBox GetMenuRowStyle(PanelContainer row)
    {
        if (row.PanelOverride is LobbyMenuRowStyleBox style)
            return style;

        style = new LobbyMenuRowStyleBox();
        row.PanelOverride = style;
        return style;
    }

    public void UpdateReadyButtonVisual(bool ready, bool roundStarted)
    {
        _ready = ready;
        _roundStarted = roundStarted;
        ApplyReadyButtonVisual(ready, roundStarted, pulse: 0f);
    }

    /// <summary>
    /// Updates both the input state and the visual state of the observe row.
    /// This menu has a custom presentation, so the stock disabled-button styling
    /// is not sufficiently visible on its own.
    /// </summary>
    public void SetObserveAvailable(bool available)
    {
        ObserveButton.Disabled = !available;
        ObserveRow.Modulate = Color.White;
        ObserveIndex.FontColorOverride = available ? Gold : Color.FromHex("#8A806D");

        foreach (var presentation in _menuRows)
        {
            if (presentation.Button != ObserveButton)
                continue;

            presentation.Hovered = false;
            presentation.Pressed = false;
            presentation.HoverAmount = 0f;
            presentation.VisualDirty = true;
            UpdateMenuRowPresentation(presentation, reducedMotion: true);
        }
    }

    private void ApplyReadyButtonVisual(bool ready, bool roundStarted, float pulse)
    {
        if (roundStarted)
        {
            ConfigureActionButton(ReadyButton);
            ReadyButton.Label.FontColorOverride = Paper;
            ApplyReadyRowVisual(ready, roundStarted: true, pulse: 0f);
            _lastReadyPulse = 0f;
            return;
        }

        ReadyButton.Label.FontColorOverride = ready ? BrightGold : Color.FromHex("#F0D7B2");
        ApplyReadyRowVisual(ready, roundStarted: false, pulse);
        _lastReadyPulse = pulse;
    }

    /// <summary>
    /// Starts the lobby presentation once for the lifetime of the client process.
    /// Returning to the lobby uses the normal immediately-visible layout.
    /// </summary>
    public void BeginPresentation()
    {
        _introElapsed = 0f;
        _ambientElapsed = 0f;
        _introActive = !_introPlayedThisProcess && !IsReducedMotion;
        _introPlayedThisProcess = true;

        if (_introActive)
        {
            ApplyIntroOpacity(left: 0f, utility: 0f, chat: 0f);
            return;
        }

        ApplyIntroOpacity(left: 1f, utility: 1f, chat: 1f);
        ApplyStaticVisuals();
    }

    public void UpdateVisualEffects(float deltaSeconds)
    {
        UpdateResponsiveLayout();
        UpdateInteractiveVisuals(deltaSeconds, IsReducedMotion);

        if (IsReducedMotion)
        {
            _introActive = false;
            ApplyIntroOpacity(left: 1f, utility: 1f, chat: 1f);
            ApplyStaticVisuals();
            return;
        }

        _ambientElapsed += deltaSeconds;

        if (_introActive)
        {
            _introElapsed += deltaSeconds;
            ApplyIntroOpacity(
                left: EaseTimeline(_introElapsed, 0.05f, 0.52f),
                utility: EaseTimeline(_introElapsed, 0.42f, 0.42f),
                chat: EaseTimeline(_introElapsed, 0.58f, 0.47f));

            if (_introElapsed >= IntroDuration)
            {
                _introActive = false;
                ApplyIntroOpacity(left: 1f, utility: 1f, chat: 1f);
            }
        }

        var logoPulse = 0.5f + 0.5f * MathF.Sin(_ambientElapsed * MathF.Tau / LogoGlowCycleDuration);
        LogoDisplay.Pulse = logoPulse;
        DeckDecoration.AnimationTime = _ambientElapsed;
        var signalPhase = _ambientElapsed / 2.4f;
        signalPhase -= MathF.Floor(signalPhase);
        RoundIndicator.Pulse = signalPhase;
        _drawerDecoration.Pulse = logoPulse;
        if (_roundStarted)
            return;

        var readyPulse = 0.5f + 0.5f * MathF.Sin(_ambientElapsed * MathF.Tau / ReadyPulseCycleDuration);
        if (MathF.Abs(readyPulse - _lastReadyPulse) >= 0.015f)
            ApplyReadyButtonVisual(_ready, roundStarted: false, readyPulse);
    }

    private void UpdateInteractiveVisuals(float deltaSeconds, bool reducedMotion)
    {
        foreach (var presentation in _menuRows)
        {
            UpdateMenuRowHoverState(presentation);
            var previous = presentation.HoverAmount;
            presentation.HoverAmount = ApproachPresentation(
                presentation.HoverAmount,
                presentation.Hovered ? 1f : 0f,
                deltaSeconds,
                reducedMotion);

            if (presentation.HoverAmount == previous && !presentation.VisualDirty)
                continue;

            UpdateMenuRowPresentation(presentation, reducedMotion: false);
        }

        UpdateReadyHoverState();
        var readyPrevious = _readyHoverAmount;
        _readyHoverAmount = ApproachPresentation(
            _readyHoverAmount,
            _readyHovered ? 1f : 0f,
            deltaSeconds,
            reducedMotion);
        if (_readyHoverAmount != readyPrevious || _readyVisualDirty)
        {
            ReadyButton.Label.Margin = new Thickness(8f * _readyHoverAmount, 0f, 0f, 0f);
            ApplyReadyButtonVisual(_ready, _roundStarted, _lastReadyPulse < 0f ? 0f : _lastReadyPulse);
            _readyVisualDirty = false;
        }

        foreach (var presentation in _utilityButtons)
        {
            var previous = presentation.HoverAmount;
            presentation.HoverAmount = ApproachPresentation(
                presentation.HoverAmount,
                presentation.Hovered ? 1f : 0f,
                deltaSeconds,
                reducedMotion);

            if (presentation.HoverAmount == previous && !presentation.VisualDirty)
                continue;

            UpdateUtilityPresentation(presentation, reducedMotion: false);
        }

        foreach (var presentation in _communityButtons)
        {
            var previous = presentation.HoverAmount;
            presentation.HoverAmount = ApproachPresentation(
                presentation.HoverAmount,
                presentation.Hovered ? 1f : 0f,
                deltaSeconds,
                reducedMotion);

            if (presentation.HoverAmount == previous && !presentation.VisualDirty)
                continue;

            UpdateCommunityPresentation(presentation, reducedMotion: false);
        }

        var authorsPrevious = _authorsHoverAmount;
        _authorsHoverAmount = ApproachPresentation(
            _authorsHoverAmount,
            _authorsHovered ? 1f : 0f,
            deltaSeconds,
            reducedMotion);
        if (_authorsHoverAmount != authorsPrevious || _authorsVisualDirty)
        {
            UpdateAuthorsButtonVisual();
            _authorsVisualDirty = false;
        }

        foreach (var presentation in _chatControls)
        {
            var previous = presentation.HoverAmount;
            presentation.HoverAmount = ApproachPresentation(
                presentation.HoverAmount,
                presentation.Hovered ? 1f : 0f,
                deltaSeconds,
                reducedMotion);

            if (presentation.HoverAmount == previous && !presentation.VisualDirty)
                continue;

            UpdateChatControlPresentation(presentation, reducedMotion: false);
        }
    }

    private static float ApproachPresentation(float value, float target, float deltaSeconds, bool reducedMotion)
    {
        if (reducedMotion)
            return target;

        var speed = Math.Clamp(deltaSeconds * 12f, 0f, 1f);
        var approached = value + (target - value) * speed;
        return MathF.Abs(approached - target) <= 0.002f ? target : approached;
    }

    private static Color LerpColor(Color from, Color to, float progress)
    {
        progress = Math.Clamp(progress, 0f, 1f);
        return new Color(
            from.R + (to.R - from.R) * progress,
            from.G + (to.G - from.G) * progress,
            from.B + (to.B - from.B) * progress,
            from.A + (to.A - from.A) * progress);
    }

    private static void UpdateMenuRowPresentation(MenuRowPresentation presentation, bool reducedMotion)
    {
        if (presentation.Button.Disabled)
        {
            presentation.HoverAmount = 0f;
            presentation.Pressed = false;
            presentation.Button.Label.Margin = default;
            presentation.Button.Label.FontColorOverride = Color.FromHex("#8A806D");
            ApplyStandardRowVisual(presentation.Row, hovered: false);
            presentation.VisualDirty = false;
            return;
        }

        if (reducedMotion)
            presentation.HoverAmount = presentation.Hovered ? 1f : 0f;

        presentation.Button.Label.Margin = new Thickness(8f * presentation.HoverAmount, 0f, 0f, 0f);
        presentation.Button.Label.FontColorOverride = LerpColor(Paper, Color.FromHex("#FFF4D9"), presentation.HoverAmount);
        ApplyStandardRowVisual(presentation.Row, presentation.HoverAmount, presentation.Pressed);
        presentation.VisualDirty = false;
    }

    private static void UpdateUtilityPresentation(UtilityPresentation presentation, bool reducedMotion)
    {
        if (reducedMotion)
            presentation.HoverAmount = presentation.Hovered ? 1f : 0f;

        ApplyUtilityButtonVisual(presentation.Button, presentation.HoverAmount, presentation.Pressed);
        var tint = presentation.Pressed
            ? Color.FromHex("#FFF1C8")
            : LerpColor(Paper, BrightGold, presentation.HoverAmount);
        presentation.SetIconTint(tint);
        presentation.VisualDirty = false;
    }

    private static void UpdateCommunityPresentation(CommunityPresentation presentation, bool reducedMotion)
    {
        if (reducedMotion)
            presentation.HoverAmount = presentation.Hovered ? 1f : 0f;

        var background = presentation.Pressed
            ? Color.FromHex("#A8793D94")
            : LerpColor(Color.FromHex("#17140DC7"), Color.FromHex("#43361CD9"), presentation.HoverAmount);
        var border = presentation.Pressed
            ? Color.FromHex("#FFF1C8")
            : LerpColor(Color.FromHex("#DFD7C38A"), BrightGold, presentation.HoverAmount);
        var style = presentation.Button.StyleBoxOverride as LobbyRoundedStyleBox;
        if (style == null)
        {
            style = CreateCommunityStyleBox(background, border);
            presentation.Button.StyleBoxOverride = style;
        }
        else
        {
            style.BackgroundColor = background;
            style.BorderColor = border;
        }
        presentation.Icon.ModulateSelfOverride = presentation.Pressed
            ? Color.FromHex("#FFF1C8")
            : LerpColor(Paper, BrightGold, presentation.HoverAmount);
        presentation.Button.Margin = new Thickness(0f, -2f * presentation.HoverAmount, 0f, 2f * presentation.HoverAmount);
        presentation.VisualDirty = false;
    }

    private void UpdateAuthorsButtonVisual()
    {
        AuthorsButton.Label.FontColorOverride = LerpColor(
            Color.FromHex("#8E8879"),
            BrightGold,
            _authorsHoverAmount);
        AuthorsButton.Label.Margin = new Thickness(0f, -1.5f * _authorsHoverAmount, 0f, 1.5f * _authorsHoverAmount);
    }

    private static void UpdateChatControlPresentation(ChatControlPresentation presentation, bool reducedMotion)
    {
        if (reducedMotion)
            presentation.HoverAmount = presentation.Hovered ? 1f : 0f;

        var isChannel = presentation.Kind == ChatControlKind.Channel;
        var normalBackground = isChannel ? Color.FromHex("#15394CB8") : Color.FromHex("#120F0AD0");
        var hoverBackground = isChannel ? Color.FromHex("#1F506AD9") : Color.FromHex("#2A2111E8");
        var normalBorder = isChannel ? Color.FromHex("#4B7F9C8C") : Color.FromHex("#9E86504D");
        var hoverBorder = isChannel ? Color.FromHex("#90D2EE") : BrightGold;
        var normalText = isChannel ? Color.FromHex("#90D2EE") : Paper;
        var hoverText = isChannel ? Color.FromHex("#C6EEFF") : BrightGold;
        var pressedBackground = isChannel ? Color.FromHex("#285C76EF") : Color.FromHex("#4A3816E8");
        var pressedBorder = isChannel ? Color.FromHex("#D7F5FF") : Color.FromHex("#FFF1C8");

        var background = presentation.Pressed
            ? pressedBackground
            : LerpColor(normalBackground, hoverBackground, presentation.HoverAmount);
        var border = presentation.Pressed
            ? pressedBorder
            : LerpColor(normalBorder, hoverBorder, presentation.HoverAmount);
        var style = presentation.Button.StyleBoxOverride as LobbyRoundedStyleBox;
        if (style == null)
        {
            style = CreateChatControlStyle(background, border, cornerRadius: 3f);
            presentation.Button.StyleBoxOverride = style;
        }
        else
        {
            style.BackgroundColor = background;
            style.BorderColor = border;
        }
        presentation.Button.Label.FontColorOverride = LerpColor(normalText, hoverText, presentation.HoverAmount);
        presentation.VisualDirty = false;
    }

    public void SetChatExpanded(bool expanded)
    {
        _chatExpanded = expanded;

        if (expanded)
        {
            if (_chatPanelAvailable)
                RightSide.Visible = true;
        }
        else
        {
            Chat.ChatInput.Input.ReleaseKeyboardFocus();
        }

        if (IsReducedMotion)
            _chatCurrentWidth = expanded ? GetEffectiveChatWidth() : 0f;

        // Keep the drawer outside the screen from the very first frame. Otherwise its
        // XAML width is briefly visible before the animation gets its first update.
        UpdateChatPanelLayout();
    }

    public void UpdateChatAnimation(float deltaSeconds)
    {
        if (!_chatPanelAvailable)
            return;

        var targetWidth = _chatExpanded ? GetEffectiveChatWidth() : 0f;
        var panelWidthChanged = MathF.Abs(targetWidth - _lastChatPanelWidth) > 0.25f;
        if (IsReducedMotion)
        {
            if (MathF.Abs(_chatCurrentWidth - targetWidth) <= 0.01f && !panelWidthChanged)
                return;

            _chatCurrentWidth = targetWidth;
            UpdateChatPanelLayout();
            return;
        }

        // A closed, settled drawer has no visible controls to animate. Avoid repeatedly
        // assigning the same layout, visibility and modulation values every frame.
        if (!_chatExpanded && _chatCurrentWidth <= 0.01f)
        {
            _lastChatPanelWidth = targetWidth;
            return;
        }

        if (MathF.Abs(_chatCurrentWidth - targetWidth) <= 0.01f && !panelWidthChanged)
            return;

        var interpolation = Math.Clamp(deltaSeconds * ChatSlideSpeed, 0f, 1f);
        _chatCurrentWidth = MathHelper.Lerp(_chatCurrentWidth, targetWidth, interpolation);

        if (MathF.Abs(_chatCurrentWidth - targetWidth) < 0.25f)
            _chatCurrentWidth = targetWidth;

        UpdateChatPanelLayout();
    }

    private void UpdateChatPanelLayout()
    {
        var panelWidth = GetEffectiveChatWidth();
        _lastChatPanelWidth = panelWidth;
        var panelVisible = _chatExpanded || _chatCurrentWidth > 0f;
        RightSide.Visible = panelVisible;
        DrawerShadow.Visible = panelVisible;
        DrawerBlurBackdrop.Visible = panelVisible;
        if (!panelVisible)
        {
            ChatContent.Visible = false;
            RightSide.ModulateSelfOverride = null;
            DrawerShadow.ModulateSelfOverride = null;
            DrawerBlurBackdrop.ModulateSelfOverride = null;
            ChatContent.Modulate = Color.White;
            return;
        }

        // The chat itself keeps its natural minimum width.  Sliding the whole panel by
        // its right margin avoids a layout overflow that used to make it pop in at full size.
        RightSide.SetWidth = panelWidth;
        SetMarginRight(RightSide, panelWidth - _chatCurrentWidth);
        DrawerBlurBackdrop.SetWidth = panelWidth;
        SetMarginRight(DrawerBlurBackdrop, panelWidth - _chatCurrentWidth);
        DrawerBlurBackdrop.BackgroundTexture = Background.Texture;
        DrawerBlurBackdrop.BackgroundPixelSize = Background.PixelSize;
        DrawerBlurBackdrop.BackgroundGlobalPixelPosition = Background.GlobalPixelPosition;
        // On compact screens the drawer owns the whole viewport, so a separate
        // left-edge shadow would only create an artificial dark strip.
        DrawerShadow.SetWidth = IsFullscreenChatLayout() ? panelWidth : panelWidth + 64f;
        DrawerShadow.DrawerWidth = panelWidth;
        SetMarginRight(DrawerShadow, panelWidth - _chatCurrentWidth);
        var openAmount = panelWidth <= 0f
            ? 0f
            : Math.Clamp(_chatCurrentWidth / panelWidth, 0f, 1f);
        var easedOpenAmount = openAmount * openAmount * (3f - 2f * openAmount);
        // The drawer surface starts softly before text becomes readable; this avoids
        // the previous hard pop when ChatContent crossed a width threshold.
        RightSide.ModulateSelfOverride = Color.White.WithAlpha(0.12f + easedOpenAmount * 0.88f);
        DrawerBlurBackdrop.ModulateSelfOverride = Color.White.WithAlpha(0.12f + easedOpenAmount * 0.88f);
        DrawerShadow.Opacity = easedOpenAmount;
        DrawerShadow.ModulateSelfOverride = Color.White.WithAlpha(easedOpenAmount);
        ChatContent.Visible = _chatCurrentWidth >= ChatContentRevealThreshold * 0.5f;
        ChatContent.Modulate = Color.White.WithAlpha(easedOpenAmount);
    }

    private float GetEffectiveChatWidth()
    {
        var viewportWidth = PixelSize.X / MathF.Max(UIScale, 0.01f);
        if (viewportWidth <= 0f)
            return DesktopChatWidth;

        // Mirrors the HTML prototype: the compact layout takes the complete
        // viewport, while the desktop drawer never exceeds its designed width.
        if (viewportWidth <= CompactChatBreakpoint)
            return viewportWidth;

        return Math.Min(DesktopChatWidth, viewportWidth - DesktopChatViewportInset);
    }

    private bool IsFullscreenChatLayout()
    {
        var viewportWidth = PixelSize.X / MathF.Max(UIScale, 0.01f);
        return viewportWidth > 0f && viewportWidth <= CompactChatBreakpoint;
    }

    private bool IsReducedMotion => _cfg.GetCVar(CCVars.ReducedMotion);

    private void ApplyStaticVisuals()
    {
        LogoDisplay.Pulse = 0f;
        DeckDecoration.AnimationTime = 0f;
        RoundIndicator.Pulse = 0f;
        StatusBlock.Modulate = Color.White;
        MenuBlock.Modulate = Color.White;
        BottomInfoPanel.Modulate = Color.White;
        StatusBlock.Margin = new Thickness(0f, 0f, 0f, 16f);
        MenuBlock.Margin = new Thickness(0f);
        BottomInfoPanel.Margin = new Thickness(33f, 14f, 0f, 0f);
        SetMarginLeft(MainContainer, _responsiveLeftInset);
        SetMarginTop(UtilityBar, 20);

        if (_lastReadyPulse != 0f)
            ApplyReadyButtonVisual(_ready, _roundStarted, pulse: 0f);
    }

    private void ApplyIntroOpacity(float left, float utility, float chat)
    {
        // Modulate is inherited by child controls; ModulateSelfOverride would only fade the
        // empty containers and leave their labels/buttons visible.
        LeftSide.Modulate = Color.White.WithAlpha(left);
        UtilityBar.Modulate = Color.White.WithAlpha(utility);
        RightSide.Modulate = Color.White.WithAlpha(chat);
        var status = EaseTimeline(_introElapsed, 0.61f, 0.42f);
        var menu = EaseTimeline(_introElapsed, 0.76f, 0.48f);
        var footnote = EaseTimeline(_introElapsed, 1.02f, 0.36f);
        StatusBlock.Modulate = Color.White.WithAlpha(status);
        MenuBlock.Modulate = Color.White.WithAlpha(menu);
        BottomInfoPanel.Modulate = Color.White.WithAlpha(footnote);
        // Mirror the prototype's small upward arrival without translating the whole
        // command deck or changing its resting geometry.
        StatusBlock.Margin = new Thickness(0f, 13f * (1f - status), 0f, 16f);
        MenuBlock.Margin = new Thickness(0f, 13f * (1f - menu), 0f, 0f);
        BottomInfoPanel.Margin = new Thickness(33f, 14f + 13f * (1f - footnote), 0f, 0f);
        SetMarginLeft(MainContainer, MathF.Max(0f, _responsiveLeftInset - 32f * (1f - left)));
        SetMarginTop(UtilityBar, 7f + 13f * utility);
    }

    private void UpdateResponsiveLayout()
    {
        var viewportWidth = PixelSize.X / MathF.Max(UIScale, 0.01f);
        if (viewportWidth <= 1f || MathF.Abs(viewportWidth - _lastResponsiveViewportWidth) < 0.5f)
            return;

        _lastResponsiveViewportWidth = viewportWidth;
        _responsiveDeckWidth = Math.Clamp(viewportWidth - 48f, 300f, 440f);
        _responsiveLeftInset = Math.Clamp(viewportWidth * 0.07f, 24f, 126f);
        _responsiveLeftInset = Math.Min(
            _responsiveLeftInset,
            MathF.Max(16f, viewportWidth - _responsiveDeckWidth - 16f));

        MainContainer.SetWidth = _responsiveDeckWidth;
        LeftSide.SetWidth = _responsiveDeckWidth;
        if (_introActive)
            return;

        SetMarginLeft(MainContainer, _responsiveLeftInset);
    }

    private static float EaseTimeline(float elapsed, float start, float duration)
    {
        var progress = Math.Clamp((elapsed - start) / duration, 0f, 1f);
        return progress * progress * (3f - 2f * progress);
    }

    private void SetChatPanelAvailable(bool available)
    {
        _chatPanelAvailable = available;
        UtilityBar.Visible = available;

        if (!available)
        {
            RightSide.Visible = false;
            DrawerShadow.Visible = false;
            DrawerBlurBackdrop.Visible = false;
            ChatContent.Visible = false;
            return;
        }

        UpdateChatPanelLayout();
    }

    public void SwitchState(LobbyGuiState state)
    {
        DefaultState.Visible = false;
        CharacterSetupState.Visible = false;
        MainContainer.Visible = false;

        switch (state)
        {
            case LobbyGuiState.Default:
                MainContainer.Visible = true;
                DefaultState.Visible = true;
                SetChatPanelAvailable(true);
                break;
            case LobbyGuiState.CharacterSetup:
                CharacterSetupState.Visible = true;
                SetChatPanelAvailable(false);

                UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();
                break;
        }
    }

    public void ApplyPanelBackgroundOpacity(float opacity)
    {
        LeftSideTop.PanelOverride = LobbyPanelOpacityHelper.CreateOpacityStyle(_leftSideTopPanelStyle, opacity);
        BottomInfoPanel.PanelOverride = LobbyPanelOpacityHelper.CreateOpacityStyle(_bottomInfoPanelStyle, opacity);
        // The drawer is its own glass surface, not an ordinary lobby card. Applying
        // the global panel-opacity slider here makes the chat unreadable on bright art.
        RightSide.PanelOverride = _rightSidePanelStyle;
    }

    private sealed class MenuRowPresentation
    {
        public Button Button { get; }
        public PanelContainer Row { get; }
        public bool Hovered { get; set; }
        public bool Pressed { get; set; }
        public float HoverAmount { get; set; }
        public bool VisualDirty { get; set; } = true;

        public MenuRowPresentation(Button button, PanelContainer row)
        {
            Button = button;
            Row = row;
        }
    }

    private sealed class UtilityPresentation
    {
        public Button Button { get; }
        public Action<Color> SetIconTint { get; }
        public bool Hovered { get; set; }
        public bool Pressed { get; set; }
        public float HoverAmount { get; set; }
        public bool VisualDirty { get; set; } = true;

        public UtilityPresentation(Button button, Action<Color> setIconTint)
        {
            Button = button;
            SetIconTint = setIconTint;
        }
    }

    private sealed class ChatControlPresentation
    {
        public Button Button { get; }
        public ChatControlKind Kind { get; }
        public bool Hovered { get; set; }
        public bool Pressed { get; set; }
        public float HoverAmount { get; set; }
        public bool VisualDirty { get; set; } = true;

        public ChatControlPresentation(Button button, ChatControlKind kind)
        {
            Button = button;
            Kind = kind;
        }
    }

    private sealed class CommunityPresentation
    {
        public Button Button { get; }
        public TextureRect Icon { get; }
        public CVarDef<string> LinkCVar { get; }
        public bool Hovered { get; set; }
        public bool Pressed { get; set; }
        public float HoverAmount { get; set; }
        public bool VisualDirty { get; set; } = true;

        public CommunityPresentation(Button button, TextureRect icon, CVarDef<string> linkCVar)
        {
            Button = button;
            Icon = icon;
            LinkCVar = linkCVar;
        }
    }

    private enum ChatControlKind : byte
    {
        Channel,
        Filter,
    }

    public enum LobbyGuiState : byte
    {
        /// <summary>
        /// The default state, i.e., what's seen on launch.
        /// </summary>
        Default,
        /// <summary>
        /// Character setup state.
        /// </summary>
        CharacterSetup
    }
}
