using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Storage;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WH40K.Augments;

[GenerateTypedNameReferences]
public sealed partial class AugmentToolPanelMenu : RadialMenu
{
    [Dependency] private readonly EntityManager _entities = default!;

    public event Action<EntityUid?>? SendSwitchMessage;

    private EntityUid _owner;

    public AugmentToolPanelMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void SetEntity(EntityUid owner)
    {
        _owner = owner;
        Refresh();
    }

    private void Refresh()
    {
        if (!_entities.TryGetComponent<StorageComponent>(_owner, out var storage))
            return;

        foreach (var (entity, _) in storage.StoredItems)
        {
            var button = new RadialMenuTextureButton
            {
                SetSize = new Vector2(64f, 64f),
                StyleClasses = { "RadialMenuButton" },
            };
            button.AddChild(new SpriteView(entity, _entities) { Scale = new Vector2(3f, 3f) });
            Main.AddChild(button);
            button.OnButtonUp += _ =>
            {
                SendSwitchMessage?.Invoke(entity);
                Close();
            };
        }

        var retract = new RadialMenuTextureButton
        {
            SetSize = new Vector2(64f, 64f),
            StyleClasses = { "RadialMenuButton" },
        };
        Main.AddChild(retract);
        retract.OnButtonUp += _ =>
        {
            SendSwitchMessage?.Invoke(null);
            Close();
        };
    }
}
