- type: entity
  id: WH40KCargoRailDecor
  suffix: WH40K, Visual
  components:
  - type: Transform
    anchored: true
  - type: Sprite
    sprite: _WH40K/Objects/Cargo/rail.rsi
    state: icon
    drawdepth: FloorObjects
