using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Text;
using Content.Client.UserInterface.Controls;
using Content.Shared._WH40K.MetaProgress;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.ResourceManagement;
using Robust.Client.Utility;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client._WH40K.MetaProgress;

[GenerateTypedNameReferences]
public sealed partial class PlayerDecorationsWindow : FancyWindow
{
    private const float CardWidth = 300f;
    private const float CardHeight = 210f;
    private const float PreviewHeight = 120f;
    private const float PreviewTextMaxWidth = 260f;

    // Нейтральные цвета штатного лобби: отделяют карточки от контейнера без старой золотой палитры.
    private static readonly Color CardBackground = Color.FromHex("#1B1B1E");
    private static readonly Color SelectedCardBackground = Color.FromHex("#252525");
    private static readonly Color PreviewBackground = Color.FromHex("#101010");

    [Dependency] private readonly IEntityManager _entities = default!;
    [Dependency] private readonly IPlayerManager _players = default!;
    [Dependency] private readonly IResourceCache _resources = default!;

    private readonly List<WH40KDecorationEntry> _entries = new();
    private readonly Dictionary<WH40KMetaDecorationCategory, string> _selected = new();
    private readonly WH40KDecorationSystem _decorations;
    private readonly List<DecorationCard> _renderedCards = new();
    private readonly Dictionary<GhostTextureKey, Texture?> _ghostTextureCache = new();
    private readonly HashSet<string> _failedPreviewMarkup = new(StringComparer.Ordinal);

    private WH40KMetaDecorationCategory _category = WH40KMetaDecorationCategory.GhostSkins;
    private bool _loaded;
    private long _catalogRevision = -1;
    private WH40KMetaDecorationCategory? _renderedCategory;
    private string _previewName = "Player";

    public PlayerDecorationsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _decorations = _entities.System<WH40KDecorationSystem>();
        _decorations.StateUpdated += OnStateUpdated;

        GhostSkinsTabButton.OnPressed += _ => SetCategory(WH40KMetaDecorationCategory.GhostSkins);
        OocTitlesTabButton.OnPressed += _ => SetCategory(WH40KMetaDecorationCategory.OocTitles);
        OocNameColorsTabButton.OnPressed += _ => SetCategory(WH40KMetaDecorationCategory.OocNameColors);

        if (!string.IsNullOrWhiteSpace(_players.LocalSession?.Name))
            _previewName = _players.LocalSession.Name;

        Relocalize();
        _decorations.EnsureState();
        if (_decorations.TryGetState(out var state))
            ApplyState(state);
    }

    [Obsolete]
    protected override void Dispose(bool disposing)
    {
        if (disposing)
            _decorations.StateUpdated -= OnStateUpdated;

#pragma warning disable CS0618
        base.Dispose(disposing);
#pragma warning restore CS0618
    }

    public void Relocalize()
    {
        Title = Loc.GetString("w40k-decs-window-title");
        MenuHeaderLabel.Text = Loc.GetString("w40k-decs-menu-header");
        GhostSkinsTabButton.Text = Loc.GetString("w40k-decs-tab-ghost-skins");
        OocTitlesTabButton.Text = Loc.GetString("w40k-decs-tab-ooc-titles");
        OocNameColorsTabButton.Text = Loc.GetString("w40k-decs-tab-ooc-name-colors");
        Refresh(rebuildCards: true);
    }

    private void OnStateUpdated(WH40KDecorationState state)
    {
        ApplyState(state);
    }

    private void ApplyState(WH40KDecorationState state)
    {
        var rebuildCards = _catalogRevision != state.CatalogRevision;
        if (rebuildCards)
        {
            _entries.Clear();
            _ghostTextureCache.Clear();
            _entries.AddRange(state.Decorations
                .OrderBy(entry => entry.Category)
                .ThenBy(entry => entry.SortOrder)
                .ThenBy(entry => entry.Id, StringComparer.Ordinal));
            _catalogRevision = state.CatalogRevision;
        }

        _selected[WH40KMetaDecorationCategory.GhostSkins] = state.Selection.SelectedGhostSkinId;
        _selected[WH40KMetaDecorationCategory.OocTitles] = state.Selection.SelectedOocTitleId;
        _selected[WH40KMetaDecorationCategory.OocNameColors] = state.Selection.SelectedOocNameColorId;
        _loaded = true;
        Refresh(rebuildCards);
    }

    private void SetCategory(WH40KMetaDecorationCategory category)
    {
        _category = category;
        Refresh(rebuildCards: true);
    }

    private void Refresh(bool rebuildCards = false)
    {
        GhostSkinsTabButton.Pressed = _category == WH40KMetaDecorationCategory.GhostSkins;
        OocTitlesTabButton.Pressed = _category == WH40KMetaDecorationCategory.OocTitles;
        OocNameColorsTabButton.Pressed = _category == WH40KMetaDecorationCategory.OocNameColors;

        SummaryLabel.Text = Loc.GetString(
            "w40k-decs-summary-by-category",
            ("ghostTotal", _entries.Count(entry => entry.Category == WH40KMetaDecorationCategory.GhostSkins)),
            ("titleTotal", _entries.Count(entry => entry.Category == WH40KMetaDecorationCategory.OocTitles)),
            ("colorTotal", _entries.Count(entry => entry.Category == WH40KMetaDecorationCategory.OocNameColors)));

        if (!_loaded)
        {
            CardsList.RemoveAllChildren();
            _renderedCards.Clear();
            _renderedCategory = null;
            CardsList.AddChild(new Label { Text = Loc.GetString("w40k-decs-loading"), Margin = new Thickness(4) });
            return;
        }

        var filtered = _entries.Where(entry => entry.Category == _category).ToArray();
        if (filtered.Length == 0)
        {
            CardsList.RemoveAllChildren();
            _renderedCards.Clear();
            _renderedCategory = null;
            CardsList.AddChild(new Label { Text = Loc.GetString("w40k-decs-empty"), Margin = new Thickness(4) });
            return;
        }

        if (!rebuildCards && _renderedCategory == _category)
        {
            UpdateRenderedCards();
            return;
        }

        CardsList.RemoveAllChildren();
        _renderedCards.Clear();
        _renderedCategory = _category;

        BoxContainer? row = null;
        for (var index = 0; index < filtered.Length; index++)
        {
            if (index % 3 == 0)
            {
                row = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    SeparationOverride = 8,
                    HorizontalExpand = true,
                };
                CardsList.AddChild(row);
            }

            var card = CreateCard(filtered[index]);
            _renderedCards.Add(card);
            row!.AddChild(card.Panel);
        }
    }

    private DecorationCard CreateCard(WH40KDecorationEntry entry)
    {
        var card = new PanelContainer
        {
            MinSize = new Vector2(CardWidth, CardHeight),
            SetSize = new Vector2(CardWidth, CardHeight),
            HorizontalExpand = true,
        };

        var contents = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 6,
            VerticalExpand = true,
        };
        var title = Loc.GetString(entry.TitleKey);
        contents.AddChild(new Label
        {
            Text = title,
            ToolTip = title,
            ClipText = true,
            HorizontalExpand = true,
            StyleClasses = { "LabelHeading" },
        });

        var preview = new PanelContainer
        {
            MinSize = new Vector2(0, PreviewHeight),
            VerticalExpand = true,
            PanelOverride = CreatePreviewStyle(),
        };
        preview.AddChild(BuildPreview(entry));
        contents.AddChild(preview);

        var button = new Button { HorizontalExpand = true };
        button.OnPressed += _ =>
        {
            if (_decorations.Select(entry.Category, entry.Id))
            {
                _selected[entry.Category] = entry.Id;
                UpdateRenderedCards();
            }
        };

        contents.AddChild(button);
        card.AddChild(contents);
        var result = new DecorationCard(entry, card, button);
        UpdateCard(result);
        return result;
    }

    private void UpdateRenderedCards()
    {
        foreach (var card in _renderedCards)
            UpdateCard(card);
    }

    private void UpdateCard(DecorationCard card)
    {
        var selected = IsSelected(card.Entry);
        card.Panel.PanelOverride = CreateCardStyle(selected);
        card.Button.Text = Loc.GetString(selected ? "w40k-decs-action-selected" : "w40k-decs-action-choose");
        card.Button.Disabled = selected || _decorations.IsSelectionPending(card.Entry.Category);
    }

    private static StyleBoxFlat CreateCardStyle(bool selected)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = selected ? SelectedCardBackground : CardBackground,
            ContentMarginLeftOverride = 10,
            ContentMarginTopOverride = 10,
            ContentMarginRightOverride = 10,
            ContentMarginBottomOverride = 10,
        };
    }

    private static StyleBoxFlat CreatePreviewStyle()
    {
        return new StyleBoxFlat
        {
            BackgroundColor = PreviewBackground,
            ContentMarginLeftOverride = 6,
            ContentMarginTopOverride = 6,
            ContentMarginRightOverride = 6,
            ContentMarginBottomOverride = 6,
        };
    }

    private Control BuildPreview(WH40KDecorationEntry entry)
    {
        if (entry.Category == WH40KMetaDecorationCategory.GhostSkins)
            return BuildGhostPreview(entry);

        var selectedColor = GetSelectedColor();
        var markup = entry.Category switch
        {
            WH40KMetaDecorationCategory.OocNameColors => BuildColorMarkup(entry, _previewName),
            WH40KMetaDecorationCategory.OocTitles when entry.SuppressTitlePrefix && selectedColor != null =>
                BuildColorMarkup(selectedColor, _previewName),
            WH40KMetaDecorationCategory.OocTitles when entry.SuppressTitlePrefix => FormattedMessage.EscapeText(_previewName),
            _ => BuildTitlePreviewMarkup(entry, selectedColor),
        };
        var preview = new RichTextLabel
        {
            HorizontalExpand = true,
            VerticalExpand = true,
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
            RectClipContent = true,
        };

        try
        {
            preview.SetMessage(FormattedMessage.FromMarkupOrThrow(markup), tagsAllowed: null);
        }
        catch (Exception exception)
        {
            if (_failedPreviewMarkup.Add(entry.Id))
                Log.Warning($"Failed to build WH40K decoration preview '{entry.Id}': {exception}");

            preview.SetMessage(FormattedMessage.FromUnformatted(BuildPlainPreview(entry)), tagsAllowed: null);
        }

        return preview;
    }

    private Control BuildGhostPreview(WH40KDecorationEntry entry)
    {
        var grid = new GridContainer
        {
            Columns = 2,
            HSeparationOverride = 8,
            VSeparationOverride = 8,
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
        };
        var tint = Color.TryFromHex(entry.GhostTintHex, out var parsedTint) ? parsedTint : Color.White;
        var added = 0;
        foreach (var direction in new[] { Direction.South, Direction.East, Direction.North, Direction.West })
        {
            var texture = ResolveGhostTexture(entry, direction);
            if (texture == null)
                continue;

            added++;
            grid.AddChild(new TextureRect
            {
                Texture = texture,
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                MinSize = new Vector2(44, 44),
                SetSize = new Vector2(44, 44),
                Modulate = tint,
            });
        }

        return added > 0
            ? grid
            : new Label
            {
                Text = BuildPlainPreview(entry),
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                Align = Label.AlignMode.Center,
            };
    }

    private Texture? ResolveGhostTexture(WH40KDecorationEntry entry, Direction direction)
    {
        var key = new GhostTextureKey(entry.GhostRsiPath, entry.GhostState, direction);
        if (_ghostTextureCache.TryGetValue(key, out var cached))
            return cached;

        Texture? result = null;
        if (string.IsNullOrWhiteSpace(entry.GhostRsiPath) ||
            !_resources.TryGetResource<RSIResource>(new ResPath(entry.GhostRsiPath), out var resource) ||
            !resource.RSI.TryGetState(entry.GhostState, out var state) ||
            state.DelayCount <= 0)
        {
            _ghostTextureCache[key] = null;
            return null;
        }

        result = state.GetFrame(direction.Convert(state.RsiDirections), 0);
        _ghostTextureCache[key] = result;
        return result;
    }

    private WH40KDecorationEntry? GetSelectedColor()
    {
        return _selected.TryGetValue(WH40KMetaDecorationCategory.OocNameColors, out var id)
            ? _entries.FirstOrDefault(entry => entry.Category == WH40KMetaDecorationCategory.OocNameColors && entry.Id == id)
            : null;
    }

    private string BuildColorMarkup(WH40KDecorationEntry entry, string text)
    {
        return WH40KDecorationMarkup.BuildGradientMarkup(
            text,
            entry.OocGradientColors,
            entry.OocColorHex,
            entry.OocGradientAnimated,
            entry.OocGradientDurationMs,
            entry.OocAuraHex,
            entry.OocAuraRadius,
            entry.OocAuraAlphaPercent);
    }

    private string BuildTitlePreviewMarkup(WH40KDecorationEntry title, WH40KDecorationEntry? color)
    {
        BuildTitlePreviewParts(title, out var titleText, out var nameText);
        var visualStyle = HasOwnVisualStyle(title) ? title : color ?? title;
        var titleMarkup = WH40KDecorationMarkup.BuildTitleMarkup(
            titleText,
            visualStyle.OocGradientColors,
            visualStyle.OocColorHex,
            visualStyle.OocGradientAnimated,
            visualStyle.OocGradientDurationMs,
            title.OocTitleEffect,
            title.OocTitleEffectRevealMs,
            title.OocTitleEffectHoldMs,
            title.OocTitleEffectDissolveMs,
            title.OocTitleOutlineHex,
            title.OocTitleOutlineWidth,
            title.OocTitleOutlineAlphaPercent,
            auraColorHex: visualStyle.OocAuraHex,
            auraRadius: visualStyle.OocAuraRadius,
            auraAlphaPercent: visualStyle.OocAuraAlphaPercent);

        if (string.IsNullOrWhiteSpace(nameText))
            return titleMarkup;

        var nameMarkup = color == null
            ? FormattedMessage.EscapeText(nameText)
            : BuildColorMarkup(color, nameText);
        return $"{titleMarkup} {nameMarkup}";
    }

    private static bool HasOwnVisualStyle(WH40KDecorationEntry decoration)
    {
        if (WH40KDecorationMarkup.BuildPalette(decoration.OocGradientColors, decoration.OocColorHex).Count > 0)
            return true;

        return decoration.OocAuraRadius > 0 && decoration.OocAuraAlphaPercent > 0 &&
               WH40KDecorationMarkup.TryResolveColor(decoration.OocAuraHex, out _);
    }

    private void BuildTitlePreviewParts(
        WH40KDecorationEntry title,
        out string titleText,
        out string nameText)
    {
        var previewKey = string.IsNullOrWhiteSpace(title.PreviewKey) ? title.TitleKey : title.PreviewKey;
        var fullTitle = $"({Loc.GetString(previewKey)})";
        var font = UserInterfaceManager.ThemeDefaults.LabelFont;
        var spaceWidth = MeasureTextWidth(" ", font);

        nameText = FitTextWithEllipsis(_previewName, PreviewTextMaxWidth);
        var availableTitleWidth = MathF.Max(40f, PreviewTextMaxWidth - MeasureTextWidth(nameText, font) - spaceWidth);
        titleText = FitTextWithEllipsis(fullTitle, availableTitleWidth);

        if (MeasureTextWidth($"{titleText} {nameText}", font) <= PreviewTextMaxWidth)
            return;

        var availableNameWidth = MathF.Max(30f, PreviewTextMaxWidth - MeasureTextWidth(titleText, font) - spaceWidth);
        nameText = FitTextWithEllipsis(_previewName, availableNameWidth);
    }

    private string FitTextWithEllipsis(string source, float maxWidth)
    {
        if (string.IsNullOrWhiteSpace(source))
            return string.Empty;

        var font = UserInterfaceManager.ThemeDefaults.LabelFont;
        var text = source.Trim();
        if (MeasureTextWidth(text, font) <= maxWidth)
            return text;

        const string ellipsis = "...";
        var availableWidth = Math.Max(0f, maxWidth - MeasureTextWidth(ellipsis, font));
        var width = 0f;
        var cutIndex = 0;
        foreach (var rune in text.EnumerateRunes())
        {
            var advance = GetRuneAdvance(font, rune);
            if (width + advance > availableWidth)
                break;

            width += advance;
            cutIndex += rune.Utf16SequenceLength;
        }

        return cutIndex <= 0 ? ellipsis : $"{text[..cutIndex]}{ellipsis}";
    }

    private float MeasureTextWidth(string text, Font font)
    {
        var width = 0f;
        foreach (var rune in text.EnumerateRunes())
        {
            width += GetRuneAdvance(font, rune);
        }

        return width;
    }

    private float GetRuneAdvance(Font font, Rune rune)
    {
        if (font.TryGetCharMetrics(rune, UIScale, out var metrics))
            return metrics.Advance;

        return font.GetCharMetrics(new Rune('?'), UIScale, fallback: false)?.Advance ?? 0f;
    }

    private string BuildPlainPreview(WH40KDecorationEntry entry)
    {
        return entry.Category switch
        {
            WH40KMetaDecorationCategory.GhostSkins => Loc.GetString("w40k-decs-ghost-preview-format", ("preview", Loc.GetString(entry.PreviewKey))),
            WH40KMetaDecorationCategory.OocTitles => $"({Loc.GetString(string.IsNullOrWhiteSpace(entry.PreviewKey) ? entry.TitleKey : entry.PreviewKey)}) {_previewName}",
            WH40KMetaDecorationCategory.OocNameColors => _previewName,
            _ => Loc.GetString(entry.TitleKey),
        };
    }

    private bool IsSelected(WH40KDecorationEntry entry)
    {
        return _selected.TryGetValue(entry.Category, out var selected) && selected == entry.Id;
    }

    private sealed class DecorationCard
    {
        public readonly WH40KDecorationEntry Entry;
        public readonly PanelContainer Panel;
        public readonly Button Button;

        public DecorationCard(WH40KDecorationEntry entry, PanelContainer panel, Button button)
        {
            Entry = entry;
            Panel = panel;
            Button = button;
        }
    }

    private readonly record struct GhostTextureKey(string RsiPath, string State, Direction Direction);

}
