using System;
using Content.Client.Administration.UI.CustomControls;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Content.Shared._WH40K.Administration.Mute;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._WH40K.Administration.Mute;

[GenerateTypedNameReferences]
public sealed partial class WH40KMutePanel : FancyWindow
{
    public event Action<WH40KCreateMuteRequest>? MuteSubmitted;
    public event Action<string>? PlayerChanged;

    [Dependency] private IGameTiming _gameTiming = default!;

    private string? _playerUsername;
    private double _timeEntered;
    private uint _multiplier;
    private TimeSpan? _buttonResetOn;
    private ErrorLevel _errorLevel;
    private bool _canMute;
    private bool _requestPending;

    private enum Tab
    {
        BasicInfo,
        Players,
    }

    private enum Multiplier
    {
        Minutes,
        Hours,
        Days,
        Weeks,
        Months,
        Years,
        Permanent
    }

    [Flags]
    private enum ErrorLevel : byte
    {
        None = 0,
        Minutes = 1 << 0,
        PlayerName = 1 << 1,
        Scope = 1 << 2,
    }

    public WH40KMutePanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Tabs.SetTabTitle((int) Tab.BasicInfo, Loc.GetString("wh40k-mute-panel-tabs-basic"));
        Tabs.SetTabTitle((int) Tab.Players, Loc.GetString("wh40k-mute-panel-tabs-players"));

        PlayerList.OnSelectionChanged += OnPlayerSelectionChanged;
        PlayerNameLine.OnFocusExit += _ => OnPlayerNameChanged();
        ChatMuteCheckbox.OnPressed += _ => OnScopeChanged();
        AHelpMuteCheckbox.OnPressed += _ => OnScopeChanged();
        TimeLine.OnTextChanged += OnMinutesChanged;
        MultiplierOption.OnItemSelected += args =>
        {
            MultiplierOption.SelectId(args.Id);
            OnMultiplierChanged();
        };
        SubmitButton.OnPressed += SubmitButtonOnPressed;

        MultiplierOption.AddItem(Loc.GetString("ban-panel-minutes"), (int) Multiplier.Minutes);
        MultiplierOption.AddItem(Loc.GetString("ban-panel-hours"), (int) Multiplier.Hours);
        MultiplierOption.AddItem(Loc.GetString("ban-panel-days"), (int) Multiplier.Days);
        MultiplierOption.AddItem(Loc.GetString("ban-panel-weeks"), (int) Multiplier.Weeks);
        MultiplierOption.AddItem(Loc.GetString("ban-panel-months"), (int) Multiplier.Months);
        MultiplierOption.AddItem(Loc.GetString("ban-panel-years"), (int) Multiplier.Years);
        MultiplierOption.AddItem(Loc.GetString("ban-panel-permanent"), (int) Multiplier.Permanent);
        MultiplierOption.SelectId((int) Multiplier.Permanent);
        OnMultiplierChanged();
        OnScopeChanged();
        ReasonTextEdit.Placeholder = new Rope.Leaf(Loc.GetString("wh40k-mute-panel-reason"));
    }

    public void UpdateMuteFlag(bool canMute, bool requestInFlight)
    {
        _canMute = canMute;
        _requestPending = requestInFlight;
        SubmitButton.Visible = canMute;
        ModulateSelfOverride = canMute ? null : Color.Red;
        UpdateSubmitEnabled();
    }

    public void SetRequestPending(bool pending)
    {
        _requestPending = pending;
        UpdateSubmitEnabled();
    }

    public void UpdatePlayerData(string playerName)
    {
        if (string.IsNullOrWhiteSpace(playerName))
        {
            PlayerNameLine.ModulateSelfOverride = Color.Red;
            _errorLevel |= ErrorLevel.PlayerName;
            UpdateSubmitEnabled();
            return;
        }

        _playerUsername = playerName;
        PlayerNameLine.Text = playerName;
        PlayerNameLine.ModulateSelfOverride = null;
        _errorLevel &= ~ErrorLevel.PlayerName;
        UpdateSubmitEnabled();
    }

    private void OnPlayerNameChanged()
    {
        if (_playerUsername == PlayerNameLine.Text)
            return;

        _playerUsername = PlayerNameLine.Text;
        _errorLevel = string.IsNullOrWhiteSpace(_playerUsername)
            ? _errorLevel | ErrorLevel.PlayerName
            : _errorLevel & ~ErrorLevel.PlayerName;
        UpdateSubmitEnabled();
        PlayerChanged?.Invoke(_playerUsername ?? string.Empty);
    }

    private void OnPlayerSelectionChanged(PlayerInfo? player)
    {
        PlayerNameLine.Text = player?.Username ?? string.Empty;
        OnPlayerNameChanged();
    }

    private void OnScopeChanged()
    {
        if (!ChatMuteCheckbox.Pressed && !AHelpMuteCheckbox.Pressed)
        {
            _errorLevel |= ErrorLevel.Scope;
            ChatMuteCheckbox.ModulateSelfOverride = Color.Red;
            AHelpMuteCheckbox.ModulateSelfOverride = Color.Red;
        }
        else
        {
            _errorLevel &= ~ErrorLevel.Scope;
            ChatMuteCheckbox.ModulateSelfOverride = null;
            AHelpMuteCheckbox.ModulateSelfOverride = null;
        }
        UpdateSubmitEnabled();
    }

    private void OnMinutesChanged(LineEdit.LineEditEventArgs args)
    {
        ValidateMinutes(args.Text);
    }

    private void ValidateMinutes(string text)
    {
        if (!double.TryParse(text, out var result) ||
            !double.IsFinite(result) ||
            result <= 0 ||
            _multiplier != 0 && result * _multiplier > WH40KMutePolicy.MaxTemporaryDuration.TotalMinutes)
        {
            ExpiresLabel.Text = Loc.GetString("ban-panel-expiry-error");
            _errorLevel |= ErrorLevel.Minutes;
            TimeLine.ModulateSelfOverride = Color.Red;
            UpdateSubmitEnabled();
            return;
        }

        _errorLevel &= ~ErrorLevel.Minutes;
        TimeLine.ModulateSelfOverride = null;
        _timeEntered = result;
        UpdateSubmitEnabled();
        UpdateExpiresLabel();
    }

    private void OnMultiplierChanged()
    {
        var permanent = MultiplierOption.SelectedId == (int) Multiplier.Permanent;
        TimeLine.Editable = !permanent;
        _multiplier = MultiplierOption.SelectedId switch
        {
            (int) Multiplier.Minutes => 1,
            (int) Multiplier.Hours => 60,
            (int) Multiplier.Days => 60 * 24,
            (int) Multiplier.Weeks => 60 * 24 * 7,
            (int) Multiplier.Months => 60 * 24 * 30,
            (int) Multiplier.Years => 60 * 24 * 365,
            (int) Multiplier.Permanent => 0,
            _ => throw new ArgumentOutOfRangeException(nameof(MultiplierOption.SelectedId))
        };
        if (permanent)
        {
            _errorLevel &= ~ErrorLevel.Minutes;
            TimeLine.ModulateSelfOverride = null;
        }
        else
        {
            ValidateMinutes(TimeLine.Text);
        }

        UpdateSubmitEnabled();
        UpdateExpiresLabel();
    }

    private void UpdateExpiresLabel()
    {
        var minutes = Math.Min(WH40KMutePolicy.MaxTemporaryDuration.TotalMinutes, _timeEntered * _multiplier);
        ExpiresLabel.Text = minutes == 0
            ? $"{Loc.GetString("admin-note-editor-expiry-label")} {Loc.GetString("server-ban-string-never")}" 
            : $"{Loc.GetString("admin-note-editor-expiry-label")} {DateTime.Now + TimeSpan.FromMinutes(minutes):yyyy/MM/dd HH:mm:ss}";
    }

    private void UpdateSubmitEnabled()
    {
        SubmitButton.Disabled = !_canMute || _requestPending || _errorLevel != ErrorLevel.None;
    }

    private void ResetTextEditor(GUIBoundKeyEventArgs _)
    {
        ReasonTextEdit.ModulateSelfOverride = null;
        ReasonTextEdit.OnKeyBindDown -= ResetTextEditor;
    }

    private void SubmitButtonOnPressed(BaseButton.ButtonEventArgs args)
    {
        var reason = Rope.Collapse(ReasonTextEdit.TextRope);
        if (string.IsNullOrWhiteSpace(reason))
        {
            Tabs.CurrentTab = (int) Tab.BasicInfo;
            ReasonTextEdit.GrabKeyboardFocus();
            ReasonTextEdit.ModulateSelfOverride = Color.Red;
            ReasonTextEdit.OnKeyBindDown += ResetTextEditor;
            return;
        }

        if (_buttonResetOn is null)
        {
            _buttonResetOn = _gameTiming.CurTime.Add(TimeSpan.FromSeconds(3));
            SubmitButton.ModulateSelfOverride = Color.Red;
            SubmitButton.Text = Loc.GetString("ban-panel-confirm");
            return;
        }

        var type = WH40KMuteType.None;
        if (ChatMuteCheckbox.Pressed)
            type |= WH40KMuteType.Chat;
        if (AHelpMuteCheckbox.Pressed)
            type |= WH40KMuteType.AHelp;

        var totalMinutes = _timeEntered * _multiplier;
        if (totalMinutes > WH40KMutePolicy.MaxTemporaryDuration.TotalMinutes)
        {
            _errorLevel |= ErrorLevel.Minutes;
            TimeLine.ModulateSelfOverride = Color.Red;
            ExpiresLabel.Text = Loc.GetString("ban-panel-expiry-error");
            UpdateSubmitEnabled();
            return;
        }

        MuteSubmitted?.Invoke(new WH40KCreateMuteRequest(
            _playerUsername,
            type,
            (uint) totalMinutes,
            reason,
            EraseCheckbox.Pressed));
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (_buttonResetOn is null || _gameTiming.CurTime <= _buttonResetOn)
            return;

        _buttonResetOn = null;
        SubmitButton.ModulateSelfOverride = null;
        SubmitButton.Text = Loc.GetString("wh40k-mute-panel-submit");
    }
}
