using Content.Client.PDA;
using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._NF.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class AppraisalUiFragment : BoxContainer
{
    public AppraisalUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;
    }

    public void UpdateState(List<AppraisedItem> items)
    {
        AppraisedItemContainer.RemoveAllChildren();

        // Reverse the list so the oldest entries appear at the bottom.
        items.Reverse();

        // Enable horizontal scrolling only when the table can no longer fit in the display.
        ScrollContainer.HScrollEnabled = items.Count > 9;

        foreach (var item in items)
        {
            AddAppraisedItem(item);
        }
    }

    private void AddAppraisedItem(AppraisedItem item)
    {
        var row = new BoxContainer
        {
            HorizontalExpand = true,
            Orientation = LayoutOrientation.Horizontal,
            Margin = new Thickness(4)
        };

        var nameLabel = new Label
        {
            Text = item.Name,
            FontColorOverride = PdaTerminalPalette.PrimaryText,
            HorizontalExpand = true,
            ClipText = true
        };
        row.AddChild(nameLabel);

        var valueLabel = new Label
        {
            Text = item.AppraisedPrice,
            FontColorOverride = PdaTerminalPalette.Accent,
            HorizontalExpand = true,
            ClipText = true
        };
        row.AddChild(valueLabel);

        AppraisedItemContainer.AddChild(row);
    }
}
