using System;
using Content.Shared.Localizations;
using Robust.Client.AutoGenerated;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client.UserInterface.Systems.Localization;

[GenerateTypedNameReferences]
public sealed partial class LanguageRestartPopup : FancyWindow
{
    public event Action? OnCancelled;
    public event Action? OnConfirmed;

    public LanguageRestartPopup(string cultureName)
    {
        RobustXamlLoader.Load(this);

        CancelButton.OnPressed += _ => Cancel();
        ConfirmButton.OnPressed += _ => Confirm();

        using var scope = new LocalizationCultureScope(
            IoCManager.Resolve<ILocalizationManager>(), cultureName);
        Title = Loc.GetString("ui-language-restart-title");
        MessageLabel.Text = Loc.GetString("ui-language-restart-message");
        CancelButton.Text = Loc.GetString("ui-language-restart-cancel");
        ConfirmButton.Text = Loc.GetString("ui-language-restart-confirm");
    }

    public void Cancel() => OnCancelled?.Invoke();

    public void Confirm() => OnConfirmed?.Invoke();
}
