using Content.Shared._WH40K.CharacterCreation;
using Content.Shared._WH40K.CharacterDescription;
using Content.Shared._WH40K.DetailExaminable;
using Content.Client._WH40K.CharacterDescription;
using Content.Client.Stylesheets;
using Content.Shared.Humanoid.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Enums;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._WH40K.DetailExaminable;

[GenerateTypedNameReferences]
public sealed partial class Wh40kDetailExaminableWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypes = default!;
    [Dependency] private readonly IEntityManager _entities = default!;

    private readonly Direction[] _directions = [Direction.South, Direction.West, Direction.North, Direction.East];
    private int _directionIndex;
    private EntityUid _target;

    public Wh40kDetailExaminableWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        RotateLeft.OnPressed += _ => Rotate(-1);
        RotateRight.OnPressed += _ => Rotate(1);

        DescriptionTabs.SetTabTitle(0, Loc.GetString("flavor-tab-flavor"));
        DescriptionTabs.SetTabTitle(1, Loc.GetString("flavor-tab-character"));
        DescriptionTabs.SetTabTitle(2, Loc.GetString("flavor-tab-gyr"));
    }

    public void UpdateState(Wh40kDetailExaminableEuiState state)
    {
        _target = _entities.GetEntity(state.Target);
        PreviewSprite.SetEntity(_target);
        PreviewSprite.OverrideDirection = _directions[_directionIndex];

        // Видимость уже авторитетно вычислена сервером. Повторная проверка CVar на клиенте
        // может скрыть разрешённое сервером содержимое при задержке репликации настройки.
        DescriptionTabs.SetTabVisible(1, state.ShowTraits);
        DescriptionTabs.SetTabVisible(2, state.ShowPreferences);
        OocSection.Visible = state.ShowOoc;
        LinksSection.Visible = state.ShowLinks;
        SupplementaryDetails.Visible = OocSection.Visible || LinksSection.Visible;
        TagsText.Visible = state.ShowTags;

        PreviewName.Text = state.Name;
        PreviewSummary.Text = BuildSummary(state);
        SetText(AppearanceText, state.FlavorText, "detail-examinable-empty-flavor");
        SetText(CharacterText, state.CharacterFlavorText, "detail-examinable-empty-character");
        SetText(OocText, state.OocFlavorText, "detail-examinable-empty-ooc");
        SetText(GreenText, state.GreenFlavorText, "detail-examinable-empty-green");
        SetText(YellowText, state.YellowFlavorText, "detail-examinable-empty-yellow");
        SetText(RedText, state.RedFlavorText, "detail-examinable-empty-red");
        TagsText.Text = state.TagsFlavorText;
        SetPortrait(state.PortraitId);
        UpdateLinks(state.LinksFlavorText);
    }

    private void Rotate(int step)
    {
        _directionIndex = (_directionIndex + step + _directions.Length) % _directions.Length;
        PreviewSprite.OverrideDirection = _directions[_directionIndex];
    }

    private void SetPortrait(string? portraitId)
    {
        if (portraitId is null || !_prototypes.TryIndex<Wh40kPortraitPrototype>(portraitId, out var portrait))
        {
            PreviewPortrait.Texture = null;
            return;
        }

        PreviewPortrait.Texture = _entities.System<SpriteSystem>().Frame0(portrait.LargeSprite);
    }

    private void UpdateLinks(string linksText)
    {
        Links.RemoveAllChildren();
        if (string.IsNullOrWhiteSpace(linksText))
        {
            Links.AddChild(new Label
            {
                Text = Loc.GetString("detail-examinable-empty-links"),
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Center,
                FontColorOverride = Color.Gray,
            });
            return;
        }

        foreach (var link in linksText.Split(new[] { ',', ' ', '\n', '\r', '\t' }, StringSplitOptions.RemoveEmptyEntries))
        {
            var text = link.Trim();
            if (IsAllowedLink(text))
            {
                var button = new Button
                {
                    Text = text.Length > 40 ? text[..37] + "..." : text,
                    ToolTip = text,
                    HorizontalExpand = true,
                    HorizontalAlignment = HAlignment.Center,
                    StyleClasses = { StyleBase.ButtonOpenBoth },
                };
                button.OnPressed += _ => IoCManager.Resolve<IUriOpener>().OpenUri(text);
                Links.AddChild(button);
            }
            else
            {
                Links.AddChild(new Label
                {
                    Text = text,
                    ToolTip = text,
                    HorizontalExpand = true,
                    HorizontalAlignment = HAlignment.Center,
                    ClipText = true,
                    FontColorOverride = Color.Gray,
                });
            }
        }
    }

    private static bool IsAllowedLink(string link)
    {
        return link.StartsWith("https://docs.google.com/", StringComparison.OrdinalIgnoreCase) ||
               link.StartsWith("https://disk.yandex.ru/", StringComparison.OrdinalIgnoreCase) ||
               link.StartsWith("https://disk.yandex.by/", StringComparison.OrdinalIgnoreCase) ||
               link.StartsWith("https://docs.yandex.ru/", StringComparison.OrdinalIgnoreCase) ||
               link.StartsWith("https://docs.yandex.by/", StringComparison.OrdinalIgnoreCase) ||
               link.StartsWith("https://imgbb.com/", StringComparison.OrdinalIgnoreCase) ||
               link.StartsWith("https://ru.imgbb.com/", StringComparison.OrdinalIgnoreCase) ||
               link.StartsWith("https://ibb.co/", StringComparison.OrdinalIgnoreCase) ||
               link.StartsWith("https://gyazo.com/", StringComparison.OrdinalIgnoreCase) ||
               link.StartsWith("https://i.gyazo.com/", StringComparison.OrdinalIgnoreCase) ||
               link.StartsWith("https://steamcommunity.com/", StringComparison.OrdinalIgnoreCase) ||
               link.StartsWith("https://images.steamusercontent.com/", StringComparison.OrdinalIgnoreCase) ||
               link.StartsWith("https://media.discordapp.net/attachments/", StringComparison.OrdinalIgnoreCase) ||
               link.StartsWith("https://cdn.discordapp.com/attachments/", StringComparison.OrdinalIgnoreCase);
    }

    private static string BuildSummary(Wh40kDetailExaminableEuiState state)
    {
        var species = IoCManager.Resolve<IPrototypeManager>().TryIndex(state.Species, out SpeciesPrototype? prototype)
            ? Loc.GetString(prototype.Name)
            : state.Species.ToString();
        var sex = Loc.GetString($"humanoid-profile-editor-sex-{state.Sex.ToString().ToLowerInvariant()}-text");
        var gender = Loc.GetString($"humanoid-profile-editor-pronouns-{state.Gender.ToString().ToLowerInvariant()}-text");
        return $"{species} | {sex} | {gender}";
    }

    private static void SetText(RichTextLabel label, string text, string emptyKey)
    {
        var content = string.IsNullOrWhiteSpace(text) ? Loc.GetString(emptyKey) : text;
        var sanitized = Wh40kDescriptionMarkup.SanitizeBasic(content);
        label.SetMessage(FormattedMessage.FromMarkupPermissive(sanitized), Wh40kDescriptionMarkupTags.Basic);
    }
}
