name: "Labels: Review"

on:
  pull_request_target:
    types: [review_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  add_label:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Mark PR as needing review
      uses: actions/github-script@v8
      with:
        script: |
          const issueNumber = context.payload.pull_request.number;
          await github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issueNumber,
            labels: ['S: Needs Review'],
          });

          try {
            await github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              name: 'S: Awaiting Changes',
            });
          } catch (error) {
            if (error.status !== 404)
              throw error;
          }
