name: "Labels: Untriaged"

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  add_label:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Mark unlabeled issue or PR as untriaged
      uses: actions/github-script@v8
      with:
        script: |
          const issueNumber = context.issue.number;
          const { data: labels } = await github.rest.issues.listLabelsOnIssue({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issueNumber,
          });

          if (labels.length === 0) {
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              labels: ['S: Untriaged'],
            });
          }
