name: RSI Validator

on:
  push:
    branches: [ main, staging, stable ]
  merge_group:
  pull_request:
    paths:
      - '**.rsi/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate_rsis:
    name: Validate RSIs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
      - name: Setup Submodule
        run: git submodule update --init --recursive
      - name: Set up Python 3.10
        uses: actions/setup-python@v7
        with:
          python-version: "3.10"
      - name: Install Python dependencies
        run: |
          python3 -m pip install --disable-pip-version-check pillow jsonschema
      - name: Validate RSIs
        run: |
          python3 RobustToolbox/Schemas/validate_rsis.py Resources/
